import { type CurriculumChapter } from './types';
import { OFFICIAL_CBSE_SYLLABUS_PORTAL, OFFICIAL_NCERT_PORTAL } from './cbse-2027-database';

export const CLASS_12_CHAPTERS: CurriculumChapter[] = [
  // -------------------------------------------------------------------------
  // PHYSICS (042)
  // -------------------------------------------------------------------------
  {
    id: 'c12-phy-1',
    subjectId: 'cbse-12-physics',
    subjectName: 'Physics',
    subjectCode: '042',
    class: '12',
    academicSession: '2026-27',
    title: 'Electric Charges and Fields',
    chapterNumber: 1,
    unitNumber: 1,
    unitName: 'Electrostatics',
    description: "Electric charges, Conservation of charge, Coulomb law-force between two-point charges, forces between multiple charges; superposition principle and continuous charge distribution. Electric field, electric field due to a point charge, electric field lines, electric dipole, electric field due to a dipole, torque on a dipole in uniform electric field. Electric flux, statement of Gauss theorem and its applications to find field due to infinitely long straight wire, uniformly charged infinite plane sheet and uniformly charged thin spherical shell.",
    defaultEstimatedHours: 8,
    examWeightage: 'critical',
    difficulty: 'hard',
    prerequisites: ['phy-vectors', 'phy-laws'],
    inCbseSyllabus: true,
    topics: [
      { id: 'c12-p1-t1', name: "Coulomb's Law F = k q1 q2 / r^2 and vector superposition", inCbseSyllabus: true },
      { id: 'c12-p1-t2', name: 'Electric dipole moment p = q * 2a, axial and equatorial fields', inCbseSyllabus: true },
      { id: 'c12-p1-t3', name: "Gauss's Law flux = q_enc / epsilon_0 and derivations (wire, sheet, spherical shell)", inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?leph1=1-8`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'c12-phy-2',
    subjectId: 'cbse-12-physics',
    subjectName: 'Physics',
    subjectCode: '042',
    class: '12',
    academicSession: '2026-27',
    title: 'Electrostatic Potential and Capacitance',
    chapterNumber: 2,
    unitNumber: 1,
    unitName: 'Electrostatics',
    description: "Electric potential, potential difference, electric potential due to a point charge, a dipole and system of charges; equipotential surfaces, electrical potential energy of a system of two-point charges and of electric dipole in an electrostatic field. Conductors and insulators, free charges and bound charges inside a conductor. Dielectrics and electric polarisation, capacitors and capacitance, combination of capacitors in series and in parallel, capacitance of a parallel plate capacitor with and without dielectric medium between the plates, energy stored in a capacitor.",
    defaultEstimatedHours: 8,
    examWeightage: 'critical',
    difficulty: 'hard',
    prerequisites: ['c12-phy-1'],
    inCbseSyllabus: true,
    topics: [
      { id: 'c12-p2-t1', name: 'Electrostatic potential V = k Q / r, potential energy U = k q1 q2 / r', inCbseSyllabus: true },
      { id: 'c12-p2-t2', name: 'Equipotential surfaces properties and relation E = -dV/dr', inCbseSyllabus: true },
      { id: 'c12-p2-t3', name: 'Parallel plate capacitor C = epsilon_0 A / d, dielectric effect C = K C_0', inCbseSyllabus: true },
      { id: 'c12-p2-t4', name: 'Series and parallel combination, energy stored U = 1/2 C V^2', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?leph1=2-8`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'c12-phy-3',
    subjectId: 'cbse-12-physics',
    subjectName: 'Physics',
    subjectCode: '042',
    class: '12',
    academicSession: '2026-27',
    title: 'Current Electricity',
    chapterNumber: 3,
    unitNumber: 2,
    unitName: 'Current Electricity',
    description: "Electric current, flow of electric charges in a metallic conductor, drift velocity, mobility and their relation with electric current; Ohm law, electrical resistance, V-I characteristics (linear and non-linear), electrical energy and power, electrical resistivity and conductivity, temperature dependence of resistance. Internal resistance of a cell, potential difference and emf of a cell, combination of cells in series and in parallel, Kirchhoff rules and simple applications, Wheatstone bridge.",
    defaultEstimatedHours: 8,
    examWeightage: 'critical',
    difficulty: 'medium',
    prerequisites: ['c10-sci-11'],
    inCbseSyllabus: true,
    topics: [
      { id: 'c12-p3-t1', name: 'Drift velocity v_d = e E tau / m and current relation I = n e A v_d', inCbseSyllabus: true },
      { id: 'c12-p3-t2', name: 'Ohm law vector form J = sigma E and temperature coefficient of resistance', inCbseSyllabus: true },
      { id: 'c12-p3-t3', name: 'Cell EMF E = V + Ir, series and parallel grouping of cells', inCbseSyllabus: true },
      { id: 'c12-p3-t4', name: "Kirchhoff's Current Law (KCL) & Voltage Law (KVL), balanced Wheatstone bridge", inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?leph1=3-8`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'c12-phy-4',
    subjectId: 'cbse-12-physics',
    subjectName: 'Physics',
    subjectCode: '042',
    class: '12',
    academicSession: '2026-27',
    title: 'Moving Charges and Magnetism',
    chapterNumber: 4,
    unitNumber: 3,
    unitName: 'Magnetic Effects of Current and Magnetism',
    description: "Concept of magnetic field, Oersted experiment. Biot - Savart law and its application to current carrying circular loop. Ampere law and its applications to infinitely long straight wire. Straight solenoid. Force on a moving charge in uniform magnetic and electric fields. Force on a current-carrying conductor in a uniform magnetic field. Force between two parallel current-carrying conductors-definition of ampere. Torque experienced by a current loop in uniform magnetic field; Current loop as a magnetic dipole and its magnetic dipole moment. Moving coil galvanometer its current sensitivity and conversion to ammeter and voltmeter.",
    defaultEstimatedHours: 9,
    examWeightage: 'critical',
    difficulty: 'hard',
    prerequisites: ['c12-phy-3'],
    inCbseSyllabus: true,
    topics: [
      { id: 'c12-p4-t1', name: "Biot-Savart Law dB = (mu_0 / 4pi) * (I dl x r) / r^3 and circular loop on axis", inCbseSyllabus: true },
      { id: 'c12-p4-t2', name: "Ampere's Circuital Law and solenoid field B = mu_0 n I", inCbseSyllabus: true },
      { id: 'c12-p4-t3', name: 'Lorentz force F = q(E + v x B), force on wire F = I(L x B), parallel wires force per unit length', inCbseSyllabus: true },
      { id: 'c12-p4-t4', name: 'Moving coil galvanometer principle, conversion to Ammeter (shunt S) and Voltmeter (series R)', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?leph1=4-8`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'c12-phy-6',
    subjectId: 'cbse-12-physics',
    subjectName: 'Physics',
    subjectCode: '042',
    class: '12',
    academicSession: '2026-27',
    title: 'Electromagnetic Induction',
    chapterNumber: 6,
    unitNumber: 4,
    unitName: 'Electromagnetic Induction and Alternating Currents',
    description: "Electromagnetic induction; Faraday laws, induced EMF and current; Lenz Law, Eddy currents. Self and mutual induction.",
    defaultEstimatedHours: 6,
    examWeightage: 'high',
    difficulty: 'medium',
    prerequisites: ['c12-phy-4'],
    inCbseSyllabus: true,
    topics: [
      { id: 'c12-p6-t1', name: "Faraday's Laws e = -dPhi/dt and Lenz's Law conservation of energy", inCbseSyllabus: true },
      { id: 'c12-p6-t2', name: 'Motional EMF e = B l v and Eddy currents applications', inCbseSyllabus: true },
      { id: 'c12-p6-t3', name: 'Self-inductance L, mutual inductance M, energy in inductor U = 1/2 L I^2', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?leph1=6-8`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'c12-phy-7',
    subjectId: 'cbse-12-physics',
    subjectName: 'Physics',
    subjectCode: '042',
    class: '12',
    academicSession: '2026-27',
    title: 'Alternating Current',
    chapterNumber: 7,
    unitNumber: 4,
    unitName: 'Electromagnetic Induction and Alternating Currents',
    description: "Alternating currents, peak and RMS value of alternating current/voltage; reactance and impedance; LCR series circuit, resonance; power in AC circuits, wattless current. AC generator and transformer.",
    defaultEstimatedHours: 7,
    examWeightage: 'critical',
    difficulty: 'hard',
    prerequisites: ['c12-phy-6'],
    inCbseSyllabus: true,
    topics: [
      { id: 'c12-p7-t1', name: 'RMS values I_rms = I_0 / sqrt(2) and phasor diagrams for R, L, C circuits', inCbseSyllabus: true },
      { id: 'c12-p7-t2', name: 'Series LCR circuit impedance Z = sqrt(R^2 + (X_L - X_C)^2) and resonance omega_0 = 1/sqrt(LC)', inCbseSyllabus: true },
      { id: 'c12-p7-t3', name: 'Power in AC circuit P = V_rms I_rms cos phi and Transformer ratio V_s / V_p = N_s / N_p', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?leph1=7-8`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'c12-phy-9',
    subjectId: 'cbse-12-physics',
    subjectName: 'Physics',
    subjectCode: '042',
    class: '12',
    academicSession: '2026-27',
    title: 'Ray Optics and Optical Instruments',
    chapterNumber: 9,
    unitNumber: 5,
    unitName: 'Optics',
    description: "Refraction of light, total internal reflection and its optical applications, optical fibres, refraction at spherical surfaces, lenses, thin lens formula, lensmaker formula, magnification, power of a lens, combination of thin lenses in contact, refraction of light through a prism. Optical instruments: Microscopes and astronomical telescopes (reflecting and refracting) and their magnifying powers.",
    defaultEstimatedHours: 9,
    examWeightage: 'critical',
    difficulty: 'hard',
    prerequisites: ['c10-sci-9'],
    inCbseSyllabus: true,
    topics: [
      { id: 'c12-p9-t1', name: 'Total Internal Reflection (TIR), critical angle sin C = 1/n, and optical fibers', inCbseSyllabus: true },
      { id: 'c12-p9-t2', name: "Lens Maker's Formula 1/f = (n - 1)(1/R1 - 1/R2) and spherical surface refraction", inCbseSyllabus: true },
      { id: 'c12-p9-t3', name: 'Prism refraction formula n = sin((A + D_m)/2) / sin(A/2)', inCbseSyllabus: true },
      { id: 'c12-p9-t4', name: 'Compound Microscope and Astronomical Telescope magnifying powers in normal adjustment and D', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?leph2=1-6`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'c12-phy-10',
    subjectId: 'cbse-12-physics',
    subjectName: 'Physics',
    subjectCode: '042',
    class: '12',
    academicSession: '2026-27',
    title: 'Wave Optics',
    chapterNumber: 10,
    unitNumber: 5,
    unitName: 'Optics',
    description: "Wave front and Huygens principle, reflection and refraction of plane wave at a plane surface using wave fronts. Proof of laws of reflection and refraction using Huygens principle. Interference, Young double slit experiment and expression for fringe width, coherent sources and sustained interference of light. Diffraction due to a single slit, width of central maximum.",
    defaultEstimatedHours: 7,
    examWeightage: 'critical',
    difficulty: 'hard',
    prerequisites: ['c12-phy-9'],
    inCbseSyllabus: true,
    topics: [
      { id: 'c12-p10-t1', name: "Huygens' Principle and proof of laws of reflection and Snell's Law of refraction", inCbseSyllabus: true },
      { id: 'c12-p10-t2', name: "Young's Double Slit Experiment (YDSE) fringe width beta = lambda D / d", inCbseSyllabus: true },
      { id: 'c12-p10-t3', name: 'Single slit diffraction central maximum angular width 2 lambda / a', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?leph2=2-6`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'c12-phy-14',
    subjectId: 'cbse-12-physics',
    subjectName: 'Physics',
    subjectCode: '042',
    class: '12',
    academicSession: '2026-27',
    title: 'Semiconductor Electronics: Materials, Devices and Simple Circuits',
    chapterNumber: 14,
    unitNumber: 7,
    unitName: 'Electronic Devices',
    description: "Energy bands in conductors, semiconductors and insulators (qualitative ideas only) Intrinsic and extrinsic semiconductors- p and n type, p-n junction. Semiconductor diode - I-V characteristics in forward and reverse bias, application of junction diode as a rectifier.",
    defaultEstimatedHours: 6,
    examWeightage: 'high',
    difficulty: 'easy',
    prerequisites: [],
    inCbseSyllabus: true,
    topics: [
      { id: 'c12-p14-t1', name: 'Energy band theory (valence band, conduction band, forbidden energy gap Eg)', inCbseSyllabus: true },
      { id: 'c12-p14-t2', name: 'Intrinsic and extrinsic (n-type and p-type with dopants), depletion region and barrier potential', inCbseSyllabus: true },
      { id: 'c12-p14-t3', name: 'p-n junction diode forward and reverse bias characteristics, Half wave and Full wave rectifiers', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?leph2=6-6`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },

  // -------------------------------------------------------------------------
  // CHEMISTRY (043)
  // -------------------------------------------------------------------------
  {
    id: 'c12-chem-1',
    subjectId: 'cbse-12-chemistry',
    subjectName: 'Chemistry',
    subjectCode: '043',
    class: '12',
    academicSession: '2026-27',
    title: 'Solutions',
    chapterNumber: 1,
    unitNumber: 1,
    unitName: 'Solutions',
    description: "Types of solutions, expression of concentration of solutions of solids in liquids, solubility of gases in liquids, solid solutions, Raoult law, colligative properties - relative lowering of vapour pressure, elevation of boiling point, depression of freezing point, osmotic pressure, determination of molecular masses using colligative properties, abnormal molecular mass, Van't Hoff factor.",
    defaultEstimatedHours: 8,
    examWeightage: 'critical',
    difficulty: 'medium',
    prerequisites: ['chem-basic'],
    inCbseSyllabus: true,
    topics: [
      { id: 'c12-c1-t1', name: "Henry's Law and Raoult's Law for ideal and non-ideal solutions with deviations", inCbseSyllabus: true },
      { id: 'c12-c1-t2', name: 'Colligative properties: Delta Tb = Kb m, Delta Tf = Kf m, pi = CRT', inCbseSyllabus: true },
      { id: 'c12-c1-t3', name: "Van't Hoff factor (i) for association and dissociation calculations", inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?lech1=1-5`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'c12-chem-2',
    subjectId: 'cbse-12-chemistry',
    subjectName: 'Chemistry',
    subjectCode: '043',
    class: '12',
    academicSession: '2026-27',
    title: 'Electrochemistry',
    chapterNumber: 2,
    unitNumber: 2,
    unitName: 'Electrochemistry',
    description: "Redox reactions, EMF of a cell, standard electrode potential, Nernst equation and its application to chemical cells, Relation between Gibbs energy change and EMF of a cell, conductance in electrolytic solutions, specific and molar conductivity, variations of conductivity with concentration, Kohlrausch Law, electrolysis and law of electrolysis, dry cell-electrolytic cells and Galvanic cells, lead accumulator, fuel cells, corrosion.",
    defaultEstimatedHours: 8,
    examWeightage: 'critical',
    difficulty: 'hard',
    prerequisites: ['chem-redox'],
    inCbseSyllabus: true,
    topics: [
      { id: 'c12-c2-t1', name: "Galvanic cell, standard electrode potentials and Nernst Equation E_cell = E°_cell - (0.0591/n) log Q", inCbseSyllabus: true },
      { id: 'c12-c2-t2', name: 'Relation Delta G° = -n F E°_cell and equilibrium constant log K_c = n E°_cell / 0.0591', inCbseSyllabus: true },
      { id: 'c12-c2-t3', name: "Molar conductivity Lambda_m and Kohlrausch's Law of independent migration of ions", inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?lech1=2-5`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'c12-chem-3',
    subjectId: 'cbse-12-chemistry',
    subjectName: 'Chemistry',
    subjectCode: '043',
    class: '12',
    academicSession: '2026-27',
    title: 'Chemical Kinetics',
    chapterNumber: 3,
    unitNumber: 3,
    unitName: 'Chemical Kinetics',
    description: "Rate of a reaction (Average and instantaneous), factors affecting rate of reaction: concentration, temperature, catalyst; order and molecularity of a reaction, rate law and specific rate constant, integrated rate equations and half-life (only for zero and first order reactions), concept of collision theory, Arrhenius equation, activation energy.",
    defaultEstimatedHours: 7,
    examWeightage: 'critical',
    difficulty: 'medium',
    prerequisites: [],
    inCbseSyllabus: true,
    topics: [
      { id: 'c12-c3-t1', name: 'Rate law, order vs molecularity of reaction', inCbseSyllabus: true },
      { id: 'c12-c3-t2', name: 'Integrated rate equations for Zero Order (k = [A0]-[A]/t) and First Order (k = 2.303/t log([A0]/[A]))', inCbseSyllabus: true },
      { id: 'c12-c3-t3', name: "Half life t_1/2 = 0.693 / k and Arrhenius equation k = A e^(-Ea / RT)", inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?lech1=3-5`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'c12-chem-4',
    subjectId: 'cbse-12-chemistry',
    subjectName: 'Chemistry',
    subjectCode: '043',
    class: '12',
    academicSession: '2026-27',
    title: 'The d- and f-Block Elements',
    chapterNumber: 4,
    unitNumber: 4,
    unitName: 'The d- and f-Block Elements',
    description: "General introduction, electronic configuration, occurrence and characteristics of transition metals, general trends in properties of the first-row transition metals - metallic character, ionization enthalpy, oxidation states, ionic radii, colour, catalytic property, magnetic properties, interstitial compounds, alloy formation, preparation and properties of K2Cr2O7 and KMnO4. Lanthanoids - Electronic configuration, oxidation states, chemical reactivity and lanthanoid contraction.",
    defaultEstimatedHours: 7,
    examWeightage: 'high',
    difficulty: 'medium',
    prerequisites: ['chem-periodic'],
    inCbseSyllabus: true,
    topics: [
      { id: 'c12-c4-t1', name: 'Variable oxidation states, catalytic property, interstitial compounds and alloy formation', inCbseSyllabus: true },
      { id: 'c12-c4-t2', name: 'Spin only magnetic moment mu = sqrt(n(n+2)) BM and coloured ion d-d transitions', inCbseSyllabus: true },
      { id: 'c12-c4-t3', name: 'Preparation and oxidizing reactions of KMnO4 and K2Cr2O7, Lanthanoid contraction', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?lech1=4-5`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'c12-chem-5',
    subjectId: 'cbse-12-chemistry',
    subjectName: 'Chemistry',
    subjectCode: '043',
    class: '12',
    academicSession: '2026-27',
    title: 'Coordination Compounds',
    chapterNumber: 5,
    unitNumber: 5,
    unitName: 'Coordination Compounds',
    description: "Coordination compounds - Introduction, ligands, coordination number, colour, magnetic properties and shapes, IUPAC nomenclature of mononuclear coordination compounds. Bonding, Werner theory, VBT, and CFT; structure and stereoisomerism, importance of coordination compounds (in qualitative inclusion, extraction of metals and biological system).",
    defaultEstimatedHours: 8,
    examWeightage: 'critical',
    difficulty: 'hard',
    prerequisites: ['c12-chem-4', 'chem-bonding'],
    inCbseSyllabus: true,
    topics: [
      { id: 'c12-c5-t1', name: 'Werner theory, ligands classification (monodentate, bidentate, ambidentate, chelating)', inCbseSyllabus: true },
      { id: 'c12-c5-t2', name: 'IUPAC nomenclature of coordination complexes and isomerism (geometrical & optical)', inCbseSyllabus: true },
      { id: 'c12-c5-t3', name: 'Valence Bond Theory (inner vs outer orbital complexes) and Crystal Field Theory (CFT Delta_o, Delta_t, spectrochemical series)', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?lech1=5-5`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'c12-chem-6',
    subjectId: 'cbse-12-chemistry',
    subjectName: 'Chemistry',
    subjectCode: '043',
    class: '12',
    academicSession: '2026-27',
    title: 'Haloalkanes and Haloarenes',
    chapterNumber: 6,
    unitNumber: 6,
    unitName: 'Haloalkanes and Haloarenes',
    description: "Haloalkanes: Nomenclature, nature of C-X bond, physical and chemical properties, optical rotation mechanism of substitution reactions. Haloarenes: Nature of C-X bond, substitution reactions (Directive influence of halogen in monosubstituted compounds only). Uses and environmental effects of - dichloromethane, trichloromethane, tetrachloromethane, iodoform, freons, DDT.",
    defaultEstimatedHours: 7,
    examWeightage: 'critical',
    difficulty: 'hard',
    prerequisites: ['chem-organic'],
    inCbseSyllabus: true,
    topics: [
      { id: 'c12-c6-t1', name: 'SN1 (two step, carbocation, racemisation) vs SN2 (one step, inversion of configuration)', inCbseSyllabus: true },
      { id: 'c12-c6-t2', name: 'Haloarenes low reactivity toward nucleophilic substitution and electrophilic substitution directive influence', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?lech2=1-5`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'c12-chem-8',
    subjectId: 'cbse-12-chemistry',
    subjectName: 'Chemistry',
    subjectCode: '043',
    class: '12',
    academicSession: '2026-27',
    title: 'Aldehydes, Ketones and Carboxylic Acids',
    chapterNumber: 8,
    unitNumber: 8,
    unitName: 'Aldehydes, Ketones and Carboxylic Acids',
    description: "Aldehydes and Ketones: Nomenclature, nature of carbonyl group, methods of preparation, physical and chemical properties, mechanism of nucleophilic addition, reactivity of alpha hydrogen in aldehydes, uses. Carboxylic Acids: Nomenclature, acidic nature, methods of preparation, physical and chemical properties; uses.",
    defaultEstimatedHours: 9,
    examWeightage: 'critical',
    difficulty: 'hard',
    prerequisites: ['chem-organic'],
    inCbseSyllabus: true,
    topics: [
      { id: 'c12-c8-t1', name: 'Nucleophilic addition reactions with HCN, NaHSO3, Grignard reagents, and NH2-Z derivatives', inCbseSyllabus: true },
      { id: 'c12-c8-t2', name: "Name reactions: Rosenmund reduction, Stephen reaction, Etard reaction, Aldol condensation, Cannizzaro reaction, Clemmensen & Wolff-Kishner", inCbseSyllabus: true },
      { id: 'c12-c8-t3', name: 'Tollens test, Fehling test, Iodoform test, and Carboxylic acid acidity (effect of substituents)', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?lech2=3-5`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },

  // -------------------------------------------------------------------------
  // MATHEMATICS (041)
  // -------------------------------------------------------------------------
  {
    id: 'c12-math-1',
    subjectId: 'cbse-12-mathematics',
    subjectName: 'Mathematics',
    subjectCode: '041',
    class: '12',
    academicSession: '2026-27',
    title: 'Relations and Functions',
    chapterNumber: 1,
    unitNumber: 1,
    unitName: 'Relations and Functions',
    description: "Types of relations: reflexive, symmetric, transitive and equivalence relations. One to one and onto functions.",
    defaultEstimatedHours: 6,
    examWeightage: 'high',
    difficulty: 'medium',
    prerequisites: ['math-relations'],
    inCbseSyllabus: true,
    topics: [
      { id: 'c12-m1-t1', name: 'Equivalence relations proof (reflexive, symmetric, transitive)', inCbseSyllabus: true },
      { id: 'c12-m1-t2', name: 'Injective (one-to-one) and Surjective (onto) function bijection proofs', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?lemh1=1-6`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'c12-math-3',
    subjectId: 'cbse-12-mathematics',
    subjectName: 'Mathematics',
    subjectCode: '041',
    class: '12',
    academicSession: '2026-27',
    title: 'Matrices',
    chapterNumber: 3,
    unitNumber: 2,
    unitName: 'Algebra',
    description: "Concept, notation, order, equality, types of matrices, zero and identity matrix, transpose of a matrix, symmetric and skew symmetric matrices. Operation on matrices: Addition and multiplication and multiplication with a scalar. Simple properties of addition, multiplication and scalar multiplication. Non- commutativity of multiplication of matrices and existence of non-zero matrices whose product is the zero matrix. Invertible matrices and proof of the uniqueness of inverse.",
    defaultEstimatedHours: 6,
    examWeightage: 'critical',
    difficulty: 'easy',
    prerequisites: [],
    inCbseSyllabus: true,
    topics: [
      { id: 'c12-m3-t1', name: 'Matrix multiplication properties and non-commutativity', inCbseSyllabus: true },
      { id: 'c12-m3-t2', name: 'Symmetric and skew-symmetric matrices representation A = 1/2(A + A’) + 1/2(A - A’)', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?lemh1=3-6`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'c12-math-4',
    subjectId: 'cbse-12-mathematics',
    subjectName: 'Mathematics',
    subjectCode: '041',
    class: '12',
    academicSession: '2026-27',
    title: 'Determinants',
    chapterNumber: 4,
    unitNumber: 2,
    unitName: 'Algebra',
    description: "Determinant of a square matrix (up to 3 x 3 matrices), minors, co-factors and applications of determinants in finding the area of a triangle. Adjoint and inverse of a square matrix. Consistency, inconsistency and number of solutions of system of linear equations by examples, solving system of linear equations in two or three variables (having unique solution) using inverse of a matrix.",
    defaultEstimatedHours: 7,
    examWeightage: 'critical',
    difficulty: 'medium',
    prerequisites: ['c12-math-3'],
    inCbseSyllabus: true,
    topics: [
      { id: 'c12-m4-t1', name: 'Minors and cofactors, Adjoint adj(A) and inverse A^-1 = (1/|A|) adj(A)', inCbseSyllabus: true },
      { id: 'c12-m4-t2', name: 'Matrix method for solving system of linear equations X = A^-1 B', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?lemh1=4-6`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'c12-math-5',
    subjectId: 'cbse-12-mathematics',
    subjectName: 'Mathematics',
    subjectCode: '041',
    class: '12',
    academicSession: '2026-27',
    title: 'Continuity and Differentiability',
    chapterNumber: 5,
    unitNumber: 3,
    unitName: 'Calculus',
    description: "Continuity and differentiability, chain rule, derivative of inverse trigonometric functions, derivative of implicit functions. Concept of exponential and logarithmic functions. Derivatives of logarithmic and exponential functions. Logarithmic differentiation, derivative of functions expressed in parametric forms. Second order derivatives.",
    defaultEstimatedHours: 8,
    examWeightage: 'critical',
    difficulty: 'hard',
    prerequisites: ['math-limits'],
    inCbseSyllabus: true,
    topics: [
      { id: 'c12-m5-t1', name: 'Continuity proof at a point: lim_(x->c) f(x) = f(c)', inCbseSyllabus: true },
      { id: 'c12-m5-t2', name: 'Chain rule, derivatives of implicit functions and inverse trigonometric functions', inCbseSyllabus: true },
      { id: 'c12-m5-t3', name: 'Logarithmic differentiation y = f(x)^g(x) and parametric differentiation dy/dx = (dy/dt) / (dx/dt)', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?lemh1=5-6`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'c12-math-6',
    subjectId: 'cbse-12-mathematics',
    subjectName: 'Mathematics',
    subjectCode: '041',
    class: '12',
    academicSession: '2026-27',
    title: 'Application of Derivatives',
    chapterNumber: 6,
    unitNumber: 3,
    unitName: 'Calculus',
    description: "Applications of derivatives: rate of change of quantities, increasing/decreasing functions, maxima and minima (first derivative test motivated geometrically and second derivative test given as a provable tool). Simple problems (that illustrate basic principles and understanding of the subject as well as real-life situations).",
    defaultEstimatedHours: 8,
    examWeightage: 'critical',
    difficulty: 'hard',
    prerequisites: ['c12-math-5'],
    inCbseSyllabus: true,
    topics: [
      { id: 'c12-m6-t1', name: 'Rate of change dy/dt = (dy/dx)(dx/dt)', inCbseSyllabus: true },
      { id: 'c12-m6-t2', name: 'Strictly increasing and decreasing intervals using f’(x) >= 0 or <= 0', inCbseSyllabus: true },
      { id: 'c12-m6-t3', name: 'Maxima and Minima: First derivative test, Second derivative test f’’(x), and optimization word problems', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?lemh1=6-6`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'c12-math-7',
    subjectId: 'cbse-12-mathematics',
    subjectName: 'Mathematics',
    subjectCode: '041',
    class: '12',
    academicSession: '2026-27',
    title: 'Integrals',
    chapterNumber: 7,
    unitNumber: 3,
    unitName: 'Calculus',
    description: "Integration as inverse process of differentiation. Integration of a variety of functions by substitution, by partial fractions and by parts, Evaluation of simple integrals of the specified standard types. Fundamental Theorem of Calculus. Basic properties of definite integrals and evaluation of definite integrals.",
    defaultEstimatedHours: 11,
    examWeightage: 'critical',
    difficulty: 'hard',
    prerequisites: ['c12-math-5'],
    inCbseSyllabus: true,
    topics: [
      { id: 'c12-m7-t1', name: 'Integration by substitution, Integration by parts Integral u v dx = u Integral v - Integral (u’ Integral v)', inCbseSyllabus: true },
      { id: 'c12-m7-t2', name: 'Integration using partial fractions and standard forms 1/(x^2 + a^2), 1/sqrt(a^2 - x^2)', inCbseSyllabus: true },
      { id: 'c12-m7-t3', name: 'Properties of definite integrals Integral_0^a f(x) dx = Integral_0^a f(a-x) dx and odd/even tests', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?lemh2=1-7`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'c12-math-10',
    subjectId: 'cbse-12-mathematics',
    subjectName: 'Mathematics',
    subjectCode: '041',
    class: '12',
    academicSession: '2026-27',
    title: 'Vector Algebra',
    chapterNumber: 10,
    unitNumber: 4,
    unitName: 'Vectors and Three-Dimensional Geometry',
    description: "Vectors and scalars, magnitude and direction of a vector. Direction cosines and direction ratios of a vector. Types of vectors, position vector of a point, negative of a vector, components of a vector, addition of vectors, multiplication of a vector by a scalar, position vector of a point dividing a line segment in a given ratio. Definition, properties and application of scalar (dot) product of vectors, vector (cross) product of vectors.",
    defaultEstimatedHours: 7,
    examWeightage: 'high',
    difficulty: 'medium',
    prerequisites: ['phy-motion-plane'],
    inCbseSyllabus: true,
    topics: [
      { id: 'c12-m10-t1', name: 'Direction cosines (l, m, n) where l^2 + m^2 + n^2 = 1 and direction ratios', inCbseSyllabus: true },
      { id: 'c12-m10-t2', name: 'Scalar (dot) product a.b = |a||b| cos theta and vector (cross) product a x b = |a||b| sin theta n_hat', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?lemh2=4-7`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'c12-math-11',
    subjectId: 'cbse-12-mathematics',
    subjectName: 'Mathematics',
    subjectCode: '041',
    class: '12',
    academicSession: '2026-27',
    title: 'Three-dimensional Geometry',
    chapterNumber: 11,
    unitNumber: 4,
    unitName: 'Vectors and Three-Dimensional Geometry',
    description: "Direction cosines and direction ratios of a line joining two points. Cartesian equation and vector equation of a line, skew lines, shortest distance between two lines. Angle between two lines.",
    defaultEstimatedHours: 7,
    examWeightage: 'critical',
    difficulty: 'hard',
    prerequisites: ['c12-math-10'],
    inCbseSyllabus: true,
    topics: [
      { id: 'c12-m11-t1', name: 'Equation of line in vector r = a + lambda b and Cartesian (x-x1)/a = (y-y1)/b = (z-z1)/c', inCbseSyllabus: true },
      { id: 'c12-m11-t2', name: 'Shortest distance between two skew lines d = |(b1 x b2) . (a2 - a1)| / |b1 x b2|', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?lemh2=5-7`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'c12-math-13',
    subjectId: 'cbse-12-mathematics',
    subjectName: 'Mathematics',
    subjectCode: '041',
    class: '12',
    academicSession: '2026-27',
    title: 'Probability',
    chapterNumber: 13,
    unitNumber: 6,
    unitName: 'Probability',
    description: "Conditional probability, multiplication theorem on probability, independent events, total probability, Bayes theorem, Random variable and its probability distribution, mean of random variable.",
    defaultEstimatedHours: 7,
    examWeightage: 'critical',
    difficulty: 'hard',
    prerequisites: ['math-probability'],
    inCbseSyllabus: true,
    topics: [
      { id: 'c12-m13-t1', name: 'Conditional probability P(A|B) = P(A intersection B) / P(B)', inCbseSyllabus: true },
      { id: 'c12-m13-t2', name: "Independent events and Bayes' Theorem P(E_i|A) formula", inCbseSyllabus: true },
      { id: 'c12-m13-t3', name: 'Random variable and probability distribution table, Mean E(X) = Sum(x_i p_i)', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?lemh2=7-7`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
];
