import {
  type CurriculumSubject,
  type CurriculumChapter,
  type GradeLevel,
  type StreamId,
} from './types';

export const CBSE_ACADEMIC_SESSION = '2026-27';
export const OFFICIAL_CBSE_SYLLABUS_PORTAL = 'https://cbseacademic.nic.in/curriculum_2027.html';
export const OFFICIAL_NCERT_PORTAL = 'https://ncert.nic.in/textbook.php';
export const OFFICIAL_CBSE_SKILL_PORTAL = 'https://cbseacademic.nic.in/skill-education.html';

// ============================================================================
// SUBJECT CATALOGUE
// ============================================================================

export const CBSE_SUBJECTS_CATALOGUE: CurriculumSubject[] = [
  // --------------------------------------------------------------------------
  // CLASS 9 SUBJECTS
  // --------------------------------------------------------------------------
  {
    id: 'cbse-9-math',
    code: '041',
    name: 'Mathematics',
    class: '9',
    academicSession: '2026-27',
    category: 'compulsory',
    streamRelevance: ['none'],
    description: 'Number systems, Algebra, Coordinate Geometry, Geometry, Mensuration, Statistics.',
    ncertBookTitle: 'Mathematics: Textbook for Class IX',
    officialSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
    officialTextbookUrl: `${OFFICIAL_NCERT_PORTAL}?iemh1=0-12`,
    units: [
      { unitNumber: 1, title: 'Number Systems', marksWeightage: 10, chapterIds: ['c9-math-1'] },
      { unitNumber: 2, title: 'Algebra', marksWeightage: 20, chapterIds: ['c9-math-2', 'c9-math-4'] },
      { unitNumber: 3, title: 'Coordinate Geometry', marksWeightage: 4, chapterIds: ['c9-math-3'] },
      { unitNumber: 4, title: 'Geometry', marksWeightage: 27, chapterIds: ['c9-math-5', 'c9-math-6', 'c9-math-7', 'c9-math-8', 'c9-math-9'] },
      { unitNumber: 5, title: 'Mensuration', marksWeightage: 13, chapterIds: ['c9-math-10', 'c9-math-11'] },
      { unitNumber: 6, title: 'Statistics', marksWeightage: 6, chapterIds: ['c9-math-12'] },
    ],
    chapterIds: [
      'c9-math-1', 'c9-math-2', 'c9-math-3', 'c9-math-4', 'c9-math-5', 'c9-math-6',
      'c9-math-7', 'c9-math-8', 'c9-math-9', 'c9-math-10', 'c9-math-11', 'c9-math-12'
    ],
  },
  {
    id: 'cbse-9-science',
    code: '086',
    name: 'Science',
    class: '9',
    academicSession: '2026-27',
    category: 'compulsory',
    streamRelevance: ['none'],
    description: 'Food, Materials, The World of the Living, Moving Things, People and Ideas, Natural Phenomenon.',
    ncertBookTitle: 'Science: Textbook for Class IX',
    officialSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
    officialTextbookUrl: `${OFFICIAL_NCERT_PORTAL}?iesc1=0-12`,
    units: [
      { unitNumber: 1, title: 'Matter - Nature and Behaviour', marksWeightage: 25, chapterIds: ['c9-sci-1', 'c9-sci-2', 'c9-sci-3', 'c9-sci-4'] },
      { unitNumber: 2, title: 'Organization in the Living World', marksWeightage: 22, chapterIds: ['c9-sci-5', 'c9-sci-6'] },
      { unitNumber: 3, title: 'Motion, Force and Work', marksWeightage: 27, chapterIds: ['c9-sci-7', 'c9-sci-8', 'c9-sci-9', 'c9-sci-10', 'c9-sci-11'] },
      { unitNumber: 4, title: 'Food; Food Production', marksWeightage: 6, chapterIds: ['c9-sci-12'] },
    ],
    chapterIds: [
      'c9-sci-1', 'c9-sci-2', 'c9-sci-3', 'c9-sci-4', 'c9-sci-5', 'c9-sci-6',
      'c9-sci-7', 'c9-sci-8', 'c9-sci-9', 'c9-sci-10', 'c9-sci-11', 'c9-sci-12'
    ],
  },
  {
    id: 'cbse-9-sst',
    code: '087',
    name: 'Social Science',
    class: '9',
    academicSession: '2026-27',
    category: 'compulsory',
    streamRelevance: ['none'],
    description: 'India and Contemporary World I (History), Contemporary India I (Geography), Democratic Politics I (Civics), Economics.',
    ncertBookTitle: 'NCERT Social Science Textbooks for Class IX',
    officialSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
    officialTextbookUrl: OFFICIAL_NCERT_PORTAL,
    units: [
      { unitNumber: 1, title: 'India and the Contemporary World - I (History)', marksWeightage: 20, chapterIds: ['c9-sst-hist-1', 'c9-sst-hist-2', 'c9-sst-hist-3', 'c9-sst-hist-4', 'c9-sst-hist-5'] },
      { unitNumber: 2, title: 'Contemporary India - I (Geography)', marksWeightage: 20, chapterIds: ['c9-sst-geo-1', 'c9-sst-geo-2', 'c9-sst-geo-3', 'c9-sst-geo-4', 'c9-sst-geo-5'] },
      { unitNumber: 3, title: 'Democratic Politics - I (Civics)', marksWeightage: 20, chapterIds: ['c9-sst-civ-1', 'c9-sst-civ-2', 'c9-sst-civ-3', 'c9-sst-civ-4', 'c9-sst-civ-5'] },
      { unitNumber: 4, title: 'Economics', marksWeightage: 20, chapterIds: ['c9-sst-eco-1', 'c9-sst-eco-2', 'c9-sst-eco-3', 'c9-sst-eco-4'] },
    ],
    chapterIds: [
      'c9-sst-hist-1', 'c9-sst-hist-2', 'c9-sst-hist-3', 'c9-sst-hist-4', 'c9-sst-hist-5',
      'c9-sst-geo-1', 'c9-sst-geo-2', 'c9-sst-geo-3', 'c9-sst-geo-4', 'c9-sst-geo-5',
      'c9-sst-civ-1', 'c9-sst-civ-2', 'c9-sst-civ-3', 'c9-sst-civ-4', 'c9-sst-civ-5',
      'c9-sst-eco-1', 'c9-sst-eco-2', 'c9-sst-eco-3', 'c9-sst-eco-4'
    ],
  },
  {
    id: 'cbse-9-english',
    code: '184',
    name: 'English Language & Literature',
    class: '9',
    academicSession: '2026-27',
    category: 'language',
    streamRelevance: ['none'],
    description: 'Reading comprehension, creative writing skills, grammar, prose and poetry from Beehive and Moments (NCERT rationalised edition).',
    ncertBookTitle: 'Beehive & Moments (Class IX)',
    officialSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
    officialTextbookUrl: `${OFFICIAL_NCERT_PORTAL}?iebe1=0-11`,
    units: [
      { unitNumber: 1, title: 'Reading & Writing Skills', marksWeightage: 20, chapterIds: ['c9-eng-skills', 'c9-eng-writing'] },
      { unitNumber: 2, title: 'Beehive (Prose & Poetry)', marksWeightage: 40, chapterIds: ['c9-eng-bh-1', 'c9-eng-bh-2', 'c9-eng-bh-3', 'c9-eng-bh-4', 'c9-eng-bh-5', 'c9-eng-bh-6', 'c9-eng-bh-7', 'c9-eng-bh-8', 'c9-eng-bh-9'] },
      { unitNumber: 3, title: 'Moments (Supplementary Reader)', marksWeightage: 20, chapterIds: ['c9-eng-mom-1', 'c9-eng-mom-2', 'c9-eng-mom-3', 'c9-eng-mom-4', 'c9-eng-mom-5', 'c9-eng-mom-6', 'c9-eng-mom-7', 'c9-eng-mom-8'] },
    ],
    chapterIds: [
      'c9-eng-skills', 'c9-eng-writing',
      'c9-eng-bh-1', 'c9-eng-bh-2', 'c9-eng-bh-3', 'c9-eng-bh-4', 'c9-eng-bh-5', 'c9-eng-bh-6', 'c9-eng-bh-7', 'c9-eng-bh-8', 'c9-eng-bh-9',
      'c9-eng-mom-1', 'c9-eng-mom-2', 'c9-eng-mom-3', 'c9-eng-mom-4', 'c9-eng-mom-5', 'c9-eng-mom-6', 'c9-eng-mom-7', 'c9-eng-mom-8'
    ],
  },
  {
    id: 'cbse-9-hindi-a',
    code: '002',
    name: 'Hindi Course A',
    class: '9',
    academicSession: '2026-27',
    category: 'language',
    streamRelevance: ['none'],
    description: 'Apthit Gadyansh/Kavyansh, Vyakaran, Kshitij Bhag 1, Kritika Bhag 1 (NCERT rationalised edition).',
    ncertBookTitle: 'Kshitij Bhag 1 & Kritika Bhag 1',
    officialSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
    officialTextbookUrl: OFFICIAL_NCERT_PORTAL,
    units: [
      { unitNumber: 1, title: 'Apthit Bodh, Vyakaran evam Rachana', marksWeightage: 30, chapterIds: ['c9-hin-vyakaran', 'c9-hin-rachana'] },
      { unitNumber: 2, title: 'Kshitij Bhag 1 (Gadya evam Kavya)', marksWeightage: 36, chapterIds: ['c9-hin-ksh-1', 'c9-hin-ksh-2', 'c9-hin-ksh-3', 'c9-hin-ksh-4', 'c9-hin-ksh-5', 'c9-hin-ksh-6', 'c9-hin-ksh-7', 'c9-hin-ksh-8'] },
      { unitNumber: 3, title: 'Kritika Bhag 1', marksWeightage: 14, chapterIds: ['c9-hin-krt-1', 'c9-hin-krt-2', 'c9-hin-krt-3'] },
    ],
    chapterIds: [
      'c9-hin-vyakaran', 'c9-hin-rachana',
      'c9-hin-ksh-1', 'c9-hin-ksh-2', 'c9-hin-ksh-3', 'c9-hin-ksh-4', 'c9-hin-ksh-5', 'c9-hin-ksh-6', 'c9-hin-ksh-7', 'c9-hin-ksh-8',
      'c9-hin-krt-1', 'c9-hin-krt-2', 'c9-hin-krt-3'
    ],
  },
  {
    id: 'cbse-9-bengali',
    code: '005',
    name: 'Bengali (বাংলা)',
    class: '9',
    academicSession: '2026-27',
    category: 'language',
    streamRelevance: ['none'],
    description: 'CBSE Class 9 Bengali: Reading Comprehension (অপঠিত গদ্যাংশ), Grammar (সমাস, বাক্য পরিবর্তন, সন্ধি, অশুদ্ধি সংশোধন), Writing (প্রতিবেদন, বিজ্ঞপ্তি, অনুচ্ছেদ), Sahitya Sanchayan, and Aam Aantir Bhenpu.',
    ncertBookTitle: 'Sahitya Sanchayan & Aam Aantir Bhenpu (Class IX)',
    officialSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
    officialTextbookUrl: OFFICIAL_NCERT_PORTAL,
    units: [
      { unitNumber: 1, title: 'বোধ পরীক্ষণ ও ব্যাকরণ (Reading & Grammar)', marksWeightage: 30, chapterIds: ['c9-ben-grammar'] },
      { unitNumber: 2, title: 'নির্মিতি ও রচনা (Writing Skills)', marksWeightage: 20, chapterIds: ['c9-ben-writing'] },
      { unitNumber: 3, title: 'সাহিত্য সঞ্চয়ন - গদ্য ও পদ্য (Literature: Prose & Poetry)', marksWeightage: 35, chapterIds: ['c9-ben-prose-1', 'c9-ben-prose-2', 'c9-ben-prose-3', 'c9-ben-prose-4', 'c9-ben-poem-1', 'c9-ben-poem-2', 'c9-ben-poem-3', 'c9-ben-poem-4'] },
      { unitNumber: 4, title: 'সহায়ক পাঠ - আম আঁটির ভেঁপু (Supplementary Reader)', marksWeightage: 15, chapterIds: ['c9-ben-supp-1', 'c9-ben-supp-2'] },
    ],
    chapterIds: [
      'c9-ben-grammar', 'c9-ben-writing',
      'c9-ben-prose-1', 'c9-ben-prose-2', 'c9-ben-prose-3', 'c9-ben-prose-4',
      'c9-ben-poem-1', 'c9-ben-poem-2', 'c9-ben-poem-3', 'c9-ben-poem-4',
      'c9-ben-supp-1', 'c9-ben-supp-2'
    ],
  },
  {
    id: 'cbse-9-kaushal-vikas',
    code: '444',
    name: 'Vocational Education (Kaushal Vikas)',
    class: '9',
    academicSession: '2026-27',
    category: 'skill',
    streamRelevance: ['none'],
    description: 'NCERT & CBSE new mandatory vocational curriculum under NEP 2020 & NCF-SE 2023 with 27 vocations across 3 units: Work with Life Forms, Work with Machines and Materials, and Work in Human Services.',
    ncertBookTitle: 'Kaushal Vikas: Textbook for Vocational Education Class IX (NCERT)',
    officialSyllabusUrl: OFFICIAL_CBSE_SKILL_PORTAL,
    officialTextbookUrl: OFFICIAL_CBSE_SKILL_PORTAL,
    units: [
      { unitNumber: 1, title: 'Unit I: Work with Life Forms (जीव रूपों के साथ कार्य)', marksWeightage: 15, chapterIds: ['c9-kv-1', 'c9-kv-2', 'c9-kv-3', 'c9-kv-4'] },
      { unitNumber: 2, title: 'Unit II: Work with Machines and Materials (मशीनों और सामग्रियों के साथ कार्य)', marksWeightage: 15, chapterIds: ['c9-kv-5', 'c9-kv-6', 'c9-kv-7', 'c9-kv-8'] },
      { unitNumber: 3, title: 'Unit III: Work in Human Services (मानव सेवाओं में कार्य)', marksWeightage: 20, chapterIds: ['c9-kv-9', 'c9-kv-10', 'c9-kv-11', 'c9-kv-12'] },
    ],
    chapterIds: [
      'c9-kv-1', 'c9-kv-2', 'c9-kv-3', 'c9-kv-4',
      'c9-kv-5', 'c9-kv-6', 'c9-kv-7', 'c9-kv-8',
      'c9-kv-9', 'c9-kv-10', 'c9-kv-11', 'c9-kv-12'
    ],
  },
  {
    id: 'cbse-9-ai',
    code: '417',
    name: 'Artificial Intelligence',
    class: '9',
    academicSession: '2026-27',
    category: 'skill',
    streamRelevance: ['none'],
    description: 'Employability Skills, Introduction to AI, AI Project Cycle, Neural Networks, Python Programming, Computer Vision & NLP Basics.',
    ncertBookTitle: 'CBSE Skill Education: AI Class IX',
    officialSyllabusUrl: OFFICIAL_CBSE_SKILL_PORTAL,
    officialTextbookUrl: OFFICIAL_CBSE_SKILL_PORTAL,
    units: [
      { unitNumber: 1, title: 'Employability Skills', marksWeightage: 10, chapterIds: ['c9-ai-emp'] },
      { unitNumber: 2, title: 'Subject Specific Skills (AI & Python)', marksWeightage: 40, chapterIds: ['c9-ai-1', 'c9-ai-2', 'c9-ai-3', 'c9-ai-4'] },
    ],
    chapterIds: ['c9-ai-emp', 'c9-ai-1', 'c9-ai-2', 'c9-ai-3', 'c9-ai-4'],
  },

  // --------------------------------------------------------------------------
  // CLASS 10 SUBJECTS
  // --------------------------------------------------------------------------
  {
    id: 'cbse-10-math',
    code: '041',
    name: 'Mathematics',
    class: '10',
    academicSession: '2026-27',
    category: 'compulsory',
    streamRelevance: ['none'],
    description: 'Number Systems, Algebra, Coordinate Geometry, Geometry, Trigonometry, Mensuration, Statistics and Probability.',
    ncertBookTitle: 'Mathematics: Textbook for Class X',
    officialSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
    officialTextbookUrl: `${OFFICIAL_NCERT_PORTAL}?jemh1=0-14`,
    units: [
      { unitNumber: 1, title: 'Number Systems', marksWeightage: 6, chapterIds: ['c10-math-1'] },
      { unitNumber: 2, title: 'Algebra', marksWeightage: 20, chapterIds: ['c10-math-2', 'c10-math-3', 'c10-math-4', 'c10-math-5'] },
      { unitNumber: 3, title: 'Coordinate Geometry', marksWeightage: 6, chapterIds: ['c10-math-7'] },
      { unitNumber: 4, title: 'Geometry', marksWeightage: 15, chapterIds: ['c10-math-6', 'c10-math-10'] },
      { unitNumber: 5, title: 'Trigonometry', marksWeightage: 12, chapterIds: ['c10-math-8', 'c10-math-9'] },
      { unitNumber: 6, title: 'Mensuration', marksWeightage: 10, chapterIds: ['c10-math-11', 'c10-math-12'] },
      { unitNumber: 7, title: 'Statistics & Probability', marksWeightage: 11, chapterIds: ['c10-math-13', 'c10-math-14'] },
    ],
    chapterIds: [
      'c10-math-1', 'c10-math-2', 'c10-math-3', 'c10-math-4', 'c10-math-5', 'c10-math-6',
      'c10-math-7', 'c10-math-8', 'c10-math-9', 'c10-math-10', 'c10-math-11', 'c10-math-12',
      'c10-math-13', 'c10-math-14'
    ],
  },
  {
    id: 'cbse-10-science',
    code: '086',
    name: 'Science',
    class: '10',
    academicSession: '2026-27',
    category: 'compulsory',
    streamRelevance: ['none'],
    description: 'Chemical Substances, World of Living, Natural Phenomena, Effects of Current, Natural Resources.',
    ncertBookTitle: 'Science: Textbook for Class X',
    officialSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
    officialTextbookUrl: `${OFFICIAL_NCERT_PORTAL}?jesc1=0-13`,
    units: [
      { unitNumber: 1, title: 'Chemical Substances - Nature and Behaviour', marksWeightage: 25, chapterIds: ['c10-sci-1', 'c10-sci-2', 'c10-sci-3', 'c10-sci-4'] },
      { unitNumber: 2, title: 'World of Living (Biology)', marksWeightage: 25, chapterIds: ['c10-sci-5', 'c10-sci-6', 'c10-sci-7', 'c10-sci-8'] },
      { unitNumber: 3, title: 'Natural Phenomena (Light & Human Eye)', marksWeightage: 12, chapterIds: ['c10-sci-9', 'c10-sci-10'] },
      { unitNumber: 4, title: 'Effects of Current (Electricity & Magnetism)', marksWeightage: 13, chapterIds: ['c10-sci-11', 'c10-sci-12'] },
      { unitNumber: 5, title: 'Natural Resources', marksWeightage: 5, chapterIds: ['c10-sci-13'] },
    ],
    chapterIds: [
      'c10-sci-1', 'c10-sci-2', 'c10-sci-3', 'c10-sci-4', 'c10-sci-5', 'c10-sci-6',
      'c10-sci-7', 'c10-sci-8', 'c10-sci-9', 'c10-sci-10', 'c10-sci-11', 'c10-sci-12', 'c10-sci-13'
    ],
  },
  {
    id: 'cbse-10-sst',
    code: '087',
    name: 'Social Science',
    class: '10',
    academicSession: '2026-27',
    category: 'compulsory',
    streamRelevance: ['none'],
    description: 'History (Rise of Nationalism), Geography (Contemporary India), Civics (Democratic Politics), Economics (Understanding Economic Development).',
    ncertBookTitle: 'NCERT Social Science Textbooks for Class X',
    officialSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
    officialTextbookUrl: OFFICIAL_NCERT_PORTAL,
    units: [
      { unitNumber: 1, title: 'India and the Contemporary World - II (History)', marksWeightage: 20, chapterIds: ['c10-sst-hist-1', 'c10-sst-hist-2', 'c10-sst-hist-3', 'c10-sst-hist-4', 'c10-sst-hist-5'] },
      { unitNumber: 2, title: 'Contemporary India - II (Geography)', marksWeightage: 20, chapterIds: ['c10-sst-geo-1', 'c10-sst-geo-2', 'c10-sst-geo-3', 'c10-sst-geo-4', 'c10-sst-geo-5', 'c10-sst-geo-6', 'c10-sst-geo-7'] },
      { unitNumber: 3, title: 'Democratic Politics - II (Civics)', marksWeightage: 20, chapterIds: ['c10-sst-civ-1', 'c10-sst-civ-2', 'c10-sst-civ-3', 'c10-sst-civ-4', 'c10-sst-civ-5'] },
      { unitNumber: 4, title: 'Understanding Economic Development', marksWeightage: 20, chapterIds: ['c10-sst-eco-1', 'c10-sst-eco-2', 'c10-sst-eco-3', 'c10-sst-eco-4'] },
    ],
    chapterIds: [
      'c10-sst-hist-1', 'c10-sst-hist-2', 'c10-sst-hist-3', 'c10-sst-hist-4', 'c10-sst-hist-5',
      'c10-sst-geo-1', 'c10-sst-geo-2', 'c10-sst-geo-3', 'c10-sst-geo-4', 'c10-sst-geo-5', 'c10-sst-geo-6', 'c10-sst-geo-7',
      'c10-sst-civ-1', 'c10-sst-civ-2', 'c10-sst-civ-3', 'c10-sst-civ-4', 'c10-sst-civ-5',
      'c10-sst-eco-1', 'c10-sst-eco-2', 'c10-sst-eco-3', 'c10-sst-eco-4'
    ],
  },
  {
    id: 'cbse-10-english',
    code: '184',
    name: 'English Language & Literature',
    class: '10',
    academicSession: '2026-27',
    category: 'language',
    streamRelevance: ['none'],
    description: 'Reading, writing & grammar skills, prose & poems from First Flight, stories from Footprints Without Feet.',
    ncertBookTitle: 'First Flight & Footprints without Feet (Class X)',
    officialSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
    officialTextbookUrl: `${OFFICIAL_NCERT_PORTAL}?jeff1=0-11`,
    units: [
      { unitNumber: 1, title: 'Reading & Grammar Skills', marksWeightage: 30, chapterIds: ['c10-eng-skills'] },
      { unitNumber: 2, title: 'First Flight (Prose & Poems)', marksWeightage: 30, chapterIds: ['c10-eng-ff-1', 'c10-eng-ff-2', 'c10-eng-ff-3', 'c10-eng-ff-4', 'c10-eng-ff-5', 'c10-eng-ff-6'] },
      { unitNumber: 3, title: 'Footprints without Feet', marksWeightage: 20, chapterIds: ['c10-eng-fp-1', 'c10-eng-fp-2', 'c10-eng-fp-3', 'c10-eng-fp-4'] },
    ],
    chapterIds: ['c10-eng-skills', 'c10-eng-ff-1', 'c10-eng-ff-2', 'c10-eng-ff-3', 'c10-eng-ff-4', 'c10-eng-ff-5', 'c10-eng-ff-6', 'c10-eng-fp-1', 'c10-eng-fp-2', 'c10-eng-fp-3', 'c10-eng-fp-4'],
  },
  {
    id: 'cbse-10-hindi-a',
    code: '002',
    name: 'Hindi Course A',
    class: '10',
    academicSession: '2026-27',
    category: 'language',
    streamRelevance: ['none'],
    description: 'Apthit Gadyansh, Vyakaran (Vakya bhed, Vachya, Pad-parichay, Alankar), Kshitij Bhag 2, Kritika Bhag 2.',
    ncertBookTitle: 'Kshitij Bhag 2 & Kritika Bhag 2',
    officialSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
    officialTextbookUrl: OFFICIAL_NCERT_PORTAL,
    units: [
      { unitNumber: 1, title: 'Apthit Bodh & Vyakaran', marksWeightage: 30, chapterIds: ['c10-hin-vyakaran'] },
      { unitNumber: 2, title: 'Kshitij Bhag 2', marksWeightage: 36, chapterIds: ['c10-hin-ksh-1', 'c10-hin-ksh-2', 'c10-hin-ksh-3', 'c10-hin-ksh-4'] },
      { unitNumber: 3, title: 'Kritika Bhag 2', marksWeightage: 14, chapterIds: ['c10-hin-krt-1', 'c10-hin-krt-2'] },
    ],
    chapterIds: ['c10-hin-vyakaran', 'c10-hin-ksh-1', 'c10-hin-ksh-2', 'c10-hin-ksh-3', 'c10-hin-ksh-4', 'c10-hin-krt-1', 'c10-hin-krt-2'],
  },
  {
    id: 'cbse-10-ai',
    code: '417',
    name: 'Artificial Intelligence',
    class: '10',
    academicSession: '2026-27',
    category: 'skill',
    streamRelevance: ['none'],
    description: 'Employability Skills, AI Project Cycle, Advance Python, Data Science, Computer Vision, Natural Language Processing, Evaluation.',
    ncertBookTitle: 'CBSE Skill Education: AI Class X',
    officialSyllabusUrl: OFFICIAL_CBSE_SKILL_PORTAL,
    officialTextbookUrl: OFFICIAL_CBSE_SKILL_PORTAL,
    units: [
      { unitNumber: 1, title: 'Employability Skills', marksWeightage: 10, chapterIds: ['c10-ai-1'] },
      { unitNumber: 2, title: 'Subject Specific Skills', marksWeightage: 40, chapterIds: ['c10-ai-2', 'c10-ai-3', 'c10-ai-4', 'c10-ai-5', 'c10-ai-6', 'c10-ai-7'] },
    ],
    chapterIds: ['c10-ai-1', 'c10-ai-2', 'c10-ai-3', 'c10-ai-4', 'c10-ai-5', 'c10-ai-6', 'c10-ai-7'],
  },
  {
    id: 'cbse-10-bengali',
    code: '005',
    name: 'Bengali (বাংলা)',
    class: '10',
    academicSession: '2026-27',
    category: 'language',
    streamRelevance: ['none'],
    description: 'সাহিত্য সঞ্চয়ন (গল্প ও কবিতা), সহায়ক পাঠ (কোনি) ও ব্যাকরণ নির্মিতি।',
    ncertBookTitle: 'সাহিত্য সঞ্চয়ন ও সহায়ক পাঠ (দশম শ্রেণি)',
    officialSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
    officialTextbookUrl: OFFICIAL_NCERT_PORTAL,
    units: [
      { unitNumber: 1, title: 'সাহিত্য সঞ্চয়ন: গদ্য ও পদ্য', marksWeightage: 45, chapterIds: ['c10-ben-1', 'c10-ben-2', 'c10-ben-3', 'c10-ben-4'] },
      { unitNumber: 2, title: 'সহায়ক পাঠ ও ব্যাকরণ', marksWeightage: 35, chapterIds: ['c10-ben-5'] },
    ],
    chapterIds: ['c10-ben-1', 'c10-ben-2', 'c10-ben-3', 'c10-ben-4', 'c10-ben-5'],
  },

  // --------------------------------------------------------------------------
  // CLASS 11 SUBJECTS (SCIENCE, COMMERCE, HUMANITIES)
  // --------------------------------------------------------------------------
  {
    id: 'cbse-11-physics',
    code: '042',
    name: 'Physics',
    class: '11',
    academicSession: '2026-27',
    category: 'elective',
    streamRelevance: ['pcm', 'pcb', 'pcmb', 'science_cs'],
    description: 'Mechanics, Properties of Bulk Matter, Thermodynamics, Kinetic Theory, Oscillations and Waves.',
    ncertBookTitle: 'Physics Part I & II (Class XI)',
    officialSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
    officialTextbookUrl: `${OFFICIAL_NCERT_PORTAL}?keph1=0-8`,
    units: [
      { unitNumber: 1, title: 'Physical World and Measurement', marksWeightage: 3, chapterIds: ['phy-units'] },
      { unitNumber: 2, title: 'Kinematics', marksWeightage: 10, chapterIds: ['phy-vectors', 'phy-motion-plane'] },
      { unitNumber: 3, title: 'Laws of Motion', marksWeightage: 10, chapterIds: ['phy-laws'] },
      { unitNumber: 4, title: 'Work, Energy and Power', marksWeightage: 8, chapterIds: ['phy-work'] },
      { unitNumber: 5, title: 'Motion of System of Particles & Rigid Body', marksWeightage: 7, chapterIds: ['phy-system', 'phy-rotation'] },
      { unitNumber: 6, title: 'Gravitation', marksWeightage: 6, chapterIds: ['phy-gravity'] },
      { unitNumber: 7, title: 'Properties of Bulk Matter', marksWeightage: 10, chapterIds: ['phy-solids', 'phy-fluids', 'phy-thermal'] },
      { unitNumber: 8, title: 'Thermodynamics', marksWeightage: 6, chapterIds: ['phy-thermo'] },
      { unitNumber: 9, title: 'Kinetic Theory of Gases', marksWeightage: 4, chapterIds: ['phy-kinetic'] },
      { unitNumber: 10, title: 'Oscillations and Waves', marksWeightage: 6, chapterIds: ['phy-oscillations', 'phy-waves'] },
    ],
    chapterIds: [
      'phy-units', 'phy-vectors', 'phy-motion-plane', 'phy-laws', 'phy-work',
      'phy-system', 'phy-rotation', 'phy-gravity', 'phy-solids', 'phy-fluids',
      'phy-thermal', 'phy-thermo', 'phy-kinetic', 'phy-oscillations', 'phy-waves'
    ],
  },
  {
    id: 'cbse-11-chemistry',
    code: '043',
    name: 'Chemistry',
    class: '11',
    academicSession: '2026-27',
    category: 'elective',
    streamRelevance: ['pcm', 'pcb', 'pcmb', 'science_cs'],
    description: 'Basic Concepts, Atomic Structure, Periodic Classification, Chemical Bonding, Thermodynamics, Equilibrium, Redox, Organic Chemistry, Hydrocarbons.',
    ncertBookTitle: 'Chemistry Part I & II (Class XI)',
    officialSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
    officialTextbookUrl: `${OFFICIAL_NCERT_PORTAL}?kech1=0-6`,
    units: [
      { unitNumber: 1, title: 'Some Basic Concepts of Chemistry', marksWeightage: 7, chapterIds: ['chem-basic'] },
      { unitNumber: 2, title: 'Structure of Atom', marksWeightage: 9, chapterIds: ['chem-structure'] },
      { unitNumber: 3, title: 'Classification of Elements and Periodicity in Properties', marksWeightage: 6, chapterIds: ['chem-periodic'] },
      { unitNumber: 4, title: 'Chemical Bonding and Molecular Structure', marksWeightage: 7, chapterIds: ['chem-bonding'] },
      { unitNumber: 5, title: 'Chemical Thermodynamics', marksWeightage: 9, chapterIds: ['chem-thermo'] },
      { unitNumber: 6, title: 'Equilibrium', marksWeightage: 7, chapterIds: ['chem-equilibrium'] },
      { unitNumber: 7, title: 'Redox Reactions', marksWeightage: 4, chapterIds: ['chem-redox'] },
      { unitNumber: 8, title: 'Organic Chemistry: Some Basic Principles & Techniques', marksWeightage: 11, chapterIds: ['chem-organic'] },
      { unitNumber: 9, title: 'Hydrocarbons', marksWeightage: 10, chapterIds: ['chem-hydrocarbons'] },
    ],
    chapterIds: [
      'chem-basic', 'chem-structure', 'chem-periodic', 'chem-bonding',
      'chem-thermo', 'chem-equilibrium', 'chem-redox', 'chem-organic', 'chem-hydrocarbons'
    ],
  },
  {
    id: 'cbse-11-mathematics',
    code: '041',
    name: 'Mathematics',
    class: '11',
    academicSession: '2026-27',
    category: 'elective',
    streamRelevance: ['pcm', 'pcmb', 'science_cs', 'commerce_math', 'humanities_math'],
    description: 'Sets & Functions, Algebra, Coordinate Geometry, Calculus, Statistics & Probability.',
    ncertBookTitle: 'Mathematics: Textbook for Class XI',
    officialSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
    officialTextbookUrl: `${OFFICIAL_NCERT_PORTAL}?kemh1=0-14`,
    units: [
      { unitNumber: 1, title: 'Sets and Functions', marksWeightage: 23, chapterIds: ['math-sets', 'math-relations', 'math-trig'] },
      { unitNumber: 2, title: 'Algebra', marksWeightage: 25, chapterIds: ['math-complex', 'math-inequalities', 'math-permutations', 'math-binomial', 'math-sequences'] },
      { unitNumber: 3, title: 'Coordinate Geometry', marksWeightage: 12, chapterIds: ['math-straight', 'math-conic', 'math-3d'] },
      { unitNumber: 4, title: 'Calculus (Limits & Derivatives)', marksWeightage: 8, chapterIds: ['math-limits'] },
      { unitNumber: 5, title: 'Statistics and Probability', marksWeightage: 12, chapterIds: ['math-stats', 'math-probability'] },
    ],
    chapterIds: [
      'math-sets', 'math-relations', 'math-trig', 'math-complex', 'math-inequalities',
      'math-permutations', 'math-binomial', 'math-sequences', 'math-straight', 'math-conic',
      'math-3d', 'math-limits', 'math-stats', 'math-probability'
    ],
  },
  {
    id: 'cbse-11-biology',
    code: '044',
    name: 'Biology',
    class: '11',
    academicSession: '2026-27',
    category: 'elective',
    streamRelevance: ['pcb', 'pcmb'],
    description: 'Diversity in Living World, Structural Organisation in Animals and Plants, Cell Structure and Function, Plant Physiology, Human Physiology.',
    ncertBookTitle: 'Biology: Textbook for Class XI',
    officialSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
    officialTextbookUrl: `${OFFICIAL_NCERT_PORTAL}?kebo1=0-19`,
    units: [
      { unitNumber: 1, title: 'Diversity in the Living World', marksWeightage: 12, chapterIds: ['c11-bio-1', 'c11-bio-2', 'c11-bio-3', 'c11-bio-4'] },
      { unitNumber: 2, title: 'Structural Organisation in Animals and Plants', marksWeightage: 10, chapterIds: ['c11-bio-5', 'c11-bio-6', 'c11-bio-7'] },
      { unitNumber: 3, title: 'Cell: Structure and Function', marksWeightage: 15, chapterIds: ['c11-bio-8', 'c11-bio-9', 'c11-bio-10'] },
      { unitNumber: 4, title: 'Plant Physiology', marksWeightage: 12, chapterIds: ['c11-bio-11', 'c11-bio-12', 'c11-bio-13'] },
      { unitNumber: 5, title: 'Human Physiology', marksWeightage: 21, chapterIds: ['c11-bio-14', 'c11-bio-15', 'c11-bio-16', 'c11-bio-17', 'c11-bio-18', 'c11-bio-19'] },
    ],
    chapterIds: [
      'c11-bio-1', 'c11-bio-2', 'c11-bio-3', 'c11-bio-4', 'c11-bio-5', 'c11-bio-6',
      'c11-bio-7', 'c11-bio-8', 'c11-bio-9', 'c11-bio-10', 'c11-bio-11', 'c11-bio-12',
      'c11-bio-13', 'c11-bio-14', 'c11-bio-15', 'c11-bio-16', 'c11-bio-17', 'c11-bio-18', 'c11-bio-19'
    ],
  },
  {
    id: 'cbse-11-cs',
    code: '083',
    name: 'Computer Science',
    class: '11',
    academicSession: '2026-27',
    category: 'elective',
    streamRelevance: ['science_cs', 'pcm', 'commerce_math'],
    description: 'Computer Systems and Organisation, Computational Thinking and Programming using Python, Society, Law and Ethics.',
    ncertBookTitle: 'Computer Science with Python (Class XI)',
    officialSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
    officialTextbookUrl: `${OFFICIAL_NCERT_PORTAL}?kecs1=0-11`,
    units: [
      { unitNumber: 1, title: 'Computer Systems and Organisation', marksWeightage: 10, chapterIds: ['c11-cs-1'] },
      { unitNumber: 2, title: 'Computational Thinking and Programming - 1', marksWeightage: 45, chapterIds: ['c11-cs-2', 'c11-cs-3', 'c11-cs-4', 'c11-cs-5', 'c11-cs-6'] },
      { unitNumber: 3, title: 'Society, Law and Ethics', marksWeightage: 15, chapterIds: ['c11-cs-7'] },
    ],
    chapterIds: ['c11-cs-1', 'c11-cs-2', 'c11-cs-3', 'c11-cs-4', 'c11-cs-5', 'c11-cs-6', 'c11-cs-7'],
  },
  {
    id: 'cbse-11-english',
    code: '301',
    name: 'English Core',
    class: '11',
    academicSession: '2026-27',
    category: 'compulsory',
    streamRelevance: ['pcm', 'pcb', 'pcmb', 'science_cs', 'commerce_math', 'commerce_no_math', 'humanities', 'humanities_math'],
    description: 'Reading Comprehension, Creative Writing Skills & Grammar, Literature from Hornbill and Snapshots.',
    ncertBookTitle: 'Hornbill & Snapshots (Class XI)',
    officialSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
    officialTextbookUrl: `${OFFICIAL_NCERT_PORTAL}?kehb1=0-9`,
    units: [
      { unitNumber: 1, title: 'Reading Comprehension & Grammar Skills', marksWeightage: 36, chapterIds: ['c11-eng-skills'] },
      { unitNumber: 2, title: 'Hornbill (Prose & Poetry)', marksWeightage: 26, chapterIds: ['c11-eng-hb-1', 'c11-eng-hb-2', 'c11-eng-hb-3', 'c11-eng-hb-4', 'c11-eng-hb-5'] },
      { unitNumber: 3, title: 'Snapshots (Supplementary Reader)', marksWeightage: 18, chapterIds: ['c11-eng-snap-1', 'c11-eng-snap-2', 'c11-eng-snap-3'] },
    ],
    chapterIds: ['c11-eng-skills', 'c11-eng-hb-1', 'c11-eng-hb-2', 'c11-eng-hb-3', 'c11-eng-hb-4', 'c11-eng-hb-5', 'c11-eng-snap-1', 'c11-eng-snap-2', 'c11-eng-snap-3'],
  },
  {
    id: 'cbse-11-accountancy',
    code: '055',
    name: 'Accountancy',
    class: '11',
    academicSession: '2026-27',
    category: 'elective',
    streamRelevance: ['commerce_math', 'commerce_no_math'],
    description: 'Theoretical Framework, Accounting Process (Journal, Ledger, Trial Balance, BRS, Depreciation), Financial Statements of Sole Proprietorship.',
    ncertBookTitle: 'Financial Accounting Part I & II (Class XI)',
    officialSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
    officialTextbookUrl: `${OFFICIAL_NCERT_PORTAL}?keac1=0-8`,
    units: [
      { unitNumber: 1, title: 'Theoretical Framework', marksWeightage: 12, chapterIds: ['c11-acc-1', 'c11-acc-2'] },
      { unitNumber: 2, title: 'Accounting Process', marksWeightage: 44, chapterIds: ['c11-acc-3', 'c11-acc-4', 'c11-acc-5', 'c11-acc-6', 'c11-acc-7'] },
      { unitNumber: 3, title: 'Financial Statements of Sole Proprietorship', marksWeightage: 24, chapterIds: ['c11-acc-8', 'c11-acc-9'] },
    ],
    chapterIds: ['c11-acc-1', 'c11-acc-2', 'c11-acc-3', 'c11-acc-4', 'c11-acc-5', 'c11-acc-6', 'c11-acc-7', 'c11-acc-8', 'c11-acc-9'],
  },
  {
    id: 'cbse-11-bst',
    code: '054',
    name: 'Business Studies',
    class: '11',
    academicSession: '2026-27',
    category: 'elective',
    streamRelevance: ['commerce_math', 'commerce_no_math'],
    description: 'Foundations of Business, Forms of Business Organisations, Corporate Organisation, Finance and Trade.',
    ncertBookTitle: 'Business Studies: Textbook for Class XI',
    officialSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
    officialTextbookUrl: `${OFFICIAL_NCERT_PORTAL}?kest1=0-11`,
    units: [
      { unitNumber: 1, title: 'Foundations of Business', marksWeightage: 40, chapterIds: ['c11-bst-1', 'c11-bst-2', 'c11-bst-3', 'c11-bst-4', 'c11-bst-5', 'c11-bst-6'] },
      { unitNumber: 2, title: 'Finance and Trade', marksWeightage: 40, chapterIds: ['c11-bst-7', 'c11-bst-8', 'c11-bst-9', 'c11-bst-10'] },
    ],
    chapterIds: ['c11-bst-1', 'c11-bst-2', 'c11-bst-3', 'c11-bst-4', 'c11-bst-5', 'c11-bst-6', 'c11-bst-7', 'c11-bst-8', 'c11-bst-9', 'c11-bst-10'],
  },
  {
    id: 'cbse-11-economics',
    code: '030',
    name: 'Economics',
    class: '11',
    academicSession: '2026-27',
    category: 'elective',
    streamRelevance: ['commerce_math', 'commerce_no_math', 'humanities', 'humanities_math'],
    description: 'Part A: Statistics for Economics; Part B: Introductory Microeconomics.',
    ncertBookTitle: 'Statistics for Economics & Introductory Microeconomics',
    officialSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
    officialTextbookUrl: `${OFFICIAL_NCERT_PORTAL}?keec1=0-8`,
    units: [
      { unitNumber: 1, title: 'Statistics for Economics', marksWeightage: 40, chapterIds: ['c11-eco-stat-1', 'c11-eco-stat-2', 'c11-eco-stat-3'] },
      { unitNumber: 2, title: 'Introductory Microeconomics', marksWeightage: 40, chapterIds: ['c11-eco-micro-1', 'c11-eco-micro-2', 'c11-eco-micro-3', 'c11-eco-micro-4'] },
    ],
    chapterIds: ['c11-eco-stat-1', 'c11-eco-stat-2', 'c11-eco-stat-3', 'c11-eco-micro-1', 'c11-eco-micro-2', 'c11-eco-micro-3', 'c11-eco-micro-4'],
  },
  {
    id: 'cbse-11-history',
    code: '027',
    name: 'History',
    class: '11',
    academicSession: '2026-27',
    category: 'elective',
    streamRelevance: ['humanities', 'humanities_math'],
    description: 'Themes in World History: Early Societies, Empires, Changing Traditions, Towards Modernisation.',
    ncertBookTitle: 'Themes in World History (Class XI)',
    officialSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
    officialTextbookUrl: `${OFFICIAL_NCERT_PORTAL}?kehs1=0-7`,
    units: [
      { unitNumber: 1, title: 'Early Societies', marksWeightage: 10, chapterIds: ['c11-hist-1'] },
      { unitNumber: 2, title: 'Empires', marksWeightage: 26, chapterIds: ['c11-hist-2', 'c11-hist-3'] },
      { unitNumber: 3, title: 'Changing Traditions', marksWeightage: 24, chapterIds: ['c11-hist-4', 'c11-hist-5'] },
      { unitNumber: 4, title: 'Towards Modernisation', marksWeightage: 20, chapterIds: ['c11-hist-6', 'c11-hist-7'] },
    ],
    chapterIds: ['c11-hist-1', 'c11-hist-2', 'c11-hist-3', 'c11-hist-4', 'c11-hist-5', 'c11-hist-6', 'c11-hist-7'],
  },
  {
    id: 'cbse-11-polsci',
    code: '028',
    name: 'Political Science',
    class: '11',
    academicSession: '2026-27',
    category: 'elective',
    streamRelevance: ['humanities', 'humanities_math'],
    description: 'Part A: Indian Constitution at Work; Part B: Political Theory.',
    ncertBookTitle: 'Indian Constitution at Work & Political Theory (Class XI)',
    officialSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
    officialTextbookUrl: `${OFFICIAL_NCERT_PORTAL}?keps1=0-8`,
    units: [
      { unitNumber: 1, title: 'Indian Constitution at Work', marksWeightage: 40, chapterIds: ['c11-pol-1', 'c11-pol-2', 'c11-pol-3', 'c11-pol-4', 'c11-pol-5'] },
      { unitNumber: 2, title: 'Political Theory', marksWeightage: 40, chapterIds: ['c11-pol-6', 'c11-pol-7', 'c11-pol-8', 'c11-pol-9', 'c11-pol-10'] },
    ],
    chapterIds: ['c11-pol-1', 'c11-pol-2', 'c11-pol-3', 'c11-pol-4', 'c11-pol-5', 'c11-pol-6', 'c11-pol-7', 'c11-pol-8', 'c11-pol-9', 'c11-pol-10'],
  },
  {
    id: 'cbse-11-pe',
    code: '048',
    name: 'Physical Education',
    class: '11',
    academicSession: '2026-27',
    category: 'elective',
    streamRelevance: ['pcm', 'pcb', 'pcmb', 'science_cs', 'commerce_math', 'commerce_no_math', 'humanities', 'humanities_math'],
    description: 'Changing Trends, Olympic Value Education, Yoga, Physical Education for CWSN, Physical Fitness & Wellness, Test & Measurement, Anatomy & Physiology, Psychology & Sports.',
    ncertBookTitle: 'Physical Education: CBSE Class XI',
    officialSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
    officialTextbookUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
    units: [
      { unitNumber: 1, title: 'Physical Education and Sports Management', marksWeightage: 35, chapterIds: ['c11-pe-1', 'c11-pe-2', 'c11-pe-3', 'c11-pe-4', 'c11-pe-5'] },
      { unitNumber: 2, title: 'Physiology, Anatomy, Psychology & Training', marksWeightage: 35, chapterIds: ['c11-pe-6', 'c11-pe-7', 'c11-pe-8', 'c11-pe-9', 'c11-pe-10'] },
    ],
    chapterIds: ['c11-pe-1', 'c11-pe-2', 'c11-pe-3', 'c11-pe-4', 'c11-pe-5', 'c11-pe-6', 'c11-pe-7', 'c11-pe-8', 'c11-pe-9', 'c11-pe-10'],
  },

  // --------------------------------------------------------------------------
  // CLASS 12 SUBJECTS (SCIENCE, COMMERCE, HUMANITIES)
  // --------------------------------------------------------------------------
  {
    id: 'cbse-12-physics',
    code: '042',
    name: 'Physics',
    class: '12',
    academicSession: '2026-27',
    category: 'elective',
    streamRelevance: ['pcm', 'pcb', 'pcmb', 'science_cs'],
    description: 'Electrostatics, Current Electricity, Magnetic Effects, EMI & AC, Optics, Modern Physics, Semiconductor Devices.',
    ncertBookTitle: 'Physics Part I & II (Class XII)',
    officialSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
    officialTextbookUrl: `${OFFICIAL_NCERT_PORTAL}?leph1=0-8`,
    units: [
      { unitNumber: 1, title: 'Electrostatics', marksWeightage: 16, chapterIds: ['c12-phy-1', 'c12-phy-2'] },
      { unitNumber: 2, title: 'Current Electricity', marksWeightage: 8, chapterIds: ['c12-phy-3'] },
      { unitNumber: 3, title: 'Magnetic Effects of Current and Magnetism', marksWeightage: 17, chapterIds: ['c12-phy-4', 'c12-phy-5'] },
      { unitNumber: 4, title: 'Electromagnetic Induction and Alternating Currents', marksWeightage: 12, chapterIds: ['c12-phy-6', 'c12-phy-7'] },
      { unitNumber: 5, title: 'Electromagnetic Waves & Optics', marksWeightage: 18, chapterIds: ['c12-phy-8', 'c12-phy-9', 'c12-phy-10'] },
      { unitNumber: 6, title: 'Dual Nature of Radiation, Atoms and Nuclei', marksWeightage: 12, chapterIds: ['c12-phy-11', 'c12-phy-12', 'c12-phy-13'] },
      { unitNumber: 7, title: 'Electronic Devices', marksWeightage: 7, chapterIds: ['c12-phy-14'] },
    ],
    chapterIds: [
      'c12-phy-1', 'c12-phy-2', 'c12-phy-3', 'c12-phy-4', 'c12-phy-5', 'c12-phy-6',
      'c12-phy-7', 'c12-phy-8', 'c12-phy-9', 'c12-phy-10', 'c12-phy-11', 'c12-phy-12',
      'c12-phy-13', 'c12-phy-14'
    ],
  },
  {
    id: 'cbse-12-chemistry',
    code: '043',
    name: 'Chemistry',
    class: '12',
    academicSession: '2026-27',
    category: 'elective',
    streamRelevance: ['pcm', 'pcb', 'pcmb', 'science_cs'],
    description: 'Solutions, Electrochemistry, Kinetics, d and f Block Elements, Coordination Compounds, Haloalkanes, Alcohols, Aldehydes, Amines, Biomolecules.',
    ncertBookTitle: 'Chemistry Part I & II (Class XII)',
    officialSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
    officialTextbookUrl: `${OFFICIAL_NCERT_PORTAL}?lech1=0-5`,
    units: [
      { unitNumber: 1, title: 'Solutions', marksWeightage: 7, chapterIds: ['c12-chem-1'] },
      { unitNumber: 2, title: 'Electrochemistry', marksWeightage: 9, chapterIds: ['c12-chem-2'] },
      { unitNumber: 3, title: 'Chemical Kinetics', marksWeightage: 7, chapterIds: ['c12-chem-3'] },
      { unitNumber: 4, title: 'The d- and f-Block Elements', marksWeightage: 7, chapterIds: ['c12-chem-4'] },
      { unitNumber: 5, title: 'Coordination Compounds', marksWeightage: 7, chapterIds: ['c12-chem-5'] },
      { unitNumber: 6, title: 'Haloalkanes and Haloarenes', marksWeightage: 6, chapterIds: ['c12-chem-6'] },
      { unitNumber: 7, title: 'Alcohols, Phenols and Ethers', marksWeightage: 6, chapterIds: ['c12-chem-7'] },
      { unitNumber: 8, title: 'Aldehydes, Ketones and Carboxylic Acids', marksWeightage: 8, chapterIds: ['c12-chem-8'] },
      { unitNumber: 9, title: 'Amines', marksWeightage: 6, chapterIds: ['c12-chem-9'] },
      { unitNumber: 10, title: 'Biomolecules', marksWeightage: 7, chapterIds: ['c12-chem-10'] },
    ],
    chapterIds: [
      'c12-chem-1', 'c12-chem-2', 'c12-chem-3', 'c12-chem-4', 'c12-chem-5',
      'c12-chem-6', 'c12-chem-7', 'c12-chem-8', 'c12-chem-9', 'c12-chem-10'
    ],
  },
  {
    id: 'cbse-12-mathematics',
    code: '041',
    name: 'Mathematics',
    class: '12',
    academicSession: '2026-27',
    category: 'elective',
    streamRelevance: ['pcm', 'pcmb', 'science_cs', 'commerce_math', 'humanities_math'],
    description: 'Relations & Functions, Algebra (Matrices & Determinants), Calculus, Vectors & 3D Geometry, Linear Programming, Probability.',
    ncertBookTitle: 'Mathematics Part I & II (Class XII)',
    officialSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
    officialTextbookUrl: `${OFFICIAL_NCERT_PORTAL}?lemh1=0-6`,
    units: [
      { unitNumber: 1, title: 'Relations and Functions', marksWeightage: 8, chapterIds: ['c12-math-1', 'c12-math-2'] },
      { unitNumber: 2, title: 'Algebra (Matrices & Determinants)', marksWeightage: 10, chapterIds: ['c12-math-3', 'c12-math-4'] },
      { unitNumber: 3, title: 'Calculus', marksWeightage: 35, chapterIds: ['c12-math-5', 'c12-math-6', 'c12-math-7', 'c12-math-8', 'c12-math-9'] },
      { unitNumber: 4, title: 'Vectors and Three-Dimensional Geometry', marksWeightage: 14, chapterIds: ['c12-math-10', 'c12-math-11'] },
      { unitNumber: 5, title: 'Linear Programming', marksWeightage: 5, chapterIds: ['c12-math-12'] },
      { unitNumber: 6, title: 'Probability', marksWeightage: 8, chapterIds: ['c12-math-13'] },
    ],
    chapterIds: [
      'c12-math-1', 'c12-math-2', 'c12-math-3', 'c12-math-4', 'c12-math-5', 'c12-math-6',
      'c12-math-7', 'c12-math-8', 'c12-math-9', 'c12-math-10', 'c12-math-11', 'c12-math-12', 'c12-math-13'
    ],
  },
  {
    id: 'cbse-12-biology',
    code: '044',
    name: 'Biology',
    class: '12',
    academicSession: '2026-27',
    category: 'elective',
    streamRelevance: ['pcb', 'pcmb'],
    description: 'Reproduction, Genetics and Evolution, Biology and Human Welfare, Biotechnology and its Applications, Ecology and Environment.',
    ncertBookTitle: 'Biology: Textbook for Class XII',
    officialSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
    officialTextbookUrl: `${OFFICIAL_NCERT_PORTAL}?lebo1=0-13`,
    units: [
      { unitNumber: 1, title: 'Reproduction', marksWeightage: 16, chapterIds: ['c12-bio-1', 'c12-bio-2', 'c12-bio-3'] },
      { unitNumber: 2, title: 'Genetics and Evolution', marksWeightage: 20, chapterIds: ['c12-bio-4', 'c12-bio-5', 'c12-bio-6'] },
      { unitNumber: 3, title: 'Biology and Human Welfare', marksWeightage: 12, chapterIds: ['c12-bio-7', 'c12-bio-8'] },
      { unitNumber: 4, title: 'Biotechnology and its Applications', marksWeightage: 12, chapterIds: ['c12-bio-9', 'c12-bio-10'] },
      { unitNumber: 5, title: 'Ecology and Environment', marksWeightage: 10, chapterIds: ['c12-bio-11', 'c12-bio-12', 'c12-bio-13'] },
    ],
    chapterIds: [
      'c12-bio-1', 'c12-bio-2', 'c12-bio-3', 'c12-bio-4', 'c12-bio-5', 'c12-bio-6',
      'c12-bio-7', 'c12-bio-8', 'c12-bio-9', 'c12-bio-10', 'c12-bio-11', 'c12-bio-12', 'c12-bio-13'
    ],
  },
  {
    id: 'cbse-12-cs',
    code: '083',
    name: 'Computer Science',
    class: '12',
    academicSession: '2026-27',
    category: 'elective',
    streamRelevance: ['science_cs', 'pcm', 'commerce_math'],
    description: 'Computational Thinking and Programming - 2 (Python, File Handling, Stack), Computer Networks, Database Management (SQL & Python-MySQL connectivity).',
    ncertBookTitle: 'Computer Science with Python (Class XII)',
    officialSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
    officialTextbookUrl: `${OFFICIAL_NCERT_PORTAL}?lecs1=0-7`,
    units: [
      { unitNumber: 1, title: 'Computational Thinking and Programming - 2', marksWeightage: 40, chapterIds: ['c12-cs-1', 'c12-cs-2', 'c12-cs-3', 'c12-cs-4'] },
      { unitNumber: 2, title: 'Computer Networks', marksWeightage: 10, chapterIds: ['c12-cs-5'] },
      { unitNumber: 3, title: 'Database Management (SQL)', marksWeightage: 20, chapterIds: ['c12-cs-6', 'c12-cs-7'] },
    ],
    chapterIds: ['c12-cs-1', 'c12-cs-2', 'c12-cs-3', 'c12-cs-4', 'c12-cs-5', 'c12-cs-6', 'c12-cs-7'],
  },
  {
    id: 'cbse-12-english',
    code: '301',
    name: 'English Core',
    class: '12',
    academicSession: '2026-27',
    category: 'compulsory',
    streamRelevance: ['pcm', 'pcb', 'pcmb', 'science_cs', 'commerce_math', 'commerce_no_math', 'humanities', 'humanities_math'],
    description: 'Reading Comprehension, Creative Writing Skills, Flamingo (Prose & Poetry), Vistas (Supplementary Reader).',
    ncertBookTitle: 'Flamingo & Vistas (Class XII)',
    officialSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
    officialTextbookUrl: `${OFFICIAL_NCERT_PORTAL}?lefl1=0-13`,
    units: [
      { unitNumber: 1, title: 'Reading & Creative Writing Skills', marksWeightage: 38, chapterIds: ['c12-eng-skills'] },
      { unitNumber: 2, title: 'Flamingo (Prose & Poetry)', marksWeightage: 28, chapterIds: ['c12-eng-flam-1', 'c12-eng-flam-2', 'c12-eng-flam-3', 'c12-eng-flam-4', 'c12-eng-flam-5'] },
      { unitNumber: 3, title: 'Vistas (Supplementary Reader)', marksWeightage: 14, chapterIds: ['c12-eng-vis-1', 'c12-eng-vis-2', 'c12-eng-vis-3'] },
    ],
    chapterIds: ['c12-eng-skills', 'c12-eng-flam-1', 'c12-eng-flam-2', 'c12-eng-flam-3', 'c12-eng-flam-4', 'c12-eng-flam-5', 'c12-eng-vis-1', 'c12-eng-vis-2', 'c12-eng-vis-3'],
  },
  {
    id: 'cbse-12-accountancy',
    code: '055',
    name: 'Accountancy',
    class: '12',
    academicSession: '2026-27',
    category: 'elective',
    streamRelevance: ['commerce_math', 'commerce_no_math'],
    description: 'Accounting for Partnership Firms and Companies, Analysis of Financial Statements, Cash Flow Statement.',
    ncertBookTitle: 'Accountancy Part I & II (Class XII)',
    officialSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
    officialTextbookUrl: `${OFFICIAL_NCERT_PORTAL}?leac1=0-5`,
    units: [
      { unitNumber: 1, title: 'Accounting for Partnership Firms', marksWeightage: 36, chapterIds: ['c12-acc-1', 'c12-acc-2', 'c12-acc-3', 'c12-acc-4'] },
      { unitNumber: 2, title: 'Accounting for Companies (Shares & Debentures)', marksWeightage: 24, chapterIds: ['c12-acc-5', 'c12-acc-6'] },
      { unitNumber: 3, title: 'Financial Statement Analysis & Cash Flow', marksWeightage: 20, chapterIds: ['c12-acc-7', 'c12-acc-8'] },
    ],
    chapterIds: ['c12-acc-1', 'c12-acc-2', 'c12-acc-3', 'c12-acc-4', 'c12-acc-5', 'c12-acc-6', 'c12-acc-7', 'c12-acc-8'],
  },
  {
    id: 'cbse-12-bst',
    code: '054',
    name: 'Business Studies',
    class: '12',
    academicSession: '2026-27',
    category: 'elective',
    streamRelevance: ['commerce_math', 'commerce_no_math'],
    description: 'Principles & Functions of Management, Business Finance and Marketing.',
    ncertBookTitle: 'Business Studies Part I & II (Class XII)',
    officialSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
    officialTextbookUrl: `${OFFICIAL_NCERT_PORTAL}?lebs1=0-8`,
    units: [
      { unitNumber: 1, title: 'Principles and Functions of Management', marksWeightage: 50, chapterIds: ['c12-bst-1', 'c12-bst-2', 'c12-bst-3', 'c12-bst-4', 'c12-bst-5', 'c12-bst-6', 'c12-bst-7', 'c12-bst-8'] },
      { unitNumber: 2, title: 'Business Finance and Marketing', marksWeightage: 30, chapterIds: ['c12-bst-9', 'c12-bst-10', 'c12-bst-11', 'c12-bst-12'] },
    ],
    chapterIds: [
      'c12-bst-1', 'c12-bst-2', 'c12-bst-3', 'c12-bst-4', 'c12-bst-5', 'c12-bst-6',
      'c12-bst-7', 'c12-bst-8', 'c12-bst-9', 'c12-bst-10', 'c12-bst-11', 'c12-bst-12'
    ],
  },
  {
    id: 'cbse-12-economics',
    code: '030',
    name: 'Economics',
    class: '12',
    academicSession: '2026-27',
    category: 'elective',
    streamRelevance: ['commerce_math', 'commerce_no_math', 'humanities', 'humanities_math'],
    description: 'Part A: Introductory Macroeconomics; Part B: Indian Economic Development.',
    ncertBookTitle: 'Introductory Macroeconomics & Indian Economic Development',
    officialSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
    officialTextbookUrl: `${OFFICIAL_NCERT_PORTAL}?leec1=0-6`,
    units: [
      { unitNumber: 1, title: 'Introductory Macroeconomics', marksWeightage: 40, chapterIds: ['c12-eco-macro-1', 'c12-eco-macro-2', 'c12-eco-macro-3', 'c12-eco-macro-4', 'c12-eco-macro-5'] },
      { unitNumber: 2, title: 'Indian Economic Development', marksWeightage: 40, chapterIds: ['c12-eco-dev-1', 'c12-eco-dev-2', 'c12-eco-dev-3'] },
    ],
    chapterIds: ['c12-eco-macro-1', 'c12-eco-macro-2', 'c12-eco-macro-3', 'c12-eco-macro-4', 'c12-eco-macro-5', 'c12-eco-dev-1', 'c12-eco-dev-2', 'c12-eco-dev-3'],
  },
  {
    id: 'cbse-12-history',
    code: '027',
    name: 'History',
    class: '12',
    academicSession: '2026-27',
    category: 'elective',
    streamRelevance: ['humanities', 'humanities_math'],
    description: 'Themes in Indian History Parts I, II, and III (Ancient, Medieval, and Modern Indian History).',
    ncertBookTitle: 'Themes in Indian History Part I, II, III (Class XII)',
    officialSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
    officialTextbookUrl: `${OFFICIAL_NCERT_PORTAL}?lehs1=0-4`,
    units: [
      { unitNumber: 1, title: 'Themes in Indian History Part I (Ancient)', marksWeightage: 25, chapterIds: ['c12-hist-1', 'c12-hist-2', 'c12-hist-3', 'c12-hist-4'] },
      { unitNumber: 2, title: 'Themes in Indian History Part II (Medieval)', marksWeightage: 25, chapterIds: ['c12-hist-5', 'c12-hist-6', 'c12-hist-7', 'c12-hist-8'] },
      { unitNumber: 3, title: 'Themes in Indian History Part III (Modern)', marksWeightage: 25, chapterIds: ['c12-hist-9', 'c12-hist-10', 'c12-hist-11', 'c12-hist-12'] },
    ],
    chapterIds: [
      'c12-hist-1', 'c12-hist-2', 'c12-hist-3', 'c12-hist-4', 'c12-hist-5', 'c12-hist-6',
      'c12-hist-7', 'c12-hist-8', 'c12-hist-9', 'c12-hist-10', 'c12-hist-11', 'c12-hist-12'
    ],
  },
  {
    id: 'cbse-12-polsci',
    code: '028',
    name: 'Political Science',
    class: '12',
    academicSession: '2026-27',
    category: 'elective',
    streamRelevance: ['humanities', 'humanities_math'],
    description: 'Part A: Contemporary World Politics; Part B: Politics in India Since Independence.',
    ncertBookTitle: 'Contemporary World Politics & Politics in India Since Independence',
    officialSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
    officialTextbookUrl: `${OFFICIAL_NCERT_PORTAL}?leps1=0-7`,
    units: [
      { unitNumber: 1, title: 'Contemporary World Politics', marksWeightage: 40, chapterIds: ['c12-pol-1', 'c12-pol-2', 'c12-pol-3', 'c12-pol-4', 'c12-pol-5', 'c12-pol-6', 'c12-pol-7'] },
      { unitNumber: 2, title: 'Politics in India Since Independence', marksWeightage: 40, chapterIds: ['c12-pol-8', 'c12-pol-9', 'c12-pol-10', 'c12-pol-11', 'c12-pol-12', 'c12-pol-13'] },
    ],
    chapterIds: [
      'c12-pol-1', 'c12-pol-2', 'c12-pol-3', 'c12-pol-4', 'c12-pol-5', 'c12-pol-6', 'c12-pol-7',
      'c12-pol-8', 'c12-pol-9', 'c12-pol-10', 'c12-pol-11', 'c12-pol-12', 'c12-pol-13'
    ],
  },
  {
    id: 'cbse-12-pe',
    code: '048',
    name: 'Physical Education',
    class: '12',
    academicSession: '2026-27',
    category: 'elective',
    streamRelevance: ['pcm', 'pcb', 'pcmb', 'science_cs', 'commerce_math', 'commerce_no_math', 'humanities', 'humanities_math'],
    description: 'Management of Sporting Events, Children and Women in Sports, Yoga as Preventive Measure, Physical Education for CWSN, Sports and Nutrition, Physiology and Injuries, Training in Sports.',
    ncertBookTitle: 'Physical Education: CBSE Class XII',
    officialSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
    officialTextbookUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
    units: [
      { unitNumber: 1, title: 'Sports Management & Nutrition', marksWeightage: 35, chapterIds: ['c12-pe-1', 'c12-pe-2', 'c12-pe-3', 'c12-pe-4', 'c12-pe-5'] },
      { unitNumber: 2, title: 'Biomechanics, Psychology & Sports Injuries', marksWeightage: 35, chapterIds: ['c12-pe-6', 'c12-pe-7', 'c12-pe-8', 'c12-pe-9', 'c12-pe-10'] },
    ],
    chapterIds: ['c12-pe-1', 'c12-pe-2', 'c12-pe-3', 'c12-pe-4', 'c12-pe-5', 'c12-pe-6', 'c12-pe-7', 'c12-pe-8', 'c12-pe-9', 'c12-pe-10'],
  },
];
