import { type CurriculumChapter } from './types';
import { OFFICIAL_CBSE_SYLLABUS_PORTAL, OFFICIAL_NCERT_PORTAL } from './cbse-2027-database';

export const CLASS_11_CHAPTERS: CurriculumChapter[] = [
  // -------------------------------------------------------------------------
  // PHYSICS (042)
  // -------------------------------------------------------------------------
  {
    id: 'phy-units',
    subjectId: 'cbse-11-physics',
    subjectName: 'Physics',
    subjectCode: '042',
    class: '11',
    academicSession: '2026-27',
    title: 'Units and Measurements',
    chapterNumber: 1,
    unitNumber: 1,
    unitName: 'Physical World and Measurement',
    description: 'SI units, fundamental and derived units, significant figures, dimensions of physical quantities, dimensional analysis and its applications.',
    defaultEstimatedHours: 5,
    examWeightage: 'high',
    difficulty: 'easy',
    prerequisites: [],
    inCbseSyllabus: true,
    topics: [
      { id: 'p11-u1-t1', name: 'SI units, base units and supplementary units', inCbseSyllabus: true },
      { id: 'p11-u1-t2', name: 'Significant figures, rounding off and error propagation', inCbseSyllabus: true },
      { id: 'p11-u1-t3', name: 'Dimensional formula and applications (homogeneity check, unit conversion, derivation)', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?keph1=1-8`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'phy-vectors',
    subjectId: 'cbse-11-physics',
    subjectName: 'Physics',
    subjectCode: '042',
    class: '11',
    academicSession: '2026-27',
    title: 'Motion in a Straight Line',
    chapterNumber: 2,
    unitNumber: 2,
    unitName: 'Kinematics',
    description: 'Frame of reference, position-time graph, speed and velocity, uniform and non-uniform motion, instantaneous velocity, kinematic equations for uniformly accelerated motion.',
    defaultEstimatedHours: 6,
    examWeightage: 'critical',
    difficulty: 'medium',
    prerequisites: ['phy-units'],
    inCbseSyllabus: true,
    topics: [
      { id: 'p11-u2-t1', name: 'Position, path length, displacement, average & instantaneous velocity/acceleration', inCbseSyllabus: true },
      { id: 'p11-u2-t2', name: 'Kinematic equations v = u + at, s = ut + 1/2at^2, v^2 = u^2 + 2as calculus derivation', inCbseSyllabus: true },
      { id: 'p11-u2-t3', name: 'Motion under gravity, relative velocity in 1D', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?keph1=2-8`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'phy-motion-plane',
    subjectId: 'cbse-11-physics',
    subjectName: 'Physics',
    subjectCode: '042',
    class: '11',
    academicSession: '2026-27',
    title: 'Motion in a Plane',
    chapterNumber: 3,
    unitNumber: 2,
    unitName: 'Kinematics',
    description: 'Scalar and vector quantities, position and displacement vectors, equality of vectors, resolution of a vector, dot and cross products, projectile motion, uniform circular motion.',
    defaultEstimatedHours: 8,
    examWeightage: 'critical',
    difficulty: 'hard',
    prerequisites: ['phy-vectors'],
    inCbseSyllabus: true,
    topics: [
      { id: 'p11-u3-t1', name: 'Vector algebra: Triangle law, parallelogram law, polygon law, scalar & vector products', inCbseSyllabus: true },
      { id: 'p11-u3-t2', name: 'Projectile motion: Trajectory, time of flight, maximum height, horizontal range', inCbseSyllabus: true },
      { id: 'p11-u3-t3', name: 'Uniform circular motion: Angular velocity, centripetal acceleration ac = v^2/r', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?keph1=3-8`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'phy-laws',
    subjectId: 'cbse-11-physics',
    subjectName: 'Physics',
    subjectCode: '042',
    class: '11',
    academicSession: '2026-27',
    title: 'Laws of Motion',
    chapterNumber: 4,
    unitNumber: 3,
    unitName: 'Laws of Motion',
    description: 'Intuitive concept of force, Inertia, Newton first, second, and third laws of motion, momentum, impulse, conservation of linear momentum, equilibrium of concurrent forces, static and kinetic friction, dynamics of circular motion.',
    defaultEstimatedHours: 8,
    examWeightage: 'critical',
    difficulty: 'hard',
    prerequisites: ['phy-motion-plane'],
    inCbseSyllabus: true,
    topics: [
      { id: 'p11-u4-t1', name: 'Newton laws of motion, F = dp/dt = ma, Free-body diagrams (FBD)', inCbseSyllabus: true },
      { id: 'p11-u4-t2', name: 'Law of conservation of linear momentum and recoil velocity', inCbseSyllabus: true },
      { id: 'p11-u4-t3', name: 'Friction: Static (fs <= mu_s N), limiting, kinetic friction, laws of friction', inCbseSyllabus: true },
      { id: 'p11-u4-t4', name: 'Banking of circular roads, maximum safe speed v = sqrt(rg (mu + tan theta)/(1 - mu tan theta))', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?keph1=4-8`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'phy-work',
    subjectId: 'cbse-11-physics',
    subjectName: 'Physics',
    subjectCode: '042',
    class: '11',
    academicSession: '2026-27',
    title: 'Work, Energy and Power',
    chapterNumber: 5,
    unitNumber: 4,
    unitName: 'Work, Energy and Power',
    description: 'Work done by a constant force and a variable force, kinetic energy, work-energy theorem, power, potential energy of a spring, conservative and non-conservative forces, conservation of mechanical energy, elastic and inelastic collisions.',
    defaultEstimatedHours: 7,
    examWeightage: 'critical',
    difficulty: 'medium',
    prerequisites: ['phy-laws'],
    inCbseSyllabus: true,
    topics: [
      { id: 'p11-u5-t1', name: 'Work done W = Integral F.dx, Work-Energy Theorem (W_net = Delta K)', inCbseSyllabus: true },
      { id: 'p11-u5-t2', name: 'Conservative forces, potential energy of spring U = 1/2 k x^2', inCbseSyllabus: true },
      { id: 'p11-u5-t3', name: 'Elastic and inelastic collisions in 1D and 2D, coefficient of restitution', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?keph1=5-8`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'phy-system',
    subjectId: 'cbse-11-physics',
    subjectName: 'Physics',
    subjectCode: '042',
    class: '11',
    academicSession: '2026-27',
    title: 'System of Particles and Rotational Motion',
    chapterNumber: 6,
    unitNumber: 5,
    unitName: 'Motion of System of Particles and Rigid Body',
    description: 'Centre of mass of a two-particle system, momentum conservation and centre of mass motion, torque, angular momentum, conservation of angular momentum, moment of inertia, radius of gyration, values of moments of inertia for simple geometrical objects.',
    defaultEstimatedHours: 9,
    examWeightage: 'critical',
    difficulty: 'hard',
    prerequisites: ['phy-work'],
    inCbseSyllabus: true,
    topics: [
      { id: 'p11-u6-t1', name: 'Centre of mass coordinates R_cm = Sum(m_i r_i)/M for discrete and continuous bodies', inCbseSyllabus: true },
      { id: 'p11-u6-t2', name: 'Torque tau = r x F, Angular momentum L = r x p = I omega, conservation of L', inCbseSyllabus: true },
      { id: 'p11-u6-t3', name: 'Moment of inertia I = Sum(m_i r_i^2), radius of gyration, values for ring, disc, cylinder, sphere', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?keph1=6-8`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'phy-gravity',
    subjectId: 'cbse-11-physics',
    subjectName: 'Physics',
    subjectCode: '042',
    class: '11',
    academicSession: '2026-27',
    title: 'Gravitation',
    chapterNumber: 7,
    unitNumber: 6,
    unitName: 'Gravitation',
    description: "Kepler laws of planetary motion, universal law of gravitation, acceleration due to gravity and its variation with altitude and depth, gravitational potential energy and gravitational potential, escape velocity, orbital velocity of a satellite.",
    defaultEstimatedHours: 6,
    examWeightage: 'high',
    difficulty: 'medium',
    prerequisites: ['phy-work'],
    inCbseSyllabus: true,
    topics: [
      { id: 'p11-u7-t1', name: 'Kepler laws of planetary motion, Newton Law of Gravitation F = G m1 m2 / r^2', inCbseSyllabus: true },
      { id: 'p11-u7-t2', name: 'Variation of g with height g_h = g(1 - 2h/R) and depth g_d = g(1 - d/R)', inCbseSyllabus: true },
      { id: 'p11-u7-t3', name: 'Gravitational potential energy U = -G M m / r, escape velocity v_e = sqrt(2gR), orbital velocity', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?keph1=7-8`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'phy-solids',
    subjectId: 'cbse-11-physics',
    subjectName: 'Physics',
    subjectCode: '042',
    class: '11',
    academicSession: '2026-27',
    title: 'Mechanical Properties of Solids',
    chapterNumber: 8,
    unitNumber: 7,
    unitName: 'Properties of Bulk Matter',
    description: "Stress-strain relationship, Hooke law, Young modulus, bulk modulus, shear modulus of rigidity, Poisson ratio; elastic energy.",
    defaultEstimatedHours: 5,
    examWeightage: 'medium',
    difficulty: 'easy',
    prerequisites: ['phy-work'],
    inCbseSyllabus: true,
    topics: [
      { id: 'p11-u8-t1', name: "Hooke's Law, stress-strain curve, yield point, breaking stress", inCbseSyllabus: true },
      { id: 'p11-u8-t2', name: 'Elastic moduli: Young modulus Y, Bulk modulus B, Shear modulus G, elastic energy per unit volume', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?keph2=1-7`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'phy-fluids',
    subjectId: 'cbse-11-physics',
    subjectName: 'Physics',
    subjectCode: '042',
    class: '11',
    academicSession: '2026-27',
    title: 'Mechanical Properties of Fluids',
    chapterNumber: 9,
    unitNumber: 7,
    unitName: 'Properties of Bulk Matter',
    description: "Pressure due to a fluid column; Pascal law and its applications, effect of gravity on fluid pressure. Viscosity, Stokes law, terminal velocity, streamline and turbulent flow, critical velocity, Bernoulli principle and its applications. Surface energy and surface tension, angle of contact, excess of pressure across a curved surface, capillary rise.",
    defaultEstimatedHours: 7,
    examWeightage: 'critical',
    difficulty: 'hard',
    prerequisites: ['phy-laws'],
    inCbseSyllabus: true,
    topics: [
      { id: 'p11-u9-t1', name: 'Pascal law, hydraulic lift, atmospheric pressure and gauge pressure', inCbseSyllabus: true },
      { id: 'p11-u9-t2', name: 'Stokes law F = 6 pi eta r v, terminal velocity, equation of continuity A1 v1 = A2 v2', inCbseSyllabus: true },
      { id: 'p11-u9-t3', name: 'Bernoulli principle P + 1/2 rho v^2 + rho g h = const, Venturimeter', inCbseSyllabus: true },
      { id: 'p11-u9-t4', name: 'Surface tension, excess pressure in bubble/drop (2T/R, 4T/R), capillary rise formula', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?keph2=2-7`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'phy-thermal',
    subjectId: 'cbse-11-physics',
    subjectName: 'Physics',
    subjectCode: '042',
    class: '11',
    academicSession: '2026-27',
    title: 'Thermal Properties of Matter',
    chapterNumber: 10,
    unitNumber: 7,
    unitName: 'Properties of Bulk Matter',
    description: 'Heat, temperature, thermal expansion; thermal expansion of solids, liquids and gases, anomalous expansion of water; specific heat capacity; Cp, Cv - calorimetry; change of state - latent heat capacity. Heat transfer - conduction, convection and radiation, thermal conductivity, qualitative ideas of Blackbody radiation, Wien displacement law, Stefan law.',
    defaultEstimatedHours: 6,
    examWeightage: 'high',
    difficulty: 'medium',
    prerequisites: [],
    inCbseSyllabus: true,
    topics: [
      { id: 'p11-u10-t1', name: 'Thermal expansion (alpha, beta, gamma coefficients), calorimetry, latent heat', inCbseSyllabus: true },
      { id: 'p11-u10-t2', name: 'Conduction, thermal resistance, Stefan-Boltzmann law E = sigma T^4, Wien law lambda_m T = b', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?keph2=3-7`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'phy-thermo',
    subjectId: 'cbse-11-physics',
    subjectName: 'Physics',
    subjectCode: '042',
    class: '11',
    academicSession: '2026-27',
    title: 'Thermodynamics',
    chapterNumber: 11,
    unitNumber: 8,
    unitName: 'Thermodynamics',
    description: 'Thermal equilibrium and definition of temperature (zeroth law of thermodynamics). Heat, work and internal energy. First law of thermodynamics. Isothermal and adiabatic processes. Second law of thermodynamics: reversible and irreversible processes.',
    defaultEstimatedHours: 6,
    examWeightage: 'critical',
    difficulty: 'medium',
    prerequisites: ['phy-thermal'],
    inCbseSyllabus: true,
    topics: [
      { id: 'p11-u11-t1', name: 'Zeroth Law & First Law of thermodynamics Delta Q = Delta U + Delta W', inCbseSyllabus: true },
      { id: 'p11-u11-t2', name: 'Isothermal (PV = const, W = nRT ln(V2/V1)) and Adiabatic (PV^gamma = const) work done', inCbseSyllabus: true },
      { id: 'p11-u11-t3', name: 'Second Law of thermodynamics: Kelvin-Planck and Clausius statements', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?keph2=4-7`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'phy-kinetic',
    subjectId: 'cbse-11-physics',
    subjectName: 'Physics',
    subjectCode: '042',
    class: '11',
    academicSession: '2026-27',
    title: 'Kinetic Theory',
    chapterNumber: 12,
    unitNumber: 9,
    unitName: 'Kinetic Theory of Gases',
    description: 'Equation of state of a perfect gas, work done in compressing a gas. Kinetic theory of gases - assumptions, concept of pressure. Kinetic interpretation of temperature; rms speed of gas molecules; degrees of freedom, law of equi-partition of energy and application to specific heat capacities of gases; concept of mean free path.',
    defaultEstimatedHours: 5,
    examWeightage: 'high',
    difficulty: 'easy',
    prerequisites: ['phy-thermo'],
    inCbseSyllabus: true,
    topics: [
      { id: 'p11-u12-t1', name: 'Ideal gas equation PV = nRT, pressure formula P = 1/3 rho v_rms^2', inCbseSyllabus: true },
      { id: 'p11-u12-t2', name: 'Law of equipartition of energy, degrees of freedom, mono/di/polyatomic Cv & Cp values', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?keph2=5-7`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'phy-oscillations',
    subjectId: 'cbse-11-physics',
    subjectName: 'Physics',
    subjectCode: '042',
    class: '11',
    academicSession: '2026-27',
    title: 'Oscillations',
    chapterNumber: 13,
    unitNumber: 10,
    unitName: 'Oscillations and Waves',
    description: 'Periodic motion - time period, frequency, displacement as a function of time, periodic functions. Simple harmonic motion (S.H.M) and its equation; phase; oscillations of a loaded spring-restoring force and force constant; energy in S.H.M. Kinetic and potential energies; simple pendulum derivation of expression for its time period.',
    defaultEstimatedHours: 7,
    examWeightage: 'critical',
    difficulty: 'hard',
    prerequisites: ['phy-work'],
    inCbseSyllabus: true,
    topics: [
      { id: 'p11-u13-t1', name: 'SHM equation x = A cos(omega t + phi), velocity v = omega sqrt(A^2 - x^2), acceleration a = -omega^2 x', inCbseSyllabus: true },
      { id: 'p11-u13-t2', name: 'Kinetic energy, potential energy in SHM and energy conservation', inCbseSyllabus: true },
      { id: 'p11-u13-t3', name: 'Simple pendulum time period T = 2 pi sqrt(L/g) and spring mass system T = 2 pi sqrt(m/k)', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?keph2=6-7`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'phy-waves',
    subjectId: 'cbse-11-physics',
    subjectName: 'Physics',
    subjectCode: '042',
    class: '11',
    academicSession: '2026-27',
    title: 'Waves',
    chapterNumber: 14,
    unitNumber: 10,
    unitName: 'Oscillations and Waves',
    description: 'Wave motion: Transverse and longitudinal waves, speed of travelling wave, displacement relation for a progressive wave, principle of superposition of waves, reflection of waves, standing waves in strings and organ pipes, fundamental mode and harmonics, Beats.',
    defaultEstimatedHours: 7,
    examWeightage: 'critical',
    difficulty: 'hard',
    prerequisites: ['phy-oscillations'],
    inCbseSyllabus: true,
    topics: [
      { id: 'p11-u14-t1', name: 'Progressive wave equation y = A sin(kx - omega t), speed v = nu lambda = omega / k', inCbseSyllabus: true },
      { id: 'p11-u14-t2', name: 'Standing waves in stretched string and closed/open organ pipes, harmonics & overtones', inCbseSyllabus: true },
      { id: 'p11-u14-t3', name: 'Beats frequency f_beat = |f1 - f2|', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?keph2=7-7`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },

  // -------------------------------------------------------------------------
  // CHEMISTRY (043)
  // -------------------------------------------------------------------------
  {
    id: 'chem-basic',
    subjectId: 'cbse-11-chemistry',
    subjectName: 'Chemistry',
    subjectCode: '043',
    class: '11',
    academicSession: '2026-27',
    title: 'Some Basic Concepts of Chemistry',
    chapterNumber: 1,
    unitNumber: 1,
    unitName: 'Some Basic Concepts of Chemistry',
    description: 'General Introduction: Importance and scope of Chemistry. Nature of matter, laws of chemical combination, Dalton atomic theory: concept of elements, atoms and molecules. Atomic and molecular masses, mole concept and molar mass, percentage composition, empirical and molecular formula, chemical reactions, stoichiometry and calculations based on stoichiometry.',
    defaultEstimatedHours: 7,
    examWeightage: 'critical',
    difficulty: 'medium',
    prerequisites: [],
    inCbseSyllabus: true,
    topics: [
      { id: 'c11-c1-t1', name: 'Mole concept, molar mass, Avogadro number N_A = 6.022 x 10^23', inCbseSyllabus: true },
      { id: 'c11-c1-t2', name: 'Empirical formula and molecular formula calculations', inCbseSyllabus: true },
      { id: 'c11-c1-t3', name: 'Stoichiometry, limiting reagent, and concentration terms (Molarity, Molality, Mole fraction)', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?kech1=1-6`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'chem-structure',
    subjectId: 'cbse-11-chemistry',
    subjectName: 'Chemistry',
    subjectCode: '043',
    class: '11',
    academicSession: '2026-27',
    title: 'Structure of Atom',
    chapterNumber: 2,
    unitNumber: 2,
    unitName: 'Structure of Atom',
    description: 'Discovery of Electron, Proton and Neutron, atomic number, isotopes and isobars. Thomson model and its limitations. Rutherford model and its limitations, Bohr model and its limitations, dual nature of matter and light, de Broglie relationship, Heisenberg uncertainty principle, concept of orbitals, quantum numbers, shapes of s, p and d orbitals, rules for filling electrons in orbitals - Aufbau principle, Pauli exclusion principle and Hund rule, electronic configuration of atoms, stability of half-filled and completely filled orbitals.',
    defaultEstimatedHours: 8,
    examWeightage: 'critical',
    difficulty: 'hard',
    prerequisites: ['chem-basic'],
    inCbseSyllabus: true,
    topics: [
      { id: 'c11-c2-t1', name: 'Bohr model of hydrogen atom, Rydberg formula for spectral lines', inCbseSyllabus: true },
      { id: 'c11-c2-t2', name: 'de Broglie wavelength lambda = h/mv and Heisenberg Uncertainty Principle Delta x * Delta p >= h/4pi', inCbseSyllabus: true },
      { id: 'c11-c2-t3', name: 'Quantum numbers (n, l, m_l, m_s) and shapes of s, p, d orbitals', inCbseSyllabus: true },
      { id: 'c11-c2-t4', name: 'Aufbau principle, Pauli exclusion principle, Hund rule of maximum multiplicity, Cr & Cu configurations', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?kech1=2-6`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'chem-periodic',
    subjectId: 'cbse-11-chemistry',
    subjectName: 'Chemistry',
    subjectCode: '043',
    class: '11',
    academicSession: '2026-27',
    title: 'Classification of Elements and Periodicity in Properties',
    chapterNumber: 3,
    unitNumber: 3,
    unitName: 'Classification of Elements and Periodicity in Properties',
    description: 'Significance of classification, brief history of the development of periodic table, modern periodic law and the present form of periodic table, periodic trends in properties of elements -atomic radii, ionic radii, inert gas radii, Ionization enthalpy, electron gain enthalpy, electronegativity, valency. Nomenclature of elements with atomic number greater than 100.',
    defaultEstimatedHours: 5,
    examWeightage: 'high',
    difficulty: 'easy',
    prerequisites: ['chem-structure'],
    inCbseSyllabus: true,
    topics: [
      { id: 'c11-c3-t1', name: 'Modern periodic law, s, p, d, f blocks', inCbseSyllabus: true },
      { id: 'c11-c3-t2', name: 'Periodic trends: Atomic/ionic radius, ionization enthalpy exceptions (B vs Be, N vs O)', inCbseSyllabus: true },
      { id: 'c11-c3-t3', name: 'Electron gain enthalpy trends (Cl > F) and electronegativity on Pauling scale', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?kech1=3-6`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'chem-bonding',
    subjectId: 'cbse-11-chemistry',
    subjectName: 'Chemistry',
    subjectCode: '043',
    class: '11',
    academicSession: '2026-27',
    title: 'Chemical Bonding and Molecular Structure',
    chapterNumber: 4,
    unitNumber: 4,
    unitName: 'Chemical Bonding and Molecular Structure',
    description: 'Valence electrons, ionic bond, covalent bond, bond parameters, Lewis structure, polar character of covalent bond, covalent character of ionic bond, valence bond theory, resonance, geometry of covalent molecules, VSEPR theory, concept of hybridization, involving s, p and d orbitals and shapes of some simple molecules, molecular orbital theory of homonuclear diatomic molecules, hydrogen bond.',
    defaultEstimatedHours: 9,
    examWeightage: 'critical',
    difficulty: 'hard',
    prerequisites: ['chem-periodic'],
    inCbseSyllabus: true,
    topics: [
      { id: 'c11-c4-t1', name: 'Lewis structures, formal charge, dipole moment and Fajan rules', inCbseSyllabus: true },
      { id: 'c11-c4-t2', name: 'VSEPR theory geometry and shapes of molecules (NH3, H2O, SF4, ClF3, XeF4)', inCbseSyllabus: true },
      { id: 'c11-c4-t3', name: 'Hybridization: sp, sp2, sp3, sp3d, sp3d2 shapes and sigma/pi bonds', inCbseSyllabus: true },
      { id: 'c11-c4-t4', name: 'Molecular Orbital Theory (MOT): MO diagrams, bond order, magnetic properties of B2, C2, N2, O2', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?kech1=4-6`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'chem-thermo',
    subjectId: 'cbse-11-chemistry',
    subjectName: 'Chemistry',
    subjectCode: '043',
    class: '11',
    academicSession: '2026-27',
    title: 'Chemical Thermodynamics',
    chapterNumber: 5,
    unitNumber: 5,
    unitName: 'Chemical Thermodynamics',
    description: 'Concepts of System and types of systems, surroundings, work, heat, energy, extensive and intensive properties, state functions. First law of thermodynamics -internal energy and enthalpy, heat capacity and specific heat, measurement of Delta U and Delta H, Hess law of constant heat summation, enthalpy of bond dissociation, combustion, formation, atomization, sublimation, phase transition, ionization, solution and dilution. Second law of Thermodynamics (brief introduction). Introduction of entropy as a state function, Gibbs energy change for spontaneous and non-spontaneous processes, criteria for equilibrium. Third law of thermodynamics (brief introduction).',
    defaultEstimatedHours: 8,
    examWeightage: 'critical',
    difficulty: 'hard',
    prerequisites: ['chem-basic'],
    inCbseSyllabus: true,
    topics: [
      { id: 'c11-c5-t1', name: 'First law Delta U = q + w, Enthalpy Delta H = Delta U + Delta n_g RT', inCbseSyllabus: true },
      { id: 'c11-c5-t2', name: "Hess's Law of constant heat summation and standard enthalpies of reaction", inCbseSyllabus: true },
      { id: 'c11-c5-t3', name: 'Entropy Delta S, Gibbs free energy Delta G = Delta H - T Delta S and spontaneity criteria', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?kech1=5-6`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'chem-equilibrium',
    subjectId: 'cbse-11-chemistry',
    subjectName: 'Chemistry',
    subjectCode: '043',
    class: '11',
    academicSession: '2026-27',
    title: 'Equilibrium',
    chapterNumber: 6,
    unitNumber: 6,
    unitName: 'Equilibrium',
    description: 'Equilibrium in physical and chemical processes, dynamic nature of equilibrium, law of mass action, equilibrium constant, factors affecting equilibrium - Le Chatelier principle, ionic equilibrium- ionization of acids and bases, strong and weak electrolytes, degree of ionization, ionization of poly basic acids, acid strength, concept of pH, hydrolysis of salts, buffer solution, Henderson Equation, solubility product, common ion effect.',
    defaultEstimatedHours: 9,
    examWeightage: 'critical',
    difficulty: 'hard',
    prerequisites: ['chem-thermo'],
    inCbseSyllabus: true,
    topics: [
      { id: 'c11-c6-t1', name: 'Equilibrium constant Kp = Kc (RT)^Delta n_g and Le Chatelier principle', inCbseSyllabus: true },
      { id: 'c11-c6-t2', name: 'Arrhenius, Bronsted-Lowry, Lewis acid-base concepts, pH and ionization of weak acids/bases', inCbseSyllabus: true },
      { id: 'c11-c6-t3', name: 'Salt hydrolysis pH formulas, Buffer solutions (Henderson-Hasselbalch equation)', inCbseSyllabus: true },
      { id: 'c11-c6-t4', name: 'Solubility product K_sp and common ion effect applications in qualitative analysis', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?kech1=6-6`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'chem-redox',
    subjectId: 'cbse-11-chemistry',
    subjectName: 'Chemistry',
    subjectCode: '043',
    class: '11',
    academicSession: '2026-27',
    title: 'Redox Reactions',
    chapterNumber: 7,
    unitNumber: 7,
    unitName: 'Redox Reactions',
    description: 'Concept of oxidation and reduction, redox reactions, oxidation number, balancing redox reactions, in terms of loss and gain of electrons and change in oxidation number, applications of redox reactions.',
    defaultEstimatedHours: 5,
    examWeightage: 'high',
    difficulty: 'easy',
    prerequisites: ['chem-basic'],
    inCbseSyllabus: true,
    topics: [
      { id: 'c11-c7-t1', name: 'Rules for assigning oxidation numbers', inCbseSyllabus: true },
      { id: 'c11-c7-t2', name: 'Balancing redox reactions by ion-electron method in acidic and basic medium', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?kech2=1-5`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'chem-organic',
    subjectId: 'cbse-11-chemistry',
    subjectName: 'Chemistry',
    subjectCode: '043',
    class: '11',
    academicSession: '2026-27',
    title: 'Organic Chemistry – Some Basic Principles and Techniques',
    chapterNumber: 8,
    unitNumber: 8,
    unitName: 'Organic Chemistry: Some Basic Principles and Techniques',
    description: 'General introduction, methods of purification, qualitative and quantitative analysis, classification and IUPAC nomenclature of organic compounds. Electronic displacements in a covalent bond: inductive effect, electromeric effect, resonance and hyperconjugation. Homolytic and heterolytic fission of a covalent bond: free radicals, carbocations, carbanions, electrophiles and nucleophiles, types of organic reactions.',
    defaultEstimatedHours: 10,
    examWeightage: 'critical',
    difficulty: 'hard',
    prerequisites: ['chem-bonding'],
    inCbseSyllabus: true,
    topics: [
      { id: 'c11-c8-t1', name: 'IUPAC nomenclature of branched and functionalized organic molecules', inCbseSyllabus: true },
      { id: 'c11-c8-t2', name: 'Structural and stereoisomerism overview', inCbseSyllabus: true },
      { id: 'c11-c8-t3', name: 'Electronic effects: Inductive (+I/-I), Resonance (+R/-R), Hyperconjugation, Electromeric effect', inCbseSyllabus: true },
      { id: 'c11-c8-t4', name: 'Reaction intermediates: Carbocations, carbanions, free radicals stability and mechanism', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?kech2=2-5`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'chem-hydrocarbons',
    subjectId: 'cbse-11-chemistry',
    subjectName: 'Chemistry',
    subjectCode: '043',
    class: '11',
    academicSession: '2026-27',
    title: 'Hydrocarbons',
    chapterNumber: 9,
    unitNumber: 9,
    unitName: 'Hydrocarbons',
    description: 'Classification of Hydrocarbons. Alkanes - Nomenclature, isomerism, conformation (ethane only), physical properties, chemical reactions including free radical mechanism of halogenation, combustion and pyrolysis. Alkenes - Nomenclature, structure of double bond (ethene), geometrical isomerism, physical properties, methods of preparation, chemical reactions: addition of hydrogen, halogen, water, hydrogen halides (Markownikov addition and peroxide effect), ozonolysis, oxidation, mechanism of electrophilic addition. Alkynes - Nomenclature, structure of triple bond (ethyne), physical properties, methods of preparation, chemical reactions: acidic character of alkynes, addition reaction of - hydrogen, halogens, hydrogen halides and water. Aromatic Hydrocarbons: Introduction, IUPAC nomenclature, benzene: resonance, aromaticity, chemical properties: mechanism of electrophilic substitution. Nitration, sulphonation, halogenation, Friedel Craft alkylation and acylation, directive influence of functional group in mono-substituted benzene. Carcinogenicity and toxicity.',
    defaultEstimatedHours: 10,
    examWeightage: 'critical',
    difficulty: 'hard',
    prerequisites: ['chem-organic'],
    inCbseSyllabus: true,
    topics: [
      { id: 'c11-c9-t1', name: 'Alkanes: Wurtz reaction, free radical halogenation mechanism, conformations of ethane', inCbseSyllabus: true },
      { id: 'c11-c9-t2', name: 'Alkenes: Markovnikov rule, Anti-Markovnikov Kharasch peroxide effect, ozonolysis', inCbseSyllabus: true },
      { id: 'c11-c9-t3', name: 'Alkynes: Acidic nature of terminal alkynes and hydration to carbonyls', inCbseSyllabus: true },
      { id: 'c11-c9-t4', name: "Aromaticity (Huckel's 4n+2 pi rule), Benzene electrophilic aromatic substitution mechanisms (Nitration, Friedel-Crafts)", inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?kech2=3-5`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },

  // -------------------------------------------------------------------------
  // MATHEMATICS (041)
  // -------------------------------------------------------------------------
  {
    id: 'math-sets',
    subjectId: 'cbse-11-mathematics',
    subjectName: 'Mathematics',
    subjectCode: '041',
    class: '11',
    academicSession: '2026-27',
    title: 'Sets',
    chapterNumber: 1,
    unitNumber: 1,
    unitName: 'Sets and Functions',
    description: 'Sets and their representations, empty set, finite and infinite sets, equal sets, subsets, subsets of a set of real numbers, universal set, Venn diagrams, union and intersection of sets, difference of sets, complement of a set, properties of complement.',
    defaultEstimatedHours: 5,
    examWeightage: 'high',
    difficulty: 'easy',
    prerequisites: [],
    inCbseSyllabus: true,
    topics: [
      { id: 'c11-m1-t1', name: 'Representation of sets, subsets, and power set P(A)', inCbseSyllabus: true },
      { id: 'c11-m1-t2', name: 'Venn diagrams, operations on sets (union, intersection, difference, complement)', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?kemh1=1-14`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'math-relations',
    subjectId: 'cbse-11-mathematics',
    subjectName: 'Mathematics',
    subjectCode: '041',
    class: '11',
    academicSession: '2026-27',
    title: 'Relations and Functions',
    chapterNumber: 2,
    unitNumber: 1,
    unitName: 'Sets and Functions',
    description: 'Ordered pairs. Cartesian product of sets. Number of elements in the Cartesian product of two finite sets. Cartesian product of the set of reals with itself. Definition of relation, pictorial diagrams, domain, co-domain and range of a relation. Function as a special type of relation. Pictorial representation of a function, domain, co-domain and range of a function. Real valued functions, domain and range of these functions, constant, identity, polynomial, rational, modulus, signum, exponential, logarithmic and greatest integer functions, with their graphs. Sum, difference, product and quotients of functions.',
    defaultEstimatedHours: 7,
    examWeightage: 'critical',
    difficulty: 'medium',
    prerequisites: ['math-sets'],
    inCbseSyllabus: true,
    topics: [
      { id: 'c11-m2-t1', name: 'Cartesian product of sets and definition of relation', inCbseSyllabus: true },
      { id: 'c11-m2-t2', name: 'Function domain, range, standard graphs (modulus, signum, greatest integer [x])', inCbseSyllabus: true },
      { id: 'c11-m2-t3', name: 'Algebra of real functions (f + g, f - g, f * g, f / g)', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?kemh1=2-14`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'math-trig',
    subjectId: 'cbse-11-mathematics',
    subjectName: 'Mathematics',
    subjectCode: '041',
    class: '11',
    academicSession: '2026-27',
    title: 'Trigonometric Functions',
    chapterNumber: 3,
    unitNumber: 1,
    unitName: 'Sets and Functions',
    description: 'Positive and negative angles. Measuring angles in radians and in degrees and conversion from one measure to another. Definition of trigonometric functions with the help of unit circle. Truth of the identity sin^2 x + cos^2 x = 1, for all x. Signs of trigonometric functions. Domain and range of trigonometric functions and their graphs. Expressing sin (x+-y) and cos (x+-y) in terms of sin x, sin y, cos x & cos y and their simple applications. Identities related to sin 2x, cos 2x, tan 2x, sin 3x, cos 3x and tan 3x.',
    defaultEstimatedHours: 9,
    examWeightage: 'critical',
    difficulty: 'hard',
    prerequisites: ['c10-math-8'],
    inCbseSyllabus: true,
    topics: [
      { id: 'c11-m3-t1', name: 'Radian and degree conversion (pi rad = 180°), arc length l = r theta', inCbseSyllabus: true },
      { id: 'c11-m3-t2', name: 'Trigonometric functions on unit circle and quadrant ASTC rule', inCbseSyllabus: true },
      { id: 'c11-m3-t3', name: 'Compound angle formulas sin(x+-y), cos(x+-y), tan(x+-y)', inCbseSyllabus: true },
      { id: 'c11-m3-t4', name: 'Multiple angle formulas (sin 2x, cos 2x, tan 2x, sin 3x, cos 3x) and transformation formulas', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?kemh1=3-14`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'math-complex',
    subjectId: 'cbse-11-mathematics',
    subjectName: 'Mathematics',
    subjectCode: '041',
    class: '11',
    academicSession: '2026-27',
    title: 'Complex Numbers and Quadratic Equations',
    chapterNumber: 4,
    unitNumber: 2,
    unitName: 'Algebra',
    description: 'Need for complex numbers, especially sqrt(-1), to be motivated by inability to solve some of the quadratic equations. Algebraic properties of complex numbers. Argand plane. Statement of Fundamental Theorem of Algebra, solutions of quadratic equations (with real coefficients) in the complex number system.',
    defaultEstimatedHours: 6,
    examWeightage: 'high',
    difficulty: 'medium',
    prerequisites: ['c10-math-4'],
    inCbseSyllabus: true,
    topics: [
      { id: 'c11-m4-t1', name: 'Algebra of complex numbers z = a + ib, modulus |z| and conjugate z*', inCbseSyllabus: true },
      { id: 'c11-m4-t2', name: 'Argand plane representation and quadratic equations with negative discriminant', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?kemh1=4-14`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'math-inequalities',
    subjectId: 'cbse-11-mathematics',
    subjectName: 'Mathematics',
    subjectCode: '041',
    class: '11',
    academicSession: '2026-27',
    title: 'Linear Inequalities',
    chapterNumber: 5,
    unitNumber: 2,
    unitName: 'Algebra',
    description: 'Linear inequalities. Algebraic solutions of linear inequalities in one variable and their representation on the number line.',
    defaultEstimatedHours: 4,
    examWeightage: 'medium',
    difficulty: 'easy',
    prerequisites: ['math-sets'],
    inCbseSyllabus: true,
    topics: [
      { id: 'c11-m5-t1', name: 'Algebraic solutions of linear inequalities in one variable on number line', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?kemh1=5-14`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'math-permutations',
    subjectId: 'cbse-11-mathematics',
    subjectName: 'Mathematics',
    subjectCode: '041',
    class: '11',
    academicSession: '2026-27',
    title: 'Permutations and Combinations',
    chapterNumber: 6,
    unitNumber: 2,
    unitName: 'Algebra',
    description: 'Fundamental principle of counting. Factorial n. (n!). Permutations and combinations, derivation of Formulae for nPr and nCr and their connections, simple applications.',
    defaultEstimatedHours: 8,
    examWeightage: 'critical',
    difficulty: 'hard',
    prerequisites: [],
    inCbseSyllabus: true,
    topics: [
      { id: 'c11-m6-t1', name: 'Fundamental Principle of Counting (Multiplication & Addition rules)', inCbseSyllabus: true },
      { id: 'c11-m6-t2', name: 'Permutations nPr = n! / (n-r)! with and without repetition', inCbseSyllabus: true },
      { id: 'c11-m6-t3', name: 'Combinations nCr = n! / (r! (n-r)!) and combinatorial identities nCr = nC(n-r)', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?kemh1=6-14`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'math-binomial',
    subjectId: 'cbse-11-mathematics',
    subjectName: 'Mathematics',
    subjectCode: '041',
    class: '11',
    academicSession: '2026-27',
    title: 'Binomial Theorem',
    chapterNumber: 7,
    unitNumber: 2,
    unitName: 'Algebra',
    description: 'Historical perspective, statement and proof of the binomial theorem for positive integral indices. Pascal triangle, simple applications.',
    defaultEstimatedHours: 5,
    examWeightage: 'high',
    difficulty: 'medium',
    prerequisites: ['math-permutations'],
    inCbseSyllabus: true,
    topics: [
      { id: 'c11-m7-t1', name: 'Binomial Theorem for positive integer n: (a+b)^n = Sum nCr a^(n-r) b^r', inCbseSyllabus: true },
      { id: 'c11-m7-t2', name: 'General term T_(r+1) = nCr a^(n-r) b^r and applications', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?kemh1=7-14`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'math-sequences',
    subjectId: 'cbse-11-mathematics',
    subjectName: 'Mathematics',
    subjectCode: '041',
    class: '11',
    academicSession: '2026-27',
    title: 'Sequences and Series',
    chapterNumber: 8,
    unitNumber: 2,
    unitName: 'Algebra',
    description: 'Sequence and Series. Arithmetic Progression (A. P.). Arithmetic Mean (A.M.) Geometric Progression (G.P.), general term of a G.P., sum of n terms of a G.P., infinite G.P. and its sum, geometric mean (G.M.), relation between A.M. and G.M.',
    defaultEstimatedHours: 7,
    examWeightage: 'critical',
    difficulty: 'medium',
    prerequisites: ['c10-math-5'],
    inCbseSyllabus: true,
    topics: [
      { id: 'c11-m8-t1', name: 'Geometric Progression (G.P.): nth term an = a r^(n-1)', inCbseSyllabus: true },
      { id: 'c11-m8-t2', name: 'Sum of n terms Sn = a(r^n - 1)/(r - 1) and infinite G.P. sum S_inf = a / (1 - r)', inCbseSyllabus: true },
      { id: 'c11-m8-t3', name: 'Geometric Mean (G.M.) and relation A.M. >= G.M.', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?kemh1=8-14`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'math-straight',
    subjectId: 'cbse-11-mathematics',
    subjectName: 'Mathematics',
    subjectCode: '041',
    class: '11',
    academicSession: '2026-27',
    title: 'Straight Lines',
    chapterNumber: 9,
    unitNumber: 3,
    unitName: 'Coordinate Geometry',
    description: 'Brief recall of two dimensional geometry from earlier classes. Slope of a line and angle between two lines. Various forms of equations of a line: parallel to axis, point -slope form, slope-intercept form, two-point form, intercept form. Distance of a point from a line.',
    defaultEstimatedHours: 7,
    examWeightage: 'critical',
    difficulty: 'medium',
    prerequisites: ['c10-math-7'],
    inCbseSyllabus: true,
    topics: [
      { id: 'c11-m9-t1', name: 'Slope of line m = tan theta = (y2-y1)/(x2-x1) and angle between two lines', inCbseSyllabus: true },
      { id: 'c11-m9-t2', name: 'Forms of straight line: Point-slope, slope-intercept (y = mx + c), intercept (x/a + y/b = 1)', inCbseSyllabus: true },
      { id: 'c11-m9-t3', name: 'Perpendicular distance of point (x1, y1) from line Ax + By + C = 0: d = |Ax1 + By1 + C| / sqrt(A^2 + B^2)', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?kemh1=9-14`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'math-conic',
    subjectId: 'cbse-11-mathematics',
    subjectName: 'Mathematics',
    subjectCode: '041',
    class: '11',
    academicSession: '2026-27',
    title: 'Conic Sections',
    chapterNumber: 10,
    unitNumber: 3,
    unitName: 'Coordinate Geometry',
    description: 'Sections of a cone: circles, ellipse, parabola, hyperbola. Standard equations and simple properties of parabola, ellipse and hyperbola. Standard equation of a circle.',
    defaultEstimatedHours: 8,
    examWeightage: 'critical',
    difficulty: 'hard',
    prerequisites: ['math-straight'],
    inCbseSyllabus: true,
    topics: [
      { id: 'c11-m10-t1', name: 'Circle equation (x - h)^2 + (y - k)^2 = r^2', inCbseSyllabus: true },
      { id: 'c11-m10-t2', name: 'Parabola standard equations (y^2 = 4ax, x^2 = 4ay), focus, directrix, latus rectum', inCbseSyllabus: true },
      { id: 'c11-m10-t3', name: 'Ellipse standard equation x^2/a^2 + y^2/b^2 = 1, eccentricity e, foci', inCbseSyllabus: true },
      { id: 'c11-m10-t4', name: 'Hyperbola standard equation x^2/a^2 - y^2/b^2 = 1, transverse/conjugate axes', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?kemh1=10-14`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'math-3d',
    subjectId: 'cbse-11-mathematics',
    subjectName: 'Mathematics',
    subjectCode: '041',
    class: '11',
    academicSession: '2026-27',
    title: 'Introduction to Three-dimensional Geometry',
    chapterNumber: 11,
    unitNumber: 3,
    unitName: 'Coordinate Geometry',
    description: 'Coordinate axes and coordinate planes in three dimensions. Coordinates of a point. Distance between two points and section formula.',
    defaultEstimatedHours: 4,
    examWeightage: 'medium',
    difficulty: 'easy',
    prerequisites: ['c10-math-7'],
    inCbseSyllabus: true,
    topics: [
      { id: 'c11-m11-t1', name: '3D coordinate octants, distance formula d = sqrt((x2-x1)^2 + (y2-y1)^2 + (z2-z1)^2)', inCbseSyllabus: true },
      { id: 'c11-m11-t2', name: 'Section formula in 3D for internal/external division', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?kemh1=11-14`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'math-limits',
    subjectId: 'cbse-11-mathematics',
    subjectName: 'Mathematics',
    subjectCode: '041',
    class: '11',
    academicSession: '2026-27',
    title: 'Limits and Derivatives',
    chapterNumber: 12,
    unitNumber: 4,
    unitName: 'Calculus',
    description: 'Derivative introduced as rate of change both as that of distance and function. Intuitive idea of limit. Limits of polynomials and rational functions, trigonometric functions. Definition of derivative, relate it to scope of tangent of the curve, derivative of sum, difference, product and quotient of functions. Derivatives of polynomial and trigonometric functions.',
    defaultEstimatedHours: 9,
    examWeightage: 'critical',
    difficulty: 'hard',
    prerequisites: ['math-trig'],
    inCbseSyllabus: true,
    topics: [
      { id: 'c11-m12-t1', name: 'Limits: lim_(x->a) f(x), standard trigonometric limit lim_(x->0) (sin x / x) = 1', inCbseSyllabus: true },
      { id: 'c11-m12-t2', name: 'Derivative from first principles f’(x) = lim_(h->0) (f(x+h) - f(x))/h', inCbseSyllabus: true },
      { id: 'c11-m12-t3', name: 'Product rule (uv)’ = u’v + uv’ and Quotient rule (u/v)’ = (u’v - uv’) / v^2', inCbseSyllabus: true },
      { id: 'c11-m12-t4', name: 'Derivatives of x^n, sin x, cos x, tan x, sec x, cot x, cosec x', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?kemh1=12-14`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'math-stats',
    subjectId: 'cbse-11-mathematics',
    subjectName: 'Mathematics',
    subjectCode: '041',
    class: '11',
    academicSession: '2026-27',
    title: 'Statistics',
    chapterNumber: 13,
    unitNumber: 5,
    unitName: 'Statistics and Probability',
    description: 'Measures of Dispersion: Range, Mean deviation, variance and standard deviation of ungrouped/grouped data.',
    defaultEstimatedHours: 5,
    examWeightage: 'high',
    difficulty: 'medium',
    prerequisites: ['c10-math-13'],
    inCbseSyllabus: true,
    topics: [
      { id: 'c11-m13-t1', name: 'Mean deviation about mean and median', inCbseSyllabus: true },
      { id: 'c11-m13-t2', name: 'Variance sigma^2 and Standard Deviation sigma of grouped data', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?kemh1=13-14`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'math-probability',
    subjectId: 'cbse-11-mathematics',
    subjectName: 'Mathematics',
    subjectCode: '041',
    class: '11',
    academicSession: '2026-27',
    title: 'Probability',
    chapterNumber: 14,
    unitNumber: 5,
    unitName: 'Statistics and Probability',
    description: 'Events; occurrence of events, not, and and or events, exhaustive events, mutually exclusive events, Axiomatic (set theoretic) probability, connections with other theories of earlier classes. Probability of an event, probability of not, and and or events.',
    defaultEstimatedHours: 6,
    examWeightage: 'high',
    difficulty: 'medium',
    prerequisites: ['math-sets'],
    inCbseSyllabus: true,
    topics: [
      { id: 'c11-m14-t1', name: 'Sample space, mutually exclusive & exhaustive events', inCbseSyllabus: true },
      { id: 'c11-m14-t2', name: 'Axiomatic approach to probability P(A union B) = P(A) + P(B) - P(A intersection B)', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?kemh1=14-14`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },

  // -------------------------------------------------------------------------
  // BIOLOGY (044) - Sample Core Chapters
  // -------------------------------------------------------------------------
  {
    id: 'c11-bio-1',
    subjectId: 'cbse-11-biology',
    subjectName: 'Biology',
    subjectCode: '044',
    class: '11',
    academicSession: '2026-27',
    title: 'The Living World',
    chapterNumber: 1,
    unitNumber: 1,
    unitName: 'Diversity in the Living World',
    description: 'Biodiversity; Need for classification; three domains of life; taxonomy and systematics; concept of species and taxonomical hierarchy; binomial nomenclature.',
    defaultEstimatedHours: 4,
    examWeightage: 'medium',
    difficulty: 'easy',
    prerequisites: [],
    inCbseSyllabus: true,
    topics: [
      { id: 'c11-b1-t1', name: 'Binomial nomenclature rules and taxonomic hierarchy (Species to Kingdom)', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?kebo1=1-19`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'c11-bio-2',
    subjectId: 'cbse-11-biology',
    subjectName: 'Biology',
    subjectCode: '044',
    class: '11',
    academicSession: '2026-27',
    title: 'Biological Classification',
    chapterNumber: 2,
    unitNumber: 1,
    unitName: 'Diversity in the Living World',
    description: 'Five kingdom classification; salient features and classification of Monera, Protista and Fungi into major groups; Lichens, Viruses and Viroids.',
    defaultEstimatedHours: 6,
    examWeightage: 'high',
    difficulty: 'medium',
    prerequisites: ['c11-bio-1'],
    inCbseSyllabus: true,
    topics: [
      { id: 'c11-b2-t1', name: 'Whittaker Five Kingdom system: Monera, Protista, Fungi features and reproduction', inCbseSyllabus: true },
      { id: 'c11-b2-t2', name: 'Viruses, Viroids, Prions, and Lichens', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?kebo1=2-19`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'c11-bio-8',
    subjectId: 'cbse-11-biology',
    subjectName: 'Biology',
    subjectCode: '044',
    class: '11',
    academicSession: '2026-27',
    title: 'Cell: The Unit of Life',
    chapterNumber: 8,
    unitNumber: 3,
    unitName: 'Cell: Structure and Function',
    description: 'Cell theory and cell as the basic unit of life, structure of prokaryotic and eukaryotic cells; Plant cell and animal cell; cell envelope; cell membrane, cell wall; cell organelles - structure and function.',
    defaultEstimatedHours: 7,
    examWeightage: 'critical',
    difficulty: 'medium',
    prerequisites: ['c9-sci-5'],
    inCbseSyllabus: true,
    topics: [
      { id: 'c11-b8-t1', name: 'Fluid mosaic model of plasma membrane and endomembrane system', inCbseSyllabus: true },
      { id: 'c11-b8-t2', name: 'Mitochondria, chloroplasts, ribosomes, nucleus and chromosome structure', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?kebo1=8-19`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'c11-bio-9',
    subjectId: 'cbse-11-biology',
    subjectName: 'Biology',
    subjectCode: '044',
    class: '11',
    academicSession: '2026-27',
    title: 'Biomolecules',
    chapterNumber: 9,
    unitNumber: 3,
    unitName: 'Cell: Structure and Function',
    description: 'Chemical constituents of living cells: biomolecules, structure and function of proteins, carbohydrates, lipids, nucleic acids; Enzyme - types, properties, enzyme action.',
    defaultEstimatedHours: 7,
    examWeightage: 'critical',
    difficulty: 'hard',
    prerequisites: ['c11-bio-8', 'chem-basic'],
    inCbseSyllabus: true,
    topics: [
      { id: 'c11-b9-t1', name: 'Carbohydrates, lipids, proteins (primary/secondary/tertiary structures)', inCbseSyllabus: true },
      { id: 'c11-b9-t2', name: 'Enzyme catalysis, Michaelis-Menten kinetics, activation energy, enzyme inhibition', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?kebo1=9-19`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },

  // -------------------------------------------------------------------------
  // COMPUTER SCIENCE (083) - Python
  // -------------------------------------------------------------------------
  {
    id: 'c11-cs-1',
    subjectId: 'cbse-11-cs',
    subjectName: 'Computer Science',
    subjectCode: '083',
    class: '11',
    academicSession: '2026-27',
    title: 'Computer Systems and Organisation',
    chapterNumber: 1,
    unitNumber: 1,
    unitName: 'Computer Systems and Organisation',
    description: 'Basic computer organisation: CPU, memory, hard disk, I/O devices, types of software, memory units, Boolean logic, number systems.',
    defaultEstimatedHours: 5,
    examWeightage: 'high',
    difficulty: 'easy',
    prerequisites: [],
    inCbseSyllabus: true,
    topics: [
      { id: 'c11-cs1-t1', name: 'Binary, Octal, Decimal, Hexadecimal number conversions', inCbseSyllabus: true },
      { id: 'c11-cs1-t2', name: 'Boolean gates (AND, OR, NOT, NAND, NOR, XOR) and truth tables', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?kecs1=1-11`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'c11-cs-2',
    subjectId: 'cbse-11-cs',
    subjectName: 'Computer Science',
    subjectCode: '083',
    class: '11',
    academicSession: '2026-27',
    title: 'Computational Thinking and Programming - Python Basics',
    chapterNumber: 2,
    unitNumber: 2,
    unitName: 'Computational Thinking and Programming - 1',
    description: 'Introduction to Python, interactive and script mode, identifiers, keywords, data types, mutable and immutable, operators, conditionals and loops.',
    defaultEstimatedHours: 8,
    examWeightage: 'critical',
    difficulty: 'medium',
    prerequisites: ['c11-cs-1'],
    inCbseSyllabus: true,
    topics: [
      { id: 'c11-cs2-t1', name: 'Python data types (int, float, bool, str, list, tuple, dict)', inCbseSyllabus: true },
      { id: 'c11-cs2-t2', name: 'Control structures: if-elif-else, for loops, while loops, range()', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?kecs1=2-11`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'c11-cs-3',
    subjectId: 'cbse-11-cs',
    subjectName: 'Computer Science',
    subjectCode: '083',
    class: '11',
    academicSession: '2026-27',
    title: 'Strings, Lists, Tuples, and Dictionaries in Python',
    chapterNumber: 3,
    unitNumber: 2,
    unitName: 'Computational Thinking and Programming - 1',
    description: 'String operations and methods, List indexing, slicing, methods, Tuple creation and immutability, Dictionary key-value pairs and operations.',
    defaultEstimatedHours: 9,
    examWeightage: 'critical',
    difficulty: 'medium',
    prerequisites: ['c11-cs-2'],
    inCbseSyllabus: true,
    topics: [
      { id: 'c11-cs3-t1', name: 'String slicing, traversing, built-in string functions', inCbseSyllabus: true },
      { id: 'c11-cs3-t2', name: 'List methods: append, extend, insert, pop, remove, sort', inCbseSyllabus: true },
      { id: 'c11-cs3-t3', name: 'Dictionary traversal, keys(), values(), items() methods', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?kecs1=3-11`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },

  // -------------------------------------------------------------------------
  // COMMERCE - ACCOUNTANCY (055) & BUSINESS STUDIES (054)
  // -------------------------------------------------------------------------
  {
    id: 'c11-acc-1',
    subjectId: 'cbse-11-accountancy',
    subjectName: 'Accountancy',
    subjectCode: '055',
    class: '11',
    academicSession: '2026-27',
    title: 'Introduction to Accounting',
    chapterNumber: 1,
    unitNumber: 1,
    unitName: 'Theoretical Framework',
    description: 'Accounting- concept, meaning, as a source of information, objectives, advantages and limitations, types of accounting information; users of accounting information and their needs. Qualitative characteristics of accounting information. Role of accounting in business.',
    defaultEstimatedHours: 5,
    examWeightage: 'high',
    difficulty: 'easy',
    prerequisites: [],
    inCbseSyllabus: true,
    topics: [
      { id: 'c11-a1-t1', name: 'Objectives, users, basic accounting terms (Assets, Liabilities, Capital, Revenue)', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?keac1=1-8`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'c11-acc-2',
    subjectId: 'cbse-11-accountancy',
    subjectName: 'Accountancy',
    subjectCode: '055',
    class: '11',
    academicSession: '2026-27',
    title: 'Theory Base of Accounting and Accounting Standards',
    chapterNumber: 2,
    unitNumber: 1,
    unitName: 'Theoretical Framework',
    description: 'Fundamental accounting assumptions: GAAP, Business Entity, Money Measurement, Going Concern, Accounting Period, Cost Concept, Dual Aspect, Revenue Recognition, Matching, Full Disclosure, Consistency, Conservatism, Materiality.',
    defaultEstimatedHours: 6,
    examWeightage: 'high',
    difficulty: 'medium',
    prerequisites: ['c11-acc-1'],
    inCbseSyllabus: true,
    topics: [
      { id: 'c11-a2-t1', name: 'GAAP principles (Dual aspect, Conservatism, Matching, Revenue recognition)', inCbseSyllabus: true },
      { id: 'c11-a2-t2', name: 'GST accounting concepts and accounting standards overview', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?keac1=2-8`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'c11-acc-3',
    subjectId: 'cbse-11-accountancy',
    subjectName: 'Accountancy',
    subjectCode: '055',
    class: '11',
    academicSession: '2026-27',
    title: 'Recording of Business Transactions - Journal & Ledger',
    chapterNumber: 3,
    unitNumber: 2,
    unitName: 'Accounting Process',
    description: 'Accounting Equation: Assets = Liabilities + Capital. Rules of debit and credit. Origin of transactions- source documents/Voucher. Books of Original Entry- Journal, Cash Book, Purchases Book, Sales Book, Ledger posting.',
    defaultEstimatedHours: 9,
    examWeightage: 'critical',
    difficulty: 'hard',
    prerequisites: ['c11-acc-2'],
    inCbseSyllabus: true,
    topics: [
      { id: 'c11-a3-t1', name: 'Accounting Equation A = L + C numericals', inCbseSyllabus: true },
      { id: 'c11-a3-t2', name: 'Journal entries with GST (Input CGST/SGST/IGST and Output GST)', inCbseSyllabus: true },
      { id: 'c11-a3-t3', name: 'Cash book (two column with bank) and subsidiary books', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?keac1=3-8`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'c11-bst-1',
    subjectId: 'cbse-11-bst',
    subjectName: 'Business Studies',
    subjectCode: '054',
    class: '11',
    academicSession: '2026-27',
    title: 'Nature and Purpose of Business',
    chapterNumber: 1,
    unitNumber: 1,
    unitName: 'Foundations of Business',
    description: 'Concept of business, characteristics of business, comparison of business, profession and employment, classification of business activities - Industry and Commerce, business risk.',
    defaultEstimatedHours: 5,
    examWeightage: 'high',
    difficulty: 'easy',
    prerequisites: [],
    inCbseSyllabus: true,
    topics: [
      { id: 'c11-bs1-t1', name: 'Business vs Profession vs Employment, Primary/Secondary/Tertiary industry', inCbseSyllabus: true },
      { id: 'c11-bs1-t2', name: 'Business risk: Nature and causes', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?kest1=1-11`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'c11-bst-2',
    subjectId: 'cbse-11-bst',
    subjectName: 'Business Studies',
    subjectCode: '054',
    class: '11',
    academicSession: '2026-27',
    title: 'Forms of Business Organisations',
    chapterNumber: 2,
    unitNumber: 1,
    unitName: 'Foundations of Business',
    description: 'Sole Proprietorship, Joint Hindu Family Business, Partnership, Cooperative Societies, Joint Stock Company - concepts, merits, and limitations.',
    defaultEstimatedHours: 7,
    examWeightage: 'critical',
    difficulty: 'medium',
    prerequisites: ['c11-bst-1'],
    inCbseSyllabus: true,
    topics: [
      { id: 'c11-bs2-t1', name: 'Sole proprietorship, Partnership Act 1932, and types of partners', inCbseSyllabus: true },
      { id: 'c11-bs2-t2', name: 'Joint stock company: Private vs Public company comparison', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?kest1=2-11`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },

  // -------------------------------------------------------------------------
  // HUMANITIES - HISTORY (027) & POLITICAL SCIENCE (028)
  // -------------------------------------------------------------------------
  {
    id: 'c11-hist-1',
    subjectId: 'cbse-11-history',
    subjectName: 'History',
    subjectCode: '027',
    class: '11',
    academicSession: '2026-27',
    title: 'Writing and City Life (Mesopotamia)',
    chapterNumber: 1,
    unitNumber: 1,
    unitName: 'Early Societies',
    description: 'Mesopotamia geography, growth of cities, development of writing, temples and trade, urbanization in southern Mesopotamia.',
    defaultEstimatedHours: 6,
    examWeightage: 'high',
    difficulty: 'medium',
    prerequisites: [],
    inCbseSyllabus: true,
    topics: [
      { id: 'c11-h1-t1', name: 'Mesopotamian cuneiform script, tablet writing, and temple economy in Uruk', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?kehs1=1-7`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'c11-pol-1',
    subjectId: 'cbse-11-polsci',
    subjectName: 'Political Science',
    subjectCode: '028',
    class: '11',
    academicSession: '2026-27',
    title: 'Constitution: Why and How?',
    chapterNumber: 1,
    unitNumber: 1,
    unitName: 'Indian Constitution at Work',
    description: 'Why do we need a Constitution? What does a constitution do? Who made the Indian constitution? Philosophy of the constitution.',
    defaultEstimatedHours: 6,
    examWeightage: 'critical',
    difficulty: 'medium',
    prerequisites: [],
    inCbseSyllabus: true,
    topics: [
      { id: 'c11-p1-t1', name: 'Functions of a Constitution, constituent assembly legitimacy, borrowed provisions', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?keps1=1-8`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
];
