import { type CurriculumChapter } from './types';
import { OFFICIAL_CBSE_SYLLABUS_PORTAL, OFFICIAL_NCERT_PORTAL, OFFICIAL_CBSE_SKILL_PORTAL } from './cbse-2027-database';

export const CLASS_10_CHAPTERS: CurriculumChapter[] = [
  // Mathematics (041 / 241)
  {
    id: 'c10-math-1',
    subjectId: 'cbse-10-math',
    subjectName: 'Mathematics',
    subjectCode: '041',
    class: '10',
    academicSession: '2026-27',
    title: 'Real Numbers',
    chapterNumber: 1,
    unitNumber: 1,
    unitName: 'Number Systems',
    description: 'Fundamental Theorem of Arithmetic, statements after reviewing work done earlier and after illustrating and motivating through examples, proofs of irrationality of sqrt(2), sqrt(3), sqrt(5).',
    defaultEstimatedHours: 5,
    examWeightage: 'high',
    difficulty: 'easy',
    prerequisites: ['c9-math-1'],
    inCbseSyllabus: true,
    topics: [
      { id: 'c10-m1-t1', name: 'Fundamental Theorem of Arithmetic (HCF & LCM product theorem)', inCbseSyllabus: true },
      { id: 'c10-m1-t2', name: 'Proofs of irrationality of √2, √3, √5 by contradiction', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?jemh1=1-14`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'c10-math-2',
    subjectId: 'cbse-10-math',
    subjectName: 'Mathematics',
    subjectCode: '041',
    class: '10',
    academicSession: '2026-27',
    title: 'Polynomials',
    chapterNumber: 2,
    unitNumber: 2,
    unitName: 'Algebra',
    description: 'Zeros of a polynomial. Relationship between zeros and coefficients of quadratic polynomials.',
    defaultEstimatedHours: 5,
    examWeightage: 'high',
    difficulty: 'medium',
    prerequisites: ['c9-math-2'],
    inCbseSyllabus: true,
    topics: [
      { id: 'c10-m2-t1', name: 'Geometrical meaning of zeroes of a polynomial', inCbseSyllabus: true },
      { id: 'c10-m2-t2', name: 'Relationship between zeroes and coefficients (alpha + beta = -b/a, alpha * beta = c/a)', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?jemh1=2-14`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'c10-math-3',
    subjectId: 'cbse-10-math',
    subjectName: 'Mathematics',
    subjectCode: '041',
    class: '10',
    academicSession: '2026-27',
    title: 'Pair of Linear Equations in Two Variables',
    chapterNumber: 3,
    unitNumber: 2,
    unitName: 'Algebra',
    description: 'Graphical method of solution, consistency/inconsistency. Algebraic conditions for number of solutions. Solution by substitution and elimination.',
    defaultEstimatedHours: 7,
    examWeightage: 'critical',
    difficulty: 'medium',
    prerequisites: ['c9-math-4'],
    inCbseSyllabus: true,
    topics: [
      { id: 'c10-m3-t1', name: 'Graphical method and consistency ratios a1/a2, b1/b2, c1/c2', inCbseSyllabus: true },
      { id: 'c10-m3-t2', name: 'Substitution method and Elimination method', inCbseSyllabus: true },
      { id: 'c10-m3-t3', name: 'Word problems on speeds, ages, fractions, and upstream/downstream', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?jemh1=3-14`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'c10-math-4',
    subjectId: 'cbse-10-math',
    subjectName: 'Mathematics',
    subjectCode: '041',
    class: '10',
    academicSession: '2026-27',
    title: 'Quadratic Equations',
    chapterNumber: 4,
    unitNumber: 2,
    unitName: 'Algebra',
    description: 'Standard form ax^2 + bx + c = 0. Solutions by factorisation and by using quadratic formula. Relationship between discriminant and nature of roots.',
    defaultEstimatedHours: 7,
    examWeightage: 'critical',
    difficulty: 'medium',
    prerequisites: ['c10-math-2'],
    inCbseSyllabus: true,
    topics: [
      { id: 'c10-m4-t1', name: 'Factorisation of quadratic expressions', inCbseSyllabus: true },
      { id: 'c10-m4-t2', name: 'Quadratic formula x = (-b +- sqrt(b^2 - 4ac)) / (2a)', inCbseSyllabus: true },
      { id: 'c10-m4-t3', name: 'Discriminant D = b^2 - 4ac and nature of real/equal/distinct roots', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?jemh1=4-14`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'c10-math-5',
    subjectId: 'cbse-10-math',
    subjectName: 'Mathematics',
    subjectCode: '041',
    class: '10',
    academicSession: '2026-27',
    title: 'Arithmetic Progressions',
    chapterNumber: 5,
    unitNumber: 2,
    unitName: 'Algebra',
    description: 'Motivation for studying Arithmetic Progression, derivation of nth term and sum of first n terms of A.P. Application in solving daily life problems.',
    defaultEstimatedHours: 6,
    examWeightage: 'high',
    difficulty: 'medium',
    prerequisites: [],
    inCbseSyllabus: true,
    topics: [
      { id: 'c10-m5-t1', name: 'nth term formula an = a + (n-1)d', inCbseSyllabus: true },
      { id: 'c10-m5-t2', name: 'Sum of n terms Sn = n/2 [2a + (n-1)d] = n/2 (a + l)', inCbseSyllabus: true },
      { id: 'c10-m5-t3', name: 'Real-life case study questions on savings and stairs', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?jemh1=5-14`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'c10-math-6',
    subjectId: 'cbse-10-math',
    subjectName: 'Mathematics',
    subjectCode: '041',
    class: '10',
    academicSession: '2026-27',
    title: 'Triangles',
    chapterNumber: 6,
    unitNumber: 4,
    unitName: 'Geometry',
    description: 'Definitions, examples, counter examples of similar triangles. Proof of Basic Proportionality Theorem (Thales theorem). Similarity criteria AAA, SAS, SSS.',
    defaultEstimatedHours: 9,
    examWeightage: 'critical',
    difficulty: 'hard',
    prerequisites: ['c9-math-7'],
    inCbseSyllabus: true,
    topics: [
      { id: 'c10-m6-t1', name: 'Basic Proportionality Theorem (BPT) proof and converse', inCbseSyllabus: true },
      { id: 'c10-m6-t2', name: 'Similarity criteria: AAA, SAS, SSS theorems and proofs', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?jemh1=6-14`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'c10-math-7',
    subjectId: 'cbse-10-math',
    subjectName: 'Mathematics',
    subjectCode: '041',
    class: '10',
    academicSession: '2026-27',
    title: 'Coordinate Geometry',
    chapterNumber: 7,
    unitNumber: 3,
    unitName: 'Coordinate Geometry',
    description: 'Concepts of coordinate geometry, graphs of linear equations. Distance formula. Section formula (internal division).',
    defaultEstimatedHours: 6,
    examWeightage: 'high',
    difficulty: 'easy',
    prerequisites: ['c9-math-3'],
    inCbseSyllabus: true,
    topics: [
      { id: 'c10-m7-t1', name: 'Distance formula between two points d = sqrt((x2-x1)^2 + (y2-y1)^2)', inCbseSyllabus: true },
      { id: 'c10-m7-t2', name: 'Section formula (mx2 + nx1)/(m+n), (my2 + ny1)/(m+n) & midpoint formula', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?jemh1=7-14`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'c10-math-8',
    subjectId: 'cbse-10-math',
    subjectName: 'Mathematics',
    subjectCode: '041',
    class: '10',
    academicSession: '2026-27',
    title: 'Introduction to Trigonometry',
    chapterNumber: 8,
    unitNumber: 5,
    unitName: 'Trigonometry',
    description: 'Trigonometric ratios of an acute angle of a right-angled triangle. Values at 0, 30, 45, 60, 90 degrees. Trigonometric identity sin^2 theta + cos^2 theta = 1.',
    defaultEstimatedHours: 8,
    examWeightage: 'critical',
    difficulty: 'hard',
    prerequisites: ['c10-math-6'],
    inCbseSyllabus: true,
    topics: [
      { id: 'c10-m8-t1', name: 'Trig ratios: sin, cos, tan, cot, sec, cosec definitions in right triangle', inCbseSyllabus: true },
      { id: 'c10-m8-t2', name: 'Standard angle table (0°, 30°, 45°, 60°, 90°)', inCbseSyllabus: true },
      { id: 'c10-m8-t3', name: 'Proving identities using sin^2 theta + cos^2 theta = 1, 1 + tan^2 = sec^2, 1 + cot^2 = cosec^2', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?jemh1=8-14`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'c10-math-9',
    subjectId: 'cbse-10-math',
    subjectName: 'Mathematics',
    subjectCode: '041',
    class: '10',
    academicSession: '2026-27',
    title: 'Some Applications of Trigonometry (Heights and Distances)',
    chapterNumber: 9,
    unitNumber: 5,
    unitName: 'Trigonometry',
    description: 'Simple problems on heights and distances. Angles of elevation / depression should be only 30, 45, 60 degrees.',
    defaultEstimatedHours: 6,
    examWeightage: 'high',
    difficulty: 'medium',
    prerequisites: ['c10-math-8'],
    inCbseSyllabus: true,
    topics: [
      { id: 'c10-m9-t1', name: 'Angle of elevation and angle of depression modeling', inCbseSyllabus: true },
      { id: 'c10-m9-t2', name: 'Two right triangles height and distance problems', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?jemh1=9-14`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'c10-math-10',
    subjectId: 'cbse-10-math',
    subjectName: 'Mathematics',
    subjectCode: '041',
    class: '10',
    academicSession: '2026-27',
    title: 'Circles',
    chapterNumber: 10,
    unitNumber: 4,
    unitName: 'Geometry',
    description: 'Tangent to a circle at point of contact: tangent is perpendicular to radius through point of contact. Lengths of tangents drawn from external point are equal.',
    defaultEstimatedHours: 6,
    examWeightage: 'high',
    difficulty: 'medium',
    prerequisites: ['c9-math-9'],
    inCbseSyllabus: true,
    topics: [
      { id: 'c10-m10-t1', name: 'Theorem: Radius is perpendicular to tangent at point of contact', inCbseSyllabus: true },
      { id: 'c10-m10-t2', name: 'Theorem: Lengths of tangents from an external point are equal', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?jemh1=10-14`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'c10-math-11',
    subjectId: 'cbse-10-math',
    subjectName: 'Mathematics',
    subjectCode: '041',
    class: '10',
    academicSession: '2026-27',
    title: 'Areas Related to Circles',
    chapterNumber: 11,
    unitNumber: 6,
    unitName: 'Mensuration',
    description: 'Area of sectors and segments of a circle. Problems based on areas and perimeter / circumference of sectors with central angles 60, 90, 120 degrees.',
    defaultEstimatedHours: 5,
    examWeightage: 'medium',
    difficulty: 'medium',
    prerequisites: ['c10-math-10'],
    inCbseSyllabus: true,
    topics: [
      { id: 'c10-m11-t1', name: 'Area of sector theta/360 * pi*r^2 and length of arc theta/360 * 2*pi*r', inCbseSyllabus: true },
      { id: 'c10-m11-t2', name: 'Area of major/minor segments of circle', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?jemh1=11-14`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'c10-math-12',
    subjectId: 'cbse-10-math',
    subjectName: 'Mathematics',
    subjectCode: '041',
    class: '10',
    academicSession: '2026-27',
    title: 'Surface Areas and Volumes',
    chapterNumber: 12,
    unitNumber: 6,
    unitName: 'Mensuration',
    description: 'Surface areas and volumes of combinations of any two: cubes, cuboids, spheres, hemispheres and right circular cylinders/cones.',
    defaultEstimatedHours: 7,
    examWeightage: 'critical',
    difficulty: 'hard',
    prerequisites: ['c9-math-11'],
    inCbseSyllabus: true,
    topics: [
      { id: 'c10-m12-t1', name: 'Surface area of combination of solids', inCbseSyllabus: true },
      { id: 'c10-m12-t2', name: 'Volume of combination of solids and melting/recasting problems', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?jemh1=12-14`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'c10-math-13',
    subjectId: 'cbse-10-math',
    subjectName: 'Mathematics',
    subjectCode: '041',
    class: '10',
    academicSession: '2026-27',
    title: 'Statistics',
    chapterNumber: 13,
    unitNumber: 7,
    unitName: 'Statistics & Probability',
    description: 'Mean, median and mode of grouped data (bimodal situation avoided). Mean by direct and assumed mean method.',
    defaultEstimatedHours: 6,
    examWeightage: 'high',
    difficulty: 'medium',
    prerequisites: ['c9-math-12'],
    inCbseSyllabus: true,
    topics: [
      { id: 'c10-m13-t1', name: 'Mean of grouped data (Direct method & Assumed mean method)', inCbseSyllabus: true },
      { id: 'c10-m13-t2', name: 'Mode of grouped data formula l + (f1-f0)/(2f1-f0-f2) * h', inCbseSyllabus: true },
      { id: 'c10-m13-t3', name: 'Median of grouped data formula l + (n/2 - cf)/f * h & empirical relationship', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?jemh1=13-14`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'c10-math-14',
    subjectId: 'cbse-10-math',
    subjectName: 'Mathematics',
    subjectCode: '041',
    class: '10',
    academicSession: '2026-27',
    title: 'Probability',
    chapterNumber: 14,
    unitNumber: 7,
    unitName: 'Statistics & Probability',
    description: 'Classical definition of probability. Simple problems on finding the probability of an event.',
    defaultEstimatedHours: 4,
    examWeightage: 'medium',
    difficulty: 'easy',
    prerequisites: [],
    inCbseSyllabus: true,
    topics: [
      { id: 'c10-m14-t1', name: 'P(E) = Number of favourable outcomes / Total outcomes', inCbseSyllabus: true },
      { id: 'c10-m14-t2', name: 'Cards, dice, coins, and complementary events P(E) + P(not E) = 1', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?jemh1=14-14`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },

  // Science (086)
  {
    id: 'c10-sci-1',
    subjectId: 'cbse-10-science',
    subjectName: 'Science',
    subjectCode: '086',
    class: '10',
    academicSession: '2026-27',
    title: 'Chemical Reactions and Equations',
    chapterNumber: 1,
    unitNumber: 1,
    unitName: 'Chemical Substances - Nature and Behaviour',
    description: 'Chemical equation, Balanced chemical equation, implications of a balanced chemical equation, types of chemical reactions: combination, decomposition, displacement, double displacement, precipitation, neutralization, oxidation and reduction.',
    defaultEstimatedHours: 6,
    examWeightage: 'high',
    difficulty: 'medium',
    prerequisites: ['c9-sci-3'],
    inCbseSyllabus: true,
    topics: [
      { id: 'c10-s1-t1', name: 'Balancing chemical equations', inCbseSyllabus: true },
      { id: 'c10-s1-t2', name: 'Types: Combination, decomposition (thermal, electrolytic, photolytic)', inCbseSyllabus: true },
      { id: 'c10-s1-t3', name: 'Displacement, double displacement precipitation & redox (oxidation-reduction)', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?jesc1=1-13`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'c10-sci-2',
    subjectId: 'cbse-10-science',
    subjectName: 'Science',
    subjectCode: '086',
    class: '10',
    academicSession: '2026-27',
    title: 'Acids, Bases and Salts',
    chapterNumber: 2,
    unitNumber: 1,
    unitName: 'Chemical Substances - Nature and Behaviour',
    description: 'Their definitions in terms of furnishing of H+ and OH- ions, General properties, examples and uses, neutralization, concept of pH scale, preparation and uses of Sodium Hydroxide, Bleaching powder, Baking soda, Washing soda and Plaster of Paris.',
    defaultEstimatedHours: 7,
    examWeightage: 'critical',
    difficulty: 'medium',
    prerequisites: ['c10-sci-1'],
    inCbseSyllabus: true,
    topics: [
      { id: 'c10-s2-t1', name: 'Chemical properties of acids and bases with metals, carbonates, hydroxides', inCbseSyllabus: true },
      { id: 'c10-s2-t2', name: 'Importance of pH in everyday life (digestion, tooth decay, soil)', inCbseSyllabus: true },
      { id: 'c10-s2-t3', name: 'Chemicals from common salt: NaOH, Bleaching powder, Baking soda, Washing soda, POP', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?jesc1=2-13`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'c10-sci-3',
    subjectId: 'cbse-10-science',
    subjectName: 'Science',
    subjectCode: '086',
    class: '10',
    academicSession: '2026-27',
    title: 'Metals and Non-metals',
    chapterNumber: 3,
    unitNumber: 1,
    unitName: 'Chemical Substances - Nature and Behaviour',
    description: 'Properties of metals and non-metals; Reactivity series; Formation and properties of ionic compounds; Basic metallurgical processes; Corrosion and its prevention.',
    defaultEstimatedHours: 7,
    examWeightage: 'critical',
    difficulty: 'medium',
    prerequisites: ['c10-sci-1'],
    inCbseSyllabus: true,
    topics: [
      { id: 'c10-s3-t1', name: 'Reactivity series and reaction of metals with water, acids, and salt solutions', inCbseSyllabus: true },
      { id: 'c10-s3-t2', name: 'Ionic compounds: electron dot structures, high melting point, conductivity', inCbseSyllabus: true },
      { id: 'c10-s3-t3', name: 'Metallurgy: Roasting, calcination, electrolytic refining, and rust prevention', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?jesc1=3-13`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'c10-sci-4',
    subjectId: 'cbse-10-science',
    subjectName: 'Science',
    subjectCode: '086',
    class: '10',
    academicSession: '2026-27',
    title: 'Carbon and its Compounds',
    chapterNumber: 4,
    unitNumber: 1,
    unitName: 'Chemical Substances - Nature and Behaviour',
    description: 'Covalent bonding in carbon compounds. Versatile nature of carbon. Homologous series. Nomenclature. Chemical properties. Ethanol and Ethanoic acid. Soaps and detergents.',
    defaultEstimatedHours: 8,
    examWeightage: 'critical',
    difficulty: 'hard',
    prerequisites: ['c10-sci-1'],
    inCbseSyllabus: true,
    topics: [
      { id: 'c10-s4-t1', name: 'Tetravalency and catenation, covalent bonding in CH4, CO2, H2O', inCbseSyllabus: true },
      { id: 'c10-s4-t2', name: 'Homologous series, functional groups, and IUPAC nomenclature', inCbseSyllabus: true },
      { id: 'c10-s4-t3', name: 'Combustion, oxidation, addition, substitution reactions of carbon', inCbseSyllabus: true },
      { id: 'c10-s4-t4', name: 'Ethanol, Ethanoic acid reactions and saponification micelle action', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?jesc1=4-13`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'c10-sci-5',
    subjectId: 'cbse-10-science',
    subjectName: 'Science',
    subjectCode: '086',
    class: '10',
    academicSession: '2026-27',
    title: 'Life Processes',
    chapterNumber: 5,
    unitNumber: 2,
    unitName: 'World of Living (Biology)',
    description: 'Basic concept of nutrition, respiration, transport and excretion in plants and animals.',
    defaultEstimatedHours: 9,
    examWeightage: 'critical',
    difficulty: 'hard',
    prerequisites: ['c9-sci-5'],
    inCbseSyllabus: true,
    topics: [
      { id: 'c10-s5-t1', name: 'Autotrophic and heterotrophic nutrition, human digestive system', inCbseSyllabus: true },
      { id: 'c10-s5-t2', name: 'Aerobic vs anaerobic respiration, human respiratory system', inCbseSyllabus: true },
      { id: 'c10-s5-t3', name: 'Double circulation in humans, xylem and phloem transport in plants', inCbseSyllabus: true },
      { id: 'c10-s5-t4', name: 'Structure of nephron, urine formation, and plant excretion', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?jesc1=5-13`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'c10-sci-6',
    subjectId: 'cbse-10-science',
    subjectName: 'Science',
    subjectCode: '086',
    class: '10',
    academicSession: '2026-27',
    title: 'Control and Coordination',
    chapterNumber: 6,
    unitNumber: 2,
    unitName: 'World of Living (Biology)',
    description: 'Tropic movements in plants; Introduction of plant hormones; Control and co-ordination in animals: Nervous system; Voluntary, involuntary and reflex action; Chemical co-ordination: animal hormones.',
    defaultEstimatedHours: 7,
    examWeightage: 'high',
    difficulty: 'medium',
    prerequisites: ['c10-sci-5'],
    inCbseSyllabus: true,
    topics: [
      { id: 'c10-s6-t1', name: 'Neuron, reflex arc, human brain (forebrain, midbrain, hindbrain)', inCbseSyllabus: true },
      { id: 'c10-s6-t2', name: 'Plant hormones (auxin, gibberellin, cytokinin, abscisic acid) & tropisms', inCbseSyllabus: true },
      { id: 'c10-s6-t3', name: 'Endocrine glands in humans: Pituitary, Thyroid, Adrenal, Pancreas, Testis, Ovary', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?jesc1=6-13`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'c10-sci-7',
    subjectId: 'cbse-10-science',
    subjectName: 'Science',
    subjectCode: '086',
    class: '10',
    academicSession: '2026-27',
    title: 'How do Organisms Reproduce?',
    chapterNumber: 7,
    unitNumber: 2,
    unitName: 'World of Living (Biology)',
    description: 'Reproduction in animals and plants (asexual and sexual) reproductive health - need and methods of family planning. Safe sex vs HIV/AIDS. Child bearing and women health.',
    defaultEstimatedHours: 7,
    examWeightage: 'critical',
    difficulty: 'medium',
    prerequisites: ['c9-sci-5'],
    inCbseSyllabus: true,
    topics: [
      { id: 'c10-s7-t1', name: 'Asexual reproduction modes: Fission, fragmentation, regeneration, budding, vegetative, spores', inCbseSyllabus: true },
      { id: 'c10-s7-t2', name: 'Sexual reproduction in flowering plants (pollination and fertilization)', inCbseSyllabus: true },
      { id: 'c10-s7-t3', name: 'Human male and female reproductive systems and menstrual cycle', inCbseSyllabus: true },
      { id: 'c10-s7-t4', name: 'Reproductive health and contraceptive barrier/chemical/surgical methods', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?jesc1=7-13`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'c10-sci-8',
    subjectId: 'cbse-10-science',
    subjectName: 'Science',
    subjectCode: '086',
    class: '10',
    academicSession: '2026-27',
    title: 'Heredity',
    chapterNumber: 8,
    unitNumber: 2,
    unitName: 'World of Living (Biology)',
    description: 'Heredity; Mendel contribution - Laws for inheritance of traits: Sex determination: brief introduction.',
    defaultEstimatedHours: 5,
    examWeightage: 'high',
    difficulty: 'medium',
    prerequisites: ['c10-sci-7'],
    inCbseSyllabus: true,
    topics: [
      { id: 'c10-s8-t1', name: 'Mendel monohybrid (3:1) and dihybrid (9:3:3:1) crosses and Punnett squares', inCbseSyllabus: true },
      { id: 'c10-s8-t2', name: 'Sex determination in human beings (XX and XY chromosomes)', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?jesc1=8-13`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'c10-sci-9',
    subjectId: 'cbse-10-science',
    subjectName: 'Science',
    subjectCode: '086',
    class: '10',
    academicSession: '2026-27',
    title: 'Light – Reflection and Refraction',
    chapterNumber: 9,
    unitNumber: 3,
    unitName: 'Natural Phenomena (Light & Human Eye)',
    description: 'Reflection of light by curved surfaces; Images formed by spherical mirrors, centre of curvature, principal axis, principal focus, focal length, mirror formula, magnification. Refraction; Laws of refraction, refractive index. Refraction by spherical lens; Lens formula, magnification, power of a lens.',
    defaultEstimatedHours: 8,
    examWeightage: 'critical',
    difficulty: 'hard',
    prerequisites: [],
    inCbseSyllabus: true,
    topics: [
      { id: 'c10-s9-t1', name: 'Ray diagrams for concave and convex mirrors, mirror formula 1/f = 1/v + 1/u', inCbseSyllabus: true },
      { id: 'c10-s9-t2', name: "Snell's Law of refraction n = sin i / sin r, absolute and relative refractive index", inCbseSyllabus: true },
      { id: 'c10-s9-t3', name: 'Lens formula 1/f = 1/v - 1/u, magnification m = v/u, and Power P = 1/f (dioptres)', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?jesc1=9-13`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'c10-sci-10',
    subjectId: 'cbse-10-science',
    subjectName: 'Science',
    subjectCode: '086',
    class: '10',
    academicSession: '2026-27',
    title: 'The Human Eye and the Colourful World',
    chapterNumber: 10,
    unitNumber: 3,
    unitName: 'Natural Phenomena (Light & Human Eye)',
    description: 'Functioning of a lens in human eye, defects of vision and their corrections, applications of spherical mirrors and lenses. Refraction of light through a prism, dispersion of light, scattering of light, applications in daily life.',
    defaultEstimatedHours: 5,
    examWeightage: 'high',
    difficulty: 'medium',
    prerequisites: ['c10-sci-9'],
    inCbseSyllabus: true,
    topics: [
      { id: 'c10-s10-t1', name: 'Accommodation of eye, Myopia, Hypermetropia, Presbyopia and lens corrections', inCbseSyllabus: true },
      { id: 'c10-s10-t2', name: 'Dispersion through glass prism, rainbow formation, atmospheric refraction (twinkling of stars)', inCbseSyllabus: true },
      { id: 'c10-s10-t3', name: 'Tyndall effect and Rayleigh scattering (blue sky, reddish sunrise/sunset)', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?jesc1=10-13`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'c10-sci-11',
    subjectId: 'cbse-10-science',
    subjectName: 'Science',
    subjectCode: '086',
    class: '10',
    academicSession: '2026-27',
    title: 'Electricity',
    chapterNumber: 11,
    unitNumber: 4,
    unitName: 'Effects of Current (Electricity & Magnetism)',
    description: 'Electric current, potential difference and electric current. Ohm law; Resistance, Resistivity, Factors on which the resistance of a conductor depends. Series combination of resistors, parallel combination of resistors and its applications in daily life. Heating effect of electric current and its applications in daily life. Electric power, Interrelation between P, V, I and R.',
    defaultEstimatedHours: 8,
    examWeightage: 'critical',
    difficulty: 'hard',
    prerequisites: [],
    inCbseSyllabus: true,
    topics: [
      { id: 'c10-s11-t1', name: "Ohm's Law V = IR, resistance, factors affecting R = rho * l / A", inCbseSyllabus: true },
      { id: 'c10-s11-t2', name: 'Resistors in series (Rs = R1+R2+R3) and parallel (1/Rp = 1/R1+1/R2+1/R3)', inCbseSyllabus: true },
      { id: 'c10-s11-t3', name: "Joule's Law of heating H = I^2 R t, electric power P = VI = I^2 R = V^2 / R, commercial unit kWh", inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?jesc1=11-13`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'c10-sci-12',
    subjectId: 'cbse-10-science',
    subjectName: 'Science',
    subjectCode: '086',
    class: '10',
    academicSession: '2026-27',
    title: 'Magnetic Effects of Electric Current',
    chapterNumber: 12,
    unitNumber: 4,
    unitName: 'Effects of Current (Electricity & Magnetism)',
    description: 'Magnetic field, field lines, field due to a current carrying conductor, field due to current carrying coil or solenoid; Force on current carrying conductor, Fleming Left Hand Rule, Direct current. Alternating current: frequency of AC. Advantage of AC over DC. Domestic electric circuits.',
    defaultEstimatedHours: 6,
    examWeightage: 'high',
    difficulty: 'medium',
    prerequisites: ['c10-sci-11'],
    inCbseSyllabus: true,
    topics: [
      { id: 'c10-s12-t1', name: 'Magnetic field lines properties, Right Hand Thumb Rule, solenoid field', inCbseSyllabus: true },
      { id: 'c10-s12-t2', name: "Force on conductor in magnetic field, Fleming's Left Hand Rule", inCbseSyllabus: true },
      { id: 'c10-s12-t3', name: 'Domestic electric circuits: Earth wire, fuse, overloading, short circuiting, AC vs DC', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?jesc1=12-13`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'c10-sci-13',
    subjectId: 'cbse-10-science',
    subjectName: 'Science',
    subjectCode: '086',
    class: '10',
    academicSession: '2026-27',
    title: 'Our Environment',
    chapterNumber: 13,
    unitNumber: 5,
    unitName: 'Natural Resources',
    description: 'Eco-system, Environmental problems, Ozone depletion, waste production and their solutions. Biodegradable and non-biodegradable substances.',
    defaultEstimatedHours: 4,
    examWeightage: 'medium',
    difficulty: 'easy',
    prerequisites: [],
    inCbseSyllabus: true,
    topics: [
      { id: 'c10-s13-t1', name: 'Food chains, food webs, trophic levels and 10% energy transfer law', inCbseSyllabus: true },
      { id: 'c10-s13-t2', name: 'Biological magnification, ozone layer depletion by CFCs, and waste management', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?jesc1=13-13`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
];
