import { type CurriculumChapter } from './types';
import { OFFICIAL_CBSE_SYLLABUS_PORTAL, OFFICIAL_NCERT_PORTAL, OFFICIAL_CBSE_SKILL_PORTAL } from './cbse-2027-database';

export const CLASS_9_CHAPTERS: CurriculumChapter[] = [
  // Mathematics (041)
  {
    id: 'c9-math-1',
    subjectId: 'cbse-9-math',
    subjectName: 'Mathematics',
    subjectCode: '041',
    class: '9',
    academicSession: '2026-27',
    title: 'Number Systems',
    chapterNumber: 1,
    unitNumber: 1,
    unitName: 'Number Systems',
    description: 'Real numbers, representation on number line, laws of exponents for real numbers.',
    defaultEstimatedHours: 6,
    examWeightage: 'high',
    difficulty: 'easy',
    prerequisites: [],
    inCbseSyllabus: true,
    topics: [
      { id: 'c9-m1-t1', name: 'Irrational numbers and real numbers', inCbseSyllabus: true },
      { id: 'c9-m1-t2', name: 'Real numbers and their decimal expansions', inCbseSyllabus: true },
      { id: 'c9-m1-t3', name: 'Operations on real numbers & rationalising denominator', inCbseSyllabus: true },
      { id: 'c9-m1-t4', name: 'Laws of exponents for real numbers', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?iemh1=1-12`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'c9-math-2',
    subjectId: 'cbse-9-math',
    subjectName: 'Mathematics',
    subjectCode: '041',
    class: '9',
    academicSession: '2026-27',
    title: 'Polynomials',
    chapterNumber: 2,
    unitNumber: 2,
    unitName: 'Algebra',
    description: 'Definition, coefficients, zeroes, Remainder Theorem, Factor Theorem, algebraic identities.',
    defaultEstimatedHours: 8,
    examWeightage: 'critical',
    difficulty: 'medium',
    prerequisites: ['c9-math-1'],
    inCbseSyllabus: true,
    topics: [
      { id: 'c9-m2-t1', name: 'Zeroes of a polynomial', inCbseSyllabus: true },
      { id: 'c9-m2-t2', name: 'Factor Theorem and factorisation of polynomials', inCbseSyllabus: true },
      { id: 'c9-m2-t3', name: 'Algebraic identities for quadratic and cubic polynomials', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?iemh1=2-12`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'c9-math-3',
    subjectId: 'cbse-9-math',
    subjectName: 'Mathematics',
    subjectCode: '041',
    class: '9',
    academicSession: '2026-27',
    title: 'Coordinate Geometry',
    chapterNumber: 3,
    unitNumber: 3,
    unitName: 'Coordinate Geometry',
    description: 'Cartesian plane, coordinates of a point, plotting points.',
    defaultEstimatedHours: 4,
    examWeightage: 'medium',
    difficulty: 'easy',
    prerequisites: [],
    inCbseSyllabus: true,
    topics: [
      { id: 'c9-m3-t1', name: 'Cartesian system and quadrant signs', inCbseSyllabus: true },
      { id: 'c9-m3-t2', name: 'Plotting points in the plane for given coordinates', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?iemh1=3-12`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'c9-math-4',
    subjectId: 'cbse-9-math',
    subjectName: 'Mathematics',
    subjectCode: '041',
    class: '9',
    academicSession: '2026-27',
    title: 'Linear Equations in Two Variables',
    chapterNumber: 4,
    unitNumber: 2,
    unitName: 'Algebra',
    description: 'Introduction to equation in two variables, solutions, graphing on Cartesian plane.',
    defaultEstimatedHours: 6,
    examWeightage: 'high',
    difficulty: 'medium',
    prerequisites: ['c9-math-2', 'c9-math-3'],
    inCbseSyllabus: true,
    topics: [
      { id: 'c9-m4-t1', name: 'Standard form ax + by + c = 0', inCbseSyllabus: true },
      { id: 'c9-m4-t2', name: 'Solution of a linear equation in two variables', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?iemh1=4-12`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'c9-math-5',
    subjectId: 'cbse-9-math',
    subjectName: 'Mathematics',
    subjectCode: '041',
    class: '9',
    academicSession: '2026-27',
    title: "Introduction to Euclid's Geometry",
    chapterNumber: 5,
    unitNumber: 4,
    unitName: 'Geometry',
    description: "History of geometry, Euclid's definitions, axioms and postulates.",
    defaultEstimatedHours: 3,
    examWeightage: 'low',
    difficulty: 'easy',
    prerequisites: [],
    inCbseSyllabus: true,
    topics: [
      { id: 'c9-m5-t1', name: "Euclid's definitions, axioms and postulates", inCbseSyllabus: true },
      { id: 'c9-m5-t2', name: 'Equivalent versions of fifth postulate', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?iemh1=5-12`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'c9-math-6',
    subjectId: 'cbse-9-math',
    subjectName: 'Mathematics',
    subjectCode: '041',
    class: '9',
    academicSession: '2026-27',
    title: 'Lines and Angles',
    chapterNumber: 6,
    unitNumber: 4,
    unitName: 'Geometry',
    description: 'Basic terms, intersecting lines, parallel lines and transversal, angle sum property.',
    defaultEstimatedHours: 6,
    examWeightage: 'high',
    difficulty: 'medium',
    prerequisites: ['c9-math-5'],
    inCbseSyllabus: true,
    topics: [
      { id: 'c9-m6-t1', name: 'Intersecting and non-intersecting lines', inCbseSyllabus: true },
      { id: 'c9-m6-t2', name: 'Pairs of angles and parallel lines with transversal', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?iemh1=6-12`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'c9-math-7',
    subjectId: 'cbse-9-math',
    subjectName: 'Mathematics',
    subjectCode: '041',
    class: '9',
    academicSession: '2026-27',
    title: 'Triangles',
    chapterNumber: 7,
    unitNumber: 4,
    unitName: 'Geometry',
    description: 'Congruence of triangles, SAS, ASA, AAS, SSS, RHS criteria, properties of triangles.',
    defaultEstimatedHours: 8,
    examWeightage: 'critical',
    difficulty: 'hard',
    prerequisites: ['c9-math-6'],
    inCbseSyllabus: true,
    topics: [
      { id: 'c9-m7-t1', name: 'Congruence criteria (SAS, ASA, AAS, SSS, RHS)', inCbseSyllabus: true },
      { id: 'c9-m7-t2', name: 'Properties of isosceles and equilateral triangles', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?iemh1=7-12`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'c9-math-8',
    subjectId: 'cbse-9-math',
    subjectName: 'Mathematics',
    subjectCode: '041',
    class: '9',
    academicSession: '2026-27',
    title: 'Quadrilaterals',
    chapterNumber: 8,
    unitNumber: 4,
    unitName: 'Geometry',
    description: 'Angle sum property, types of quadrilaterals, properties of parallelogram, Mid-point Theorem.',
    defaultEstimatedHours: 6,
    examWeightage: 'high',
    difficulty: 'medium',
    prerequisites: ['c9-math-7'],
    inCbseSyllabus: true,
    topics: [
      { id: 'c9-m8-t1', name: 'Properties of a parallelogram', inCbseSyllabus: true },
      { id: 'c9-m8-t2', name: 'The Mid-point Theorem and its converse', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?iemh1=8-12`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'c9-math-9',
    subjectId: 'cbse-9-math',
    subjectName: 'Mathematics',
    subjectCode: '041',
    class: '9',
    academicSession: '2026-27',
    title: 'Circles',
    chapterNumber: 9,
    unitNumber: 4,
    unitName: 'Geometry',
    description: 'Chords, perpendicular from center, cyclic quadrilaterals, angles subtended by arcs.',
    defaultEstimatedHours: 7,
    examWeightage: 'high',
    difficulty: 'hard',
    prerequisites: ['c9-math-7'],
    inCbseSyllabus: true,
    topics: [
      { id: 'c9-m9-t1', name: 'Equal chords and perpendicular bisector theorem', inCbseSyllabus: true },
      { id: 'c9-m9-t2', name: 'Angle subtended by an arc at the center and cyclic quadrilaterals', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?iemh1=9-12`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'c9-math-10',
    subjectId: 'cbse-9-math',
    subjectName: 'Mathematics',
    subjectCode: '041',
    class: '9',
    academicSession: '2026-27',
    title: "Heron's Formula",
    chapterNumber: 10,
    unitNumber: 5,
    unitName: 'Mensuration',
    description: "Area of a triangle using Heron's formula (without proof).",
    defaultEstimatedHours: 4,
    examWeightage: 'medium',
    difficulty: 'easy',
    prerequisites: [],
    inCbseSyllabus: true,
    topics: [
      { id: 'c9-m10-t1', name: "Area of triangle using s = (a+b+c)/2 and sqrt(s(s-a)(s-b)(s-c))", inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?iemh1=10-12`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'c9-math-11',
    subjectId: 'cbse-9-math',
    subjectName: 'Mathematics',
    subjectCode: '041',
    class: '9',
    academicSession: '2026-27',
    title: 'Surface Areas and Volumes',
    chapterNumber: 11,
    unitNumber: 5,
    unitName: 'Mensuration',
    description: 'Surface areas and volumes of right circular cones, spheres and hemispheres.',
    defaultEstimatedHours: 8,
    examWeightage: 'critical',
    difficulty: 'medium',
    prerequisites: [],
    inCbseSyllabus: true,
    topics: [
      { id: 'c9-m11-t1', name: 'Surface area of right circular cone, sphere and hemisphere', inCbseSyllabus: true },
      { id: 'c9-m11-t2', name: 'Volume of right circular cone, sphere and hemisphere', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?iemh1=11-12`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'c9-math-12',
    subjectId: 'cbse-9-math',
    subjectName: 'Mathematics',
    subjectCode: '041',
    class: '9',
    academicSession: '2026-27',
    title: 'Statistics',
    chapterNumber: 12,
    unitNumber: 6,
    unitName: 'Statistics',
    description: 'Graphical representation of data: bar graphs, histograms, and frequency polygons.',
    defaultEstimatedHours: 5,
    examWeightage: 'medium',
    difficulty: 'easy',
    prerequisites: [],
    inCbseSyllabus: true,
    topics: [
      { id: 'c9-m12-t1', name: 'Bar graphs, histograms of varying base widths, frequency polygons', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?iemh1=12-12`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },

  // Science (086)
  {
    id: 'c9-sci-1',
    subjectId: 'cbse-9-science',
    subjectName: 'Science',
    subjectCode: '086',
    class: '9',
    academicSession: '2026-27',
    title: 'Matter in Our Surroundings',
    chapterNumber: 1,
    unitNumber: 1,
    unitName: 'Matter - Nature and Behaviour',
    description: 'Physical nature of matter, states of matter, change of state, evaporation and factors affecting it.',
    defaultEstimatedHours: 5,
    examWeightage: 'high',
    difficulty: 'easy',
    prerequisites: [],
    inCbseSyllabus: true,
    topics: [
      { id: 'c9-s1-t1', name: 'Solid, liquid, and gas characteristics and interconversions', inCbseSyllabus: true },
      { id: 'c9-s1-t2', name: 'Latent heat of fusion and vaporisation, sublimation', inCbseSyllabus: true },
      { id: 'c9-s1-t3', name: 'Evaporation and cooling effect', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?iesc1=1-12`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'c9-sci-2',
    subjectId: 'cbse-9-science',
    subjectName: 'Science',
    subjectCode: '086',
    class: '9',
    academicSession: '2026-27',
    title: 'Is Matter Around Us Pure?',
    chapterNumber: 2,
    unitNumber: 1,
    unitName: 'Matter - Nature and Behaviour',
    description: 'Mixtures, solutions, suspensions, colloids, elements, compounds, physical and chemical changes.',
    defaultEstimatedHours: 6,
    examWeightage: 'high',
    difficulty: 'medium',
    prerequisites: ['c9-sci-1'],
    inCbseSyllabus: true,
    topics: [
      { id: 'c9-s2-t1', name: 'Solutions, suspensions, colloids and Tyndall effect', inCbseSyllabus: true },
      { id: 'c9-s2-t2', name: 'Elements vs Compounds, physical vs chemical change', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?iesc1=2-12`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'c9-sci-3',
    subjectId: 'cbse-9-science',
    subjectName: 'Science',
    subjectCode: '086',
    class: '9',
    academicSession: '2026-27',
    title: 'Atoms and Molecules',
    chapterNumber: 3,
    unitNumber: 1,
    unitName: 'Matter - Nature and Behaviour',
    description: 'Laws of chemical combination, Dalton atomic theory, atomic and molecular masses, chemical formulae.',
    defaultEstimatedHours: 7,
    examWeightage: 'critical',
    difficulty: 'hard',
    prerequisites: ['c9-sci-2'],
    inCbseSyllabus: true,
    topics: [
      { id: 'c9-s3-t1', name: 'Law of conservation of mass & constant proportions', inCbseSyllabus: true },
      { id: 'c9-s3-t2', name: 'Atoms, symbols, valency, and writing chemical formulae', inCbseSyllabus: true },
      { id: 'c9-s3-t3', name: 'Molecular mass and formula unit mass', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?iesc1=3-12`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'c9-sci-4',
    subjectId: 'cbse-9-science',
    subjectName: 'Science',
    subjectCode: '086',
    class: '9',
    academicSession: '2026-27',
    title: 'Structure of the Atom',
    chapterNumber: 4,
    unitNumber: 1,
    unitName: 'Matter - Nature and Behaviour',
    description: 'Charged particles, Thomson, Rutherford, Bohr models, atomic number, mass number, isotopes, isobars.',
    defaultEstimatedHours: 6,
    examWeightage: 'high',
    difficulty: 'medium',
    prerequisites: ['c9-sci-3'],
    inCbseSyllabus: true,
    topics: [
      { id: 'c9-s4-t1', name: 'Electrons, protons, neutrons discovery and Rutherford model', inCbseSyllabus: true },
      { id: 'c9-s4-t2', name: "Bohr's model of atom and electron distribution", inCbseSyllabus: true },
      { id: 'c9-s4-t3', name: 'Atomic number, mass number, isotopes, and isobars', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?iesc1=4-12`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'c9-sci-5',
    subjectId: 'cbse-9-science',
    subjectName: 'Science',
    subjectCode: '086',
    class: '9',
    academicSession: '2026-27',
    title: 'The Fundamental Unit of Life',
    chapterNumber: 5,
    unitNumber: 2,
    unitName: 'Organization in the Living World',
    description: 'Cell as basic unit, prokaryotic & eukaryotic cells, cell organelles, osmosis and diffusion.',
    defaultEstimatedHours: 7,
    examWeightage: 'critical',
    difficulty: 'medium',
    prerequisites: [],
    inCbseSyllabus: true,
    topics: [
      { id: 'c9-s5-t1', name: 'Cell wall, plasma membrane, diffusion, and osmosis', inCbseSyllabus: true },
      { id: 'c9-s5-t2', name: 'Nucleus, cytoplasm, and cell organelles (mitochondria, plastids, ER, Golgi, vacuoles)', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?iesc1=5-12`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'c9-sci-6',
    subjectId: 'cbse-9-science',
    subjectName: 'Science',
    subjectCode: '086',
    class: '9',
    academicSession: '2026-27',
    title: 'Tissues',
    chapterNumber: 6,
    unitNumber: 2,
    unitName: 'Organization in the Living World',
    description: 'Meristematic and permanent plant tissues, animal tissues (epithelial, connective, muscular, nervous).',
    defaultEstimatedHours: 7,
    examWeightage: 'high',
    difficulty: 'medium',
    prerequisites: ['c9-sci-5'],
    inCbseSyllabus: true,
    topics: [
      { id: 'c9-s6-t1', name: 'Plant tissues: Meristematic, parenchyma, collenchyma, sclerenchyma, xylem, phloem', inCbseSyllabus: true },
      { id: 'c9-s6-t2', name: 'Animal tissues: Epithelial, connective (blood, bone, cartilage), muscular, nervous', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?iesc1=6-12`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'c9-sci-7',
    subjectId: 'cbse-9-science',
    subjectName: 'Science',
    subjectCode: '086',
    class: '9',
    academicSession: '2026-27',
    title: 'Motion',
    chapterNumber: 7,
    unitNumber: 3,
    unitName: 'Motion, Force and Work',
    description: 'Distance, displacement, speed, velocity, acceleration, distance-time & velocity-time graphs, equations of motion.',
    defaultEstimatedHours: 8,
    examWeightage: 'critical',
    difficulty: 'hard',
    prerequisites: [],
    inCbseSyllabus: true,
    topics: [
      { id: 'c9-s7-t1', name: 'Distance, displacement, uniform vs non-uniform motion, acceleration', inCbseSyllabus: true },
      { id: 'c9-s7-t2', name: 'Graphical representation of motion and slope interpretations', inCbseSyllabus: true },
      { id: 'c9-s7-t3', name: 'Equations of motion: v = u + at, s = ut + 1/2at^2, v^2 = u^2 + 2as', inCbseSyllabus: true },
      { id: 'c9-s7-t4', name: 'Uniform circular motion', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?iesc1=7-12`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'c9-sci-8',
    subjectId: 'cbse-9-science',
    subjectName: 'Science',
    subjectCode: '086',
    class: '9',
    academicSession: '2026-27',
    title: 'Force and Laws of Motion',
    chapterNumber: 8,
    unitNumber: 3,
    unitName: 'Motion, Force and Work',
    description: "Balanced & unbalanced forces, Newton's first, second, and third laws of motion, inertia, momentum.",
    defaultEstimatedHours: 7,
    examWeightage: 'critical',
    difficulty: 'hard',
    prerequisites: ['c9-sci-7'],
    inCbseSyllabus: true,
    topics: [
      { id: 'c9-s8-t1', name: "First law of motion, inertia, and mass", inCbseSyllabus: true },
      { id: 'c9-s8-t2', name: "Second law of motion, momentum, F = ma", inCbseSyllabus: true },
      { id: 'c9-s8-t3', name: "Third law of motion, action-reaction pairs", inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?iesc1=8-12`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'c9-sci-9',
    subjectId: 'cbse-9-science',
    subjectName: 'Science',
    subjectCode: '086',
    class: '9',
    academicSession: '2026-27',
    title: 'Gravitation',
    chapterNumber: 9,
    unitNumber: 3,
    unitName: 'Motion, Force and Work',
    description: 'Universal law of gravitation, free fall, acceleration due to gravity g, mass vs weight, thrust, pressure, buoyancy, Archimedes principle.',
    defaultEstimatedHours: 6,
    examWeightage: 'high',
    difficulty: 'medium',
    prerequisites: ['c9-sci-8'],
    inCbseSyllabus: true,
    topics: [
      { id: 'c9-s9-t1', name: 'Universal Law of Gravitation and calculation of g', inCbseSyllabus: true },
      { id: 'c9-s9-t2', name: 'Mass vs weight, free fall calculations', inCbseSyllabus: true },
      { id: 'c9-s9-t3', name: 'Buoyancy, Archimedes principle, and relative density', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?iesc1=9-12`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'c9-sci-10',
    subjectId: 'cbse-9-science',
    subjectName: 'Science',
    subjectCode: '086',
    class: '9',
    academicSession: '2026-27',
    title: 'Work and Energy',
    chapterNumber: 10,
    unitNumber: 3,
    unitName: 'Motion, Force and Work',
    description: 'Work done by force, kinetic and potential energy, law of conservation of energy, power.',
    defaultEstimatedHours: 6,
    examWeightage: 'high',
    difficulty: 'medium',
    prerequisites: ['c9-sci-8'],
    inCbseSyllabus: true,
    topics: [
      { id: 'c9-s10-t1', name: 'Scientific conception of work: W = F * s', inCbseSyllabus: true },
      { id: 'c9-s10-t2', name: 'Kinetic energy (1/2 mv^2) and potential energy (mgh)', inCbseSyllabus: true },
      { id: 'c9-s10-t3', name: 'Law of conservation of energy and rate of doing work (Power)', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?iesc1=10-12`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'c9-sci-11',
    subjectId: 'cbse-9-science',
    subjectName: 'Science',
    subjectCode: '086',
    class: '9',
    academicSession: '2026-27',
    title: 'Sound',
    chapterNumber: 11,
    unitNumber: 3,
    unitName: 'Motion, Force and Work',
    description: 'Propagation of sound, longitudinal waves, characteristics of sound wave, speed of sound, reflection of sound, echo, SONAR.',
    defaultEstimatedHours: 5,
    examWeightage: 'medium',
    difficulty: 'medium',
    prerequisites: [],
    inCbseSyllabus: true,
    topics: [
      { id: 'c9-s11-t1', name: 'Production & propagation of sound, wavelength, frequency, amplitude', inCbseSyllabus: true },
      { id: 'c9-s11-t2', name: 'Echo, reverberation, and ultrasound applications', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?iesc1=11-12`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'c9-sci-12',
    subjectId: 'cbse-9-science',
    subjectName: 'Science',
    subjectCode: '086',
    class: '9',
    academicSession: '2026-27',
    title: 'Improvement in Food Resources',
    chapterNumber: 12,
    unitNumber: 4,
    unitName: 'Food; Food Production',
    description: 'Crop production management, crop protection, nutrient management, manures, fertilizers, animal husbandry.',
    defaultEstimatedHours: 5,
    examWeightage: 'medium',
    difficulty: 'easy',
    prerequisites: [],
    inCbseSyllabus: true,
    topics: [
      { id: 'c9-s12-t1', name: 'Crop variety improvement and nutrient management', inCbseSyllabus: true },
      { id: 'c9-s12-t2', name: 'Animal husbandry: Cattle, poultry, fisheries, and apiculture', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?iesc1=12-12`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },

  // Social Science (087)
  {
    id: 'c9-sst-hist-1',
    subjectId: 'cbse-9-sst',
    subjectName: 'Social Science',
    subjectCode: '087',
    class: '9',
    academicSession: '2026-27',
    title: 'The French Revolution',
    chapterNumber: 1,
    unitNumber: 1,
    unitName: 'India and the Contemporary World - I (History)',
    description: 'French society in late 18th century, outbreak of revolution, abolition of monarchy, Reign of Terror.',
    defaultEstimatedHours: 6,
    examWeightage: 'high',
    difficulty: 'medium',
    prerequisites: [],
    inCbseSyllabus: true,
    topics: [
      { id: 'c9-h1-t1', name: 'Estate system and crisis of the Old Regime', inCbseSyllabus: true },
      { id: 'c9-h1-t2', name: 'Declaration of the Rights of Man and citizen', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?iess3=1-5`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'c9-sst-hist-2',
    subjectId: 'cbse-9-sst',
    subjectName: 'Social Science',
    subjectCode: '087',
    class: '9',
    academicSession: '2026-27',
    title: 'Socialism in Europe and the Russian Revolution',
    chapterNumber: 2,
    unitNumber: 1,
    unitName: 'India and the Contemporary World - I (History)',
    description: 'Age of social change, Russian Empire in 1914, October Revolution, Civil War, collectivisation.',
    defaultEstimatedHours: 6,
    examWeightage: 'high',
    difficulty: 'medium',
    prerequisites: [],
    inCbseSyllabus: true,
    topics: [
      { id: 'c9-h2-t1', name: 'February Revolution in Petrograd & Bolshevik rise', inCbseSyllabus: true },
      { id: 'c9-h2-t2', name: 'October Revolution and Stalin Collectivisation', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?iess3=2-5`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'c9-sst-hist-3',
    subjectId: 'cbse-9-sst',
    subjectName: 'Social Science',
    subjectCode: '087',
    class: '9',
    academicSession: '2026-27',
    title: 'Nazism and the Rise of Hitler',
    chapterNumber: 3,
    unitNumber: 1,
    unitName: 'India and the Contemporary World - I (History)',
    description: 'Birth of Weimar Republic, Hitler rise to power, Nazi worldview, youth in Nazi Germany, Holocaust.',
    defaultEstimatedHours: 6,
    examWeightage: 'high',
    difficulty: 'medium',
    prerequisites: [],
    inCbseSyllabus: true,
    topics: [
      { id: 'c9-h3-t1', name: 'Weimar Republic collapse and Great Depression', inCbseSyllabus: true },
      { id: 'c9-h3-t2', name: 'Nazi racial state propaganda and Holocaust memory', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?iess3=3-5`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'c9-sst-hist-4',
    subjectId: 'cbse-9-sst',
    subjectName: 'Social Science',
    subjectCode: '087',
    class: '9',
    academicSession: '2026-27',
    title: 'Forest Society and Colonialism',
    chapterNumber: 4,
    unitNumber: 1,
    unitName: 'India and the Contemporary World - I (History)',
    description: 'Deforestation, commercial forestry, rebellion in the forest (Bastar, Java).',
    defaultEstimatedHours: 4,
    examWeightage: 'medium',
    difficulty: 'easy',
    prerequisites: [],
    inCbseSyllabus: true,
    topics: [
      { id: 'c9-h4-t1', name: 'Colonial forest acts and tribal rebellions in Bastar & Java', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?iess3=4-5`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'c9-sst-hist-5',
    subjectId: 'cbse-9-sst',
    subjectName: 'Social Science',
    subjectCode: '087',
    class: '9',
    academicSession: '2026-27',
    title: 'Pastoralists in the Modern World',
    chapterNumber: 5,
    unitNumber: 1,
    unitName: 'India and the Contemporary World - I (History)',
    description: 'Pastoral nomads and their movements in India and Africa, impact of colonial rule.',
    defaultEstimatedHours: 4,
    examWeightage: 'medium',
    difficulty: 'easy',
    prerequisites: [],
    inCbseSyllabus: true,
    topics: [
      { id: 'c9-h5-t1', name: 'Nomadic pastoralists in India and Maasai community in Africa', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?iess3=5-5`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'c9-sst-geo-1',
    subjectId: 'cbse-9-sst',
    subjectName: 'Social Science',
    subjectCode: '087',
    class: '9',
    academicSession: '2026-27',
    title: 'India - Size and Location',
    chapterNumber: 6,
    unitNumber: 2,
    unitName: 'Contemporary India - I (Geography)',
    description: 'Location, size, India and the world, India neighbours.',
    defaultEstimatedHours: 3,
    examWeightage: 'medium',
    difficulty: 'easy',
    prerequisites: [],
    inCbseSyllabus: true,
    topics: [
      { id: 'c9-g1-t1', name: 'Latitudinal & longitudinal extent, Standard Meridian 82°30’ E', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?iess1=1-6`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'c9-sst-geo-2',
    subjectId: 'cbse-9-sst',
    subjectName: 'Social Science',
    subjectCode: '087',
    class: '9',
    academicSession: '2026-27',
    title: 'Physical Features of India',
    chapterNumber: 7,
    unitNumber: 2,
    unitName: 'Contemporary India - I (Geography)',
    description: 'Major physiographic divisions: Himalayas, Northern Plains, Peninsular Plateau, Indian Desert, Coastal Plains, Islands.',
    defaultEstimatedHours: 6,
    examWeightage: 'critical',
    difficulty: 'medium',
    prerequisites: ['c9-sst-geo-1'],
    inCbseSyllabus: true,
    topics: [
      { id: 'c9-g2-t1', name: 'Himalayan ranges, Northern Plains formation and relief features', inCbseSyllabus: true },
      { id: 'c9-g2-t2', name: 'Peninsular plateau, Western vs Eastern Ghats, Coastal plains', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?iess1=2-6`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'c9-sst-geo-3',
    subjectId: 'cbse-9-sst',
    subjectName: 'Social Science',
    subjectCode: '087',
    class: '9',
    academicSession: '2026-27',
    title: 'Drainage',
    chapterNumber: 8,
    unitNumber: 2,
    unitName: 'Contemporary India - I (Geography)',
    description: 'Drainage systems in India: Himalayan and Peninsular rivers, lakes, role of rivers in economy, river pollution.',
    defaultEstimatedHours: 5,
    examWeightage: 'high',
    difficulty: 'medium',
    prerequisites: ['c9-sst-geo-2'],
    inCbseSyllabus: true,
    topics: [
      { id: 'c9-g3-t1', name: 'Indus, Ganga, Brahmaputra river systems', inCbseSyllabus: true },
      { id: 'c9-g3-t2', name: 'Narmada, Tapi, Godavari, Krishna, Kaveri basins', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?iess1=3-6`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'c9-sst-geo-4',
    subjectId: 'cbse-9-sst',
    subjectName: 'Social Science',
    subjectCode: '087',
    class: '9',
    academicSession: '2026-27',
    title: 'Climate',
    chapterNumber: 9,
    unitNumber: 2,
    unitName: 'Contemporary India - I (Geography)',
    description: 'Climatic controls, factors affecting India climate, monsoon mechanism, seasons, distribution of rainfall.',
    defaultEstimatedHours: 6,
    examWeightage: 'critical',
    difficulty: 'hard',
    prerequisites: ['c9-sst-geo-2'],
    inCbseSyllabus: true,
    topics: [
      { id: 'c9-g4-t1', name: 'Coriolis force, Jet streams, ITCZ, and Southern Oscillation', inCbseSyllabus: true },
      { id: 'c9-g4-t2', name: 'Onset and withdrawal of Indian monsoon and seasonal rhythm', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?iess1=4-6`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'c9-sst-geo-5',
    subjectId: 'cbse-9-sst',
    subjectName: 'Social Science',
    subjectCode: '087',
    class: '9',
    academicSession: '2026-27',
    title: 'Population',
    chapterNumber: 10,
    unitNumber: 2,
    unitName: 'Contemporary India - I (Geography)',
    description: 'Population size and distribution, population growth and processes of change, National Population Policy.',
    defaultEstimatedHours: 4,
    examWeightage: 'medium',
    difficulty: 'easy',
    prerequisites: [],
    inCbseSyllabus: true,
    topics: [
      { id: 'c9-g5-t1', name: 'Census, sex ratio, age composition, and population policy', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?iess1=6-6`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'c9-sst-civ-1',
    subjectId: 'cbse-9-sst',
    subjectName: 'Social Science',
    subjectCode: '087',
    class: '9',
    academicSession: '2026-27',
    title: 'What is Democracy? Why Democracy?',
    chapterNumber: 11,
    unitNumber: 3,
    unitName: 'Democratic Politics - I (Civics)',
    description: 'Definition, features of democracy, arguments for and against democracy, broader meaning.',
    defaultEstimatedHours: 4,
    examWeightage: 'high',
    difficulty: 'easy',
    prerequisites: [],
    inCbseSyllabus: true,
    topics: [
      { id: 'c9-c1-t1', name: 'Major decisions by elected leaders & free and fair elections', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?iess4=1-5`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'c9-sst-civ-2',
    subjectId: 'cbse-9-sst',
    subjectName: 'Social Science',
    subjectCode: '087',
    class: '9',
    academicSession: '2026-27',
    title: 'Constitutional Design',
    chapterNumber: 12,
    unitNumber: 3,
    unitName: 'Democratic Politics - I (Civics)',
    description: 'Democratic Constitution in South Africa, why do we need a constitution, making of the Indian Constitution, guiding values.',
    defaultEstimatedHours: 5,
    examWeightage: 'high',
    difficulty: 'medium',
    prerequisites: ['c9-sst-civ-1'],
    inCbseSyllabus: true,
    topics: [
      { id: 'c9-c2-t1', name: 'Constituent Assembly debates and Preamble philosophy', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?iess4=2-5`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'c9-sst-civ-3',
    subjectId: 'cbse-9-sst',
    subjectName: 'Social Science',
    subjectCode: '087',
    class: '9',
    academicSession: '2026-27',
    title: 'Electoral Politics',
    chapterNumber: 13,
    unitNumber: 3,
    unitName: 'Democratic Politics - I (Civics)',
    description: 'Why elections, system of elections in India, Election Commission, democratic challenges.',
    defaultEstimatedHours: 4,
    examWeightage: 'high',
    difficulty: 'easy',
    prerequisites: ['c9-sst-civ-2'],
    inCbseSyllabus: true,
    topics: [
      { id: 'c9-c3-t1', name: 'Constituencies, voters list, polling, and Election Commission powers', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?iess4=3-5`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'c9-sst-civ-4',
    subjectId: 'cbse-9-sst',
    subjectName: 'Social Science',
    subjectCode: '087',
    class: '9',
    academicSession: '2026-27',
    title: 'Working of Institutions',
    chapterNumber: 14,
    unitNumber: 3,
    unitName: 'Democratic Politics - I (Civics)',
    description: 'How a policy decision is taken, Parliament, Prime Minister & Council of Ministers, President, Judiciary.',
    defaultEstimatedHours: 6,
    examWeightage: 'critical',
    difficulty: 'medium',
    prerequisites: ['c9-sst-civ-3'],
    inCbseSyllabus: true,
    topics: [
      { id: 'c9-c4-t1', name: 'Lok Sabha vs Rajya Sabha, powers of Prime Minister & Cabinet', inCbseSyllabus: true },
      { id: 'c9-c4-t2', name: 'Independence and powers of the Supreme Court of India', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?iess4=4-5`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'c9-sst-civ-5',
    subjectId: 'cbse-9-sst',
    subjectName: 'Social Science',
    subjectCode: '087',
    class: '9',
    academicSession: '2026-27',
    title: 'Democratic Rights',
    chapterNumber: 15,
    unitNumber: 3,
    unitName: 'Democratic Politics - I (Civics)',
    description: 'Life without rights, rights in a democracy, Fundamental Rights in Indian Constitution, expanding scope.',
    defaultEstimatedHours: 4,
    examWeightage: 'high',
    difficulty: 'easy',
    prerequisites: ['c9-sst-civ-2'],
    inCbseSyllabus: true,
    topics: [
      { id: 'c9-c5-t1', name: 'Six Fundamental Rights and Right to Constitutional Remedies', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?iess4=5-5`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'c9-sst-eco-1',
    subjectId: 'cbse-9-sst',
    subjectName: 'Social Science',
    subjectCode: '087',
    class: '9',
    academicSession: '2026-27',
    title: 'The Story of Village Palampur',
    chapterNumber: 16,
    unitNumber: 4,
    unitName: 'Economics',
    description: 'Organization of production, farming activities, non-farm activities in Palampur.',
    defaultEstimatedHours: 3,
    examWeightage: 'medium',
    difficulty: 'easy',
    prerequisites: [],
    inCbseSyllabus: true,
    topics: [
      { id: 'c9-e1-t1', name: 'Factors of production: Land, labour, physical capital, human capital', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?iess2=1-4`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'c9-sst-eco-2',
    subjectId: 'cbse-9-sst',
    subjectName: 'Social Science',
    subjectCode: '087',
    class: '9',
    academicSession: '2026-27',
    title: 'People as Resource',
    chapterNumber: 17,
    unitNumber: 4,
    unitName: 'Economics',
    description: 'Economic activities by men and women, quality of population, education, health, unemployment.',
    defaultEstimatedHours: 4,
    examWeightage: 'high',
    difficulty: 'easy',
    prerequisites: ['c9-sst-eco-1'],
    inCbseSyllabus: true,
    topics: [
      { id: 'c9-e2-t1', name: 'Human capital formation, primary/secondary/tertiary sectors, unemployment types', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?iess2=2-4`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'c9-sst-eco-3',
    subjectId: 'cbse-9-sst',
    subjectName: 'Social Science',
    subjectCode: '087',
    class: '9',
    academicSession: '2026-27',
    title: 'Poverty as a Challenge',
    chapterNumber: 18,
    unitNumber: 4,
    unitName: 'Economics',
    description: 'Two typical cases, poverty line, estimates, vulnerable groups, causes, anti-poverty measures.',
    defaultEstimatedHours: 5,
    examWeightage: 'high',
    difficulty: 'medium',
    prerequisites: ['c9-sst-eco-2'],
    inCbseSyllabus: true,
    topics: [
      { id: 'c9-e3-t1', name: 'Poverty line estimation, MGNREGA, and national anti-poverty programmes', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?iess2=3-4`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'c9-sst-eco-4',
    subjectId: 'cbse-9-sst',
    subjectName: 'Social Science',
    subjectCode: '087',
    class: '9',
    academicSession: '2026-27',
    title: 'Food Security in India',
    chapterNumber: 19,
    unitNumber: 4,
    unitName: 'Economics',
    description: 'What is food security, why food security, Public Distribution System (PDS), buffer stock, role of cooperatives.',
    defaultEstimatedHours: 4,
    examWeightage: 'high',
    difficulty: 'medium',
    prerequisites: ['c9-sst-eco-3'],
    inCbseSyllabus: true,
    topics: [
      { id: 'c9-e4-t1', name: 'Buffer stock, MSP, PDS rationing, and cooperative role in food security', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?iess2=4-4`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },

  // Artificial Intelligence (417)
  {
    id: 'c9-ai-emp',
    subjectId: 'cbse-9-ai',
    subjectName: 'Artificial Intelligence',
    subjectCode: '417',
    class: '9',
    academicSession: '2026-27',
    title: 'Employability Skills',
    chapterNumber: 1,
    unitNumber: 1,
    unitName: 'Employability Skills',
    description: 'Communication skills, self-management, basic ICT skills, entrepreneurship, and green skills in the modern economy.',
    defaultEstimatedHours: 4,
    examWeightage: 'medium',
    difficulty: 'easy',
    prerequisites: [],
    inCbseSyllabus: true,
    topics: [
      { id: 'c9-ai-emp-t1', name: 'Communication & Interpersonal Skills', inCbseSyllabus: true },
      { id: 'c9-ai-emp-t2', name: 'ICT Skills: Word Processing, Spreadsheets, and Internet safety', inCbseSyllabus: true },
      { id: 'c9-ai-emp-t3', name: 'Entrepreneurial and Sustainable Green Practices', inCbseSyllabus: true }
    ],
    officialNcertUrl: OFFICIAL_CBSE_SKILL_PORTAL,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SKILL_PORTAL,
  },
  {
    id: 'c9-ai-1',
    subjectId: 'cbse-9-ai',
    subjectName: 'Artificial Intelligence',
    subjectCode: '417',
    class: '9',
    academicSession: '2026-27',
    title: 'Introduction to Artificial Intelligence',
    chapterNumber: 2,
    unitNumber: 2,
    unitName: 'Subject Specific Skills',
    description: 'Foundations of AI, human intelligence vs artificial intelligence, applications in smart cities, healthcare, ethics.',
    defaultEstimatedHours: 4,
    examWeightage: 'high',
    difficulty: 'easy',
    prerequisites: [],
    inCbseSyllabus: true,
    topics: [
      { id: 'c9-ai1-t1', name: 'AI, Machine Learning, Deep Learning distinctions', inCbseSyllabus: true },
      { id: 'c9-ai1-t2', name: 'AI Ethics, Bias, and Data Privacy', inCbseSyllabus: true }
    ],
    officialNcertUrl: OFFICIAL_CBSE_SKILL_PORTAL,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SKILL_PORTAL,
  },
  {
    id: 'c9-ai-2',
    subjectId: 'cbse-9-ai',
    subjectName: 'Artificial Intelligence',
    subjectCode: '417',
    class: '9',
    academicSession: '2026-27',
    title: 'AI Project Cycle',
    chapterNumber: 3,
    unitNumber: 2,
    unitName: 'Subject Specific Skills',
    description: 'Problem Scoping (4Ws canvas), Data Acquisition, Data Exploration, Modelling (Rule-based vs Learning-based), Evaluation.',
    defaultEstimatedHours: 6,
    examWeightage: 'critical',
    difficulty: 'medium',
    prerequisites: ['c9-ai-1'],
    inCbseSyllabus: true,
    topics: [
      { id: 'c9-ai2-t1', name: 'Problem scoping with 4Ws Canvas', inCbseSyllabus: true },
      { id: 'c9-ai2-t2', name: 'Data acquisition, feature extraction, and clean dataset prep', inCbseSyllabus: true }
    ],
    officialNcertUrl: OFFICIAL_CBSE_SKILL_PORTAL,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SKILL_PORTAL,
  },
  {
    id: 'c9-ai-3',
    subjectId: 'cbse-9-ai',
    subjectName: 'Artificial Intelligence',
    subjectCode: '417',
    class: '9',
    academicSession: '2026-27',
    title: 'Neural Networks & Python Programming',
    chapterNumber: 4,
    unitNumber: 2,
    unitName: 'Subject Specific Skills',
    description: 'Biological vs Artificial Neural Networks, input/hidden/output layers, Python variables, lists, conditional statements.',
    defaultEstimatedHours: 7,
    examWeightage: 'critical',
    difficulty: 'hard',
    prerequisites: ['c9-ai-2'],
    inCbseSyllabus: true,
    topics: [
      { id: 'c9-ai3-t1', name: 'Biological and artificial neuron structure', inCbseSyllabus: true },
      { id: 'c9-ai3-t2', name: 'Basic Python syntax, conditions, and loops for data processing', inCbseSyllabus: true }
    ],
    officialNcertUrl: OFFICIAL_CBSE_SKILL_PORTAL,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SKILL_PORTAL,
  },
  {
    id: 'c9-ai-4',
    subjectId: 'cbse-9-ai',
    subjectName: 'Artificial Intelligence',
    subjectCode: '417',
    class: '9',
    academicSession: '2026-27',
    title: 'Computer Vision & Natural Language Processing',
    chapterNumber: 5,
    unitNumber: 2,
    unitName: 'Subject Specific Skills',
    description: 'Introduction to Computer Vision (pixels, RGB, OpenCV basics) and Natural Language Processing (text pre-processing, tokenisation, chatbots).',
    defaultEstimatedHours: 5,
    examWeightage: 'high',
    difficulty: 'medium',
    prerequisites: ['c9-ai-3'],
    inCbseSyllabus: true,
    topics: [
      { id: 'c9-ai4-t1', name: 'Computer Vision: Image representation, resolution, pixels, and edge detection', inCbseSyllabus: true },
      { id: 'c9-ai4-t2', name: 'NLP: Text normalisation, tokenisation, stop words, and sentiment analysis', inCbseSyllabus: true }
    ],
    officialNcertUrl: OFFICIAL_CBSE_SKILL_PORTAL,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SKILL_PORTAL,
  },

  // English Language & Literature (184) - NCERT Rationalised Edition
  {
    id: 'c9-eng-skills',
    subjectId: 'cbse-9-english',
    subjectName: 'English Language & Literature',
    subjectCode: '184',
    class: '9',
    academicSession: '2026-27',
    title: 'Reading Skills & Unseen Passages',
    chapterNumber: 1,
    unitNumber: 1,
    unitName: 'Reading & Writing Skills',
    description: 'Discursive and factual unseen passages with conceptual understanding, inference, vocabulary in context, and analysis.',
    defaultEstimatedHours: 5,
    examWeightage: 'critical',
    difficulty: 'medium',
    prerequisites: [],
    inCbseSyllabus: true,
    topics: [
      { id: 'c9-eng-sk-t1', name: 'Discursive passage analysis (400-450 words)', inCbseSyllabus: true },
      { id: 'c9-eng-sk-t2', name: 'Case-based factual passage with visual input or data', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?iebe1=0-11`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'c9-eng-writing',
    subjectId: 'cbse-9-english',
    subjectName: 'English Language & Literature',
    subjectCode: '184',
    class: '9',
    academicSession: '2026-27',
    title: 'Writing Skills & Integrated Grammar',
    chapterNumber: 2,
    unitNumber: 1,
    unitName: 'Reading & Writing Skills',
    description: 'Descriptive paragraphs (person/event/situation), short story writing, diary entry, tenses, modals, subject-verb concord, reported speech.',
    defaultEstimatedHours: 6,
    examWeightage: 'critical',
    difficulty: 'medium',
    prerequisites: [],
    inCbseSyllabus: true,
    topics: [
      { id: 'c9-eng-wr-t1', name: 'Descriptive paragraph & story writing on given cues', inCbseSyllabus: true },
      { id: 'c9-eng-wr-t2', name: 'Integrated grammar: Gap filling, error correction, dialogue completion', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?iebe1=0-11`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'c9-eng-bh-1',
    subjectId: 'cbse-9-english',
    subjectName: 'English Language & Literature',
    subjectCode: '184',
    class: '9',
    academicSession: '2026-27',
    title: 'Beehive: The Fun They Had & The Road Not Taken',
    chapterNumber: 3,
    unitNumber: 2,
    unitName: 'Beehive (Prose & Poetry)',
    description: 'Futuristic schooling story by Isaac Asimov paired with Robert Frost iconic poem on choices in life.',
    defaultEstimatedHours: 4,
    examWeightage: 'high',
    difficulty: 'easy',
    prerequisites: [],
    inCbseSyllabus: true,
    topics: [
      { id: 'c9-ebh1-t1', name: 'Prose: The Fun They Had - Isaac Asimov', inCbseSyllabus: true },
      { id: 'c9-ebh1-t2', name: 'Poem: The Road Not Taken - Robert Frost', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?iebe1=1-11`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'c9-eng-bh-2',
    subjectId: 'cbse-9-english',
    subjectName: 'English Language & Literature',
    subjectCode: '184',
    class: '9',
    academicSession: '2026-27',
    title: 'Beehive: The Sound of Music & Wind',
    chapterNumber: 4,
    unitNumber: 2,
    unitName: 'Beehive (Prose & Poetry)',
    description: 'Biographical sketches of Evelyn Glennie & Ustad Bismillah Khan alongside Subramania Bharati poem on resilience.',
    defaultEstimatedHours: 5,
    examWeightage: 'high',
    difficulty: 'medium',
    prerequisites: [],
    inCbseSyllabus: true,
    topics: [
      { id: 'c9-ebh2-t1', name: 'Evelyn Glennie listens to sound without hearing it', inCbseSyllabus: true },
      { id: 'c9-ebh2-t2', name: 'The Shehnai of Bismillah Khan', inCbseSyllabus: true },
      { id: 'c9-ebh2-t3', name: 'Poem: Wind - Subramania Bharati', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?iebe1=2-11`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'c9-eng-bh-3',
    subjectId: 'cbse-9-english',
    subjectName: 'English Language & Literature',
    subjectCode: '184',
    class: '9',
    academicSession: '2026-27',
    title: 'Beehive: The Little Girl & Rain on the Roof',
    chapterNumber: 5,
    unitNumber: 2,
    unitName: 'Beehive (Prose & Poetry)',
    description: 'Kezia relationship with her father by Katherine Mansfield and lyrical nostalgia in Coates Kinney poem.',
    defaultEstimatedHours: 4,
    examWeightage: 'medium',
    difficulty: 'easy',
    prerequisites: [],
    inCbseSyllabus: true,
    topics: [
      { id: 'c9-ebh3-t1', name: 'Prose: The Little Girl - Katherine Mansfield', inCbseSyllabus: true },
      { id: 'c9-ebh3-t2', name: 'Poem: Rain on the Roof - Coates Kinney', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?iebe1=3-11`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'c9-eng-bh-4',
    subjectId: 'cbse-9-english',
    subjectName: 'English Language & Literature',
    subjectCode: '184',
    class: '9',
    academicSession: '2026-27',
    title: 'Beehive: A Truly Beautiful Mind & The Lake Isle of Innisfree',
    chapterNumber: 6,
    unitNumber: 2,
    unitName: 'Beehive (Prose & Poetry)',
    description: 'The life and pacifist ideals of Albert Einstein paired with W.B. Yeats musical longing for tranquility.',
    defaultEstimatedHours: 4,
    examWeightage: 'high',
    difficulty: 'easy',
    prerequisites: [],
    inCbseSyllabus: true,
    topics: [
      { id: 'c9-ebh4-t1', name: 'Prose: A Truly Beautiful Mind - Albert Einstein biography', inCbseSyllabus: true },
      { id: 'c9-ebh4-t2', name: 'Poem: The Lake Isle of Innisfree - W.B. Yeats', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?iebe1=4-11`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'c9-eng-bh-5',
    subjectId: 'cbse-9-english',
    subjectName: 'English Language & Literature',
    subjectCode: '184',
    class: '9',
    academicSession: '2026-27',
    title: 'Beehive: The Snake and the Mirror & A Legend of the Northland',
    chapterNumber: 7,
    unitNumber: 2,
    unitName: 'Beehive (Prose & Poetry)',
    description: 'Vaikom Muhammad Basheer comic encounter with a snake paired with Phoebe Cary moral ballad.',
    defaultEstimatedHours: 4,
    examWeightage: 'medium',
    difficulty: 'easy',
    prerequisites: [],
    inCbseSyllabus: true,
    topics: [
      { id: 'c9-ebh5-t1', name: 'Prose: The Snake and the Mirror - Basheer', inCbseSyllabus: true },
      { id: 'c9-ebh5-t2', name: 'Poem: A Legend of the Northland - Phoebe Cary', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?iebe1=5-11`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'c9-eng-bh-6',
    subjectId: 'cbse-9-english',
    subjectName: 'English Language & Literature',
    subjectCode: '184',
    class: '9',
    academicSession: '2026-27',
    title: 'Beehive: My Childhood & No Men Are Foreign',
    chapterNumber: 8,
    unitNumber: 2,
    unitName: 'Beehive (Prose & Poetry)',
    description: 'Dr. A.P.J. Abdul Kalam formative years in Rameswaram and James Kirkup poem advocating universal brotherhood.',
    defaultEstimatedHours: 5,
    examWeightage: 'critical',
    difficulty: 'medium',
    prerequisites: [],
    inCbseSyllabus: true,
    topics: [
      { id: 'c9-ebh6-t1', name: 'Prose: My Childhood - Wings of Fire by A.P.J. Abdul Kalam', inCbseSyllabus: true },
      { id: 'c9-ebh6-t2', name: 'Poem: No Men Are Foreign - James Kirkup', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?iebe1=6-11`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'c9-eng-bh-7',
    subjectId: 'cbse-9-english',
    subjectName: 'English Language & Literature',
    subjectCode: '184',
    class: '9',
    academicSession: '2026-27',
    title: 'Beehive: Reach for the Top & On Killing a Tree',
    chapterNumber: 9,
    unitNumber: 2,
    unitName: 'Beehive (Prose & Poetry)',
    description: 'Courageous journeys of mountaineer Santosh Yadav and tennis champion Maria Sharapova with Gieve Patel environmental poem.',
    defaultEstimatedHours: 5,
    examWeightage: 'high',
    difficulty: 'medium',
    prerequisites: [],
    inCbseSyllabus: true,
    topics: [
      { id: 'c9-ebh7-t1', name: 'Part I: Santosh Yadav & Part II: Maria Sharapova', inCbseSyllabus: true },
      { id: 'c9-ebh7-t2', name: 'Poem: On Killing a Tree - Gieve Patel', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?iebe1=7-11`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'c9-eng-bh-8',
    subjectId: 'cbse-9-english',
    subjectName: 'English Language & Literature',
    subjectCode: '184',
    class: '9',
    academicSession: '2026-27',
    title: 'Beehive: Kathmandu & A Slumber Did My Spirit Seal',
    chapterNumber: 10,
    unitNumber: 2,
    unitName: 'Beehive (Prose & Poetry)',
    description: 'Vikram Seth sensory travelogue of Pashupatinath and Baudhnath paired with William Wordsworth Lucy poem.',
    defaultEstimatedHours: 4,
    examWeightage: 'medium',
    difficulty: 'easy',
    prerequisites: [],
    inCbseSyllabus: true,
    topics: [
      { id: 'c9-ebh8-t1', name: 'Prose: Kathmandu - Vikram Seth (From Heaven Lake)', inCbseSyllabus: true },
      { id: 'c9-ebh8-t2', name: 'Poem: A Slumber Did My Spirit Seal - William Wordsworth', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?iebe1=8-11`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'c9-eng-bh-9',
    subjectId: 'cbse-9-english',
    subjectName: 'English Language & Literature',
    subjectCode: '184',
    class: '9',
    academicSession: '2026-27',
    title: 'Beehive: If I Were You',
    chapterNumber: 11,
    unitNumber: 2,
    unitName: 'Beehive (Prose & Poetry)',
    description: 'Douglas James suspenseful, witty one-act play where playwright Gerrard outsmarts an armed intruder.',
    defaultEstimatedHours: 4,
    examWeightage: 'high',
    difficulty: 'easy',
    prerequisites: [],
    inCbseSyllabus: true,
    topics: [
      { id: 'c9-ebh9-t1', name: 'Play: If I Were You - Douglas James (Wit and presence of mind)', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?iebe1=9-11`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'c9-eng-mom-1',
    subjectId: 'cbse-9-english',
    subjectName: 'English Language & Literature',
    subjectCode: '184',
    class: '9',
    academicSession: '2026-27',
    title: 'Moments: The Lost Child',
    chapterNumber: 12,
    unitNumber: 3,
    unitName: 'Moments (Supplementary Reader)',
    description: 'Mulk Raj Anand heartwarming story exploring a child bond with his parents at a village fair.',
    defaultEstimatedHours: 3,
    examWeightage: 'medium',
    difficulty: 'easy',
    prerequisites: [],
    inCbseSyllabus: true,
    topics: [
      { id: 'c9-emom1-t1', name: 'Child desires vs supreme love and security of parents', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?ieso1=1-8`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'c9-eng-mom-2',
    subjectId: 'cbse-9-english',
    subjectName: 'English Language & Literature',
    subjectCode: '184',
    class: '9',
    academicSession: '2026-27',
    title: 'Moments: The Adventures of Toto',
    chapterNumber: 13,
    unitNumber: 3,
    unitName: 'Moments (Supplementary Reader)',
    description: 'Ruskin Bond amusing tale of grandfather private zoo and an uncontrollable mischievous monkey.',
    defaultEstimatedHours: 3,
    examWeightage: 'medium',
    difficulty: 'easy',
    prerequisites: [],
    inCbseSyllabus: true,
    topics: [
      { id: 'c9-emom2-t1', name: 'Mischief and comic escapades of pet monkey Toto', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?ieso1=2-8`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'c9-eng-mom-3',
    subjectId: 'cbse-9-english',
    subjectName: 'English Language & Literature',
    subjectCode: '184',
    class: '9',
    academicSession: '2026-27',
    title: 'Moments: Iswaran the Storyteller',
    chapterNumber: 14,
    unitNumber: 3,
    unitName: 'Moments (Supplementary Reader)',
    description: 'R.K. Laxman delightful story about a cook who mesmerises his master with vivid dramatic tales.',
    defaultEstimatedHours: 3,
    examWeightage: 'medium',
    difficulty: 'easy',
    prerequisites: [],
    inCbseSyllabus: true,
    topics: [
      { id: 'c9-emom3-t1', name: 'Art of storytelling, suspense, and phantom encounters', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?ieso1=3-8`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'c9-eng-mom-4',
    subjectId: 'cbse-9-english',
    subjectName: 'English Language & Literature',
    subjectCode: '184',
    class: '9',
    academicSession: '2026-27',
    title: 'Moments: In the Kingdom of Fools',
    chapterNumber: 15,
    unitNumber: 3,
    unitName: 'Moments (Supplementary Reader)',
    description: 'Kannada folktale adapted by A.K. Ramanujan illustrating why dealing with foolish rulers is perilous.',
    defaultEstimatedHours: 3,
    examWeightage: 'high',
    difficulty: 'easy',
    prerequisites: [],
    inCbseSyllabus: true,
    topics: [
      { id: 'c9-emom4-t1', name: 'Guru wisdom and saving disciple in an absurd realm', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?ieso1=4-8`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'c9-eng-mom-5',
    subjectId: 'cbse-9-english',
    subjectName: 'English Language & Literature',
    subjectCode: '184',
    class: '9',
    academicSession: '2026-27',
    title: 'Moments: The Happy Prince',
    chapterNumber: 16,
    unitNumber: 3,
    unitName: 'Moments (Supplementary Reader)',
    description: 'Oscar Wilde moving parable on sacrifice, true compassion, and selfless giving.',
    defaultEstimatedHours: 4,
    examWeightage: 'high',
    difficulty: 'easy',
    prerequisites: [],
    inCbseSyllabus: true,
    topics: [
      { id: 'c9-emom5-t1', name: 'Sacrifice of the statue and little swallow for poor people', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?ieso1=5-8`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'c9-eng-mom-6',
    subjectId: 'cbse-9-english',
    subjectName: 'English Language & Literature',
    subjectCode: '184',
    class: '9',
    academicSession: '2026-27',
    title: 'Moments: The Last Leaf',
    chapterNumber: 17,
    unitNumber: 3,
    unitName: 'Moments (Supplementary Reader)',
    description: 'O. Henry poignant narrative of hope, friendship, and artist Behrman final supreme masterpiece.',
    defaultEstimatedHours: 4,
    examWeightage: 'critical',
    difficulty: 'easy',
    prerequisites: [],
    inCbseSyllabus: true,
    topics: [
      { id: 'c9-emom6-t1', name: 'Will to survive, psychological hope, and Behrman sacrifice', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?ieso1=6-8`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'c9-eng-mom-7',
    subjectId: 'cbse-9-english',
    subjectName: 'English Language & Literature',
    subjectCode: '184',
    class: '9',
    academicSession: '2026-27',
    title: 'Moments: A House Is Not a Home',
    chapterNumber: 18,
    unitNumber: 3,
    unitName: 'Moments (Supplementary Reader)',
    description: 'Zan Gaudioso autobiographical account of devastating loss by fire, community kindness, and rebuilding life.',
    defaultEstimatedHours: 3,
    examWeightage: 'medium',
    difficulty: 'easy',
    prerequisites: [],
    inCbseSyllabus: true,
    topics: [
      { id: 'c9-emom7-t1', name: 'Dealing with trauma, loneliness, and emotional healing', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?ieso1=7-8`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'c9-eng-mom-8',
    subjectId: 'cbse-9-english',
    subjectName: 'English Language & Literature',
    subjectCode: '184',
    class: '9',
    academicSession: '2026-27',
    title: 'Moments: The Beggar',
    chapterNumber: 19,
    unitNumber: 3,
    unitName: 'Moments (Supplementary Reader)',
    description: 'Anton Chekhov classic on alcoholism, redemption, and cook Olga silent transforming compassion.',
    defaultEstimatedHours: 3,
    examWeightage: 'high',
    difficulty: 'easy',
    prerequisites: [],
    inCbseSyllabus: true,
    topics: [
      { id: 'c9-emom8-t1', name: 'Transformation of Lushkoff through genuine empathy', inCbseSyllabus: true }
    ],
    officialNcertUrl: `${OFFICIAL_NCERT_PORTAL}?ieso1=8-8`,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },

  // Hindi Course A (002) - NCERT Rationalised Edition
  {
    id: 'c9-hin-vyakaran',
    subjectId: 'cbse-9-hindi-a',
    subjectName: 'Hindi Course A',
    subjectCode: '002',
    class: '9',
    academicSession: '2026-27',
    title: 'हिंदी व्याकरण (व्यावहारिक व्याकरण)',
    chapterNumber: 1,
    unitNumber: 1,
    unitName: 'अपठित बोध, व्याकरण एवं रचना',
    description: 'उपसर्ग और प्रत्यय, समास (तत्पुरुष, द्विगु, द्वंद्व, कर्मधारय, बहुव्रीहि, अव्ययीभाव), अर्थ की दृष्टि से वाक्य भेद, अलंकार।',
    defaultEstimatedHours: 6,
    examWeightage: 'critical',
    difficulty: 'medium',
    prerequisites: [],
    inCbseSyllabus: true,
    topics: [
      { id: 'c9-hvy-t1', name: 'उपसर्ग और प्रत्यय निर्माण एवं अभ्यास', inCbseSyllabus: true },
      { id: 'c9-hvy-t2', name: 'समास विग्रह एवं प्रकार', inCbseSyllabus: true },
      { id: 'c9-hvy-t3', name: 'अर्थ की दृष्टि से वाक्य भेद (8 प्रकार) व रूपांतरण', inCbseSyllabus: true },
      { id: 'c9-hvy-t4', name: 'अलंकार: शब्दालंकार (अनुप्रास, यमक) व अर्थालंकार (उपमा, रूपक, उत्प्रेक्षा, अतिशयोक्ति, मानवीकरण)', inCbseSyllabus: true }
    ],
    officialNcertUrl: OFFICIAL_NCERT_PORTAL,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'c9-hin-rachana',
    subjectId: 'cbse-9-hindi-a',
    subjectName: 'Hindi Course A',
    subjectCode: '002',
    class: '9',
    academicSession: '2026-27',
    title: 'अपठित बोध एवं रचनात्मक लेखन',
    chapterNumber: 2,
    unitNumber: 1,
    unitName: 'अपठित बोध, व्याकरण एवं रचना',
    description: 'अपठित गद्यांश व काव्यांश बोध, संकेत बिंदुओं पर अनुच्छेद लेखन, औपचारिक/अनौपचारिक पत्र, संवाद लेखन व ई-मेल लेखन।',
    defaultEstimatedHours: 5,
    examWeightage: 'high',
    difficulty: 'easy',
    prerequisites: [],
    inCbseSyllabus: true,
    topics: [
      { id: 'c9-hra-t1', name: 'अपठित गद्यांश व पद्यांश पर आधारित प्रश्नोत्तरी', inCbseSyllabus: true },
      { id: 'c9-hra-t2', name: 'अनुच्छेद लेखन, पत्र लेखन, संवाद एवं ई-मेल लेखन प्रारूप', inCbseSyllabus: true }
    ],
    officialNcertUrl: OFFICIAL_NCERT_PORTAL,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'c9-hin-ksh-1',
    subjectId: 'cbse-9-hindi-a',
    subjectName: 'Hindi Course A',
    subjectCode: '002',
    class: '9',
    academicSession: '2026-27',
    title: 'क्षितिज: दो बैलों की कथा (प्रेमचंद)',
    chapterNumber: 3,
    unitNumber: 2,
    unitName: 'क्षितिज भाग 1 (गद्य एवं काव्य)',
    description: 'हीरा और मोती के माध्यम से प्रेमचंद की किसान जीवन, निष्ठा, आजादी की चाह और स्वाभिमान पर कालजयी कहानी।',
    defaultEstimatedHours: 4,
    examWeightage: 'critical',
    difficulty: 'easy',
    prerequisites: [],
    inCbseSyllabus: true,
    topics: [
      { id: 'c9-hksh1-t1', name: 'हीरा-मोती की मित्रता, गया के घर से पलायन व कांजीहौस प्रसंग', inCbseSyllabus: true }
    ],
    officialNcertUrl: OFFICIAL_NCERT_PORTAL,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'c9-hin-ksh-2',
    subjectId: 'cbse-9-hindi-a',
    subjectName: 'Hindi Course A',
    subjectCode: '002',
    class: '9',
    academicSession: '2026-27',
    title: 'क्षितिज: ल्हासा की ओर (राहुल सांकृत्यायन)',
    chapterNumber: 4,
    unitNumber: 2,
    unitName: 'क्षितिज भाग 1 (गद्य एवं काव्य)',
    description: 'तिब्बत यात्रा का रोचक वृत्तांत, सामाजिक संरचना, डांडे का डाकू भय, और सुमति का साथ।',
    defaultEstimatedHours: 4,
    examWeightage: 'high',
    difficulty: 'medium',
    prerequisites: [],
    inCbseSyllabus: true,
    topics: [
      { id: 'c9-hksh2-t1', name: 'तिब्बत यात्रा वृत्तांत, डांडे का मार्ग, भिक्षु वेश और तिब्बती समाज', inCbseSyllabus: true }
    ],
    officialNcertUrl: OFFICIAL_NCERT_PORTAL,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'c9-hin-ksh-3',
    subjectId: 'cbse-9-hindi-a',
    subjectName: 'Hindi Course A',
    subjectCode: '002',
    class: '9',
    academicSession: '2026-27',
    title: 'क्षितिज: उपभोक्तावाद की संस्कृति (श्यामाचरण दुबे)',
    chapterNumber: 5,
    unitNumber: 2,
    unitName: 'क्षितिज भाग 1 (गद्य एवं काव्य)',
    description: 'विज्ञापन संस्कृति, दिखावे की अंधी दौड़, और भारतीय सामाजिक जीवन पर उपभोक्तावाद के दुष्प्रभाव का विश्लेषण।',
    defaultEstimatedHours: 3,
    examWeightage: 'medium',
    difficulty: 'medium',
    prerequisites: [],
    inCbseSyllabus: true,
    topics: [
      { id: 'c9-hksh3-t1', name: 'उपभोक्तावाद, विज्ञापनों का मायाजाल व सामाजिक सरोकारों का ह्रास', inCbseSyllabus: true }
    ],
    officialNcertUrl: OFFICIAL_NCERT_PORTAL,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'c9-hin-ksh-4',
    subjectId: 'cbse-9-hindi-a',
    subjectName: 'Hindi Course A',
    subjectCode: '002',
    class: '9',
    academicSession: '2026-27',
    title: 'क्षितिज: सांवले सपनों की याद (जाबिर हुसैन)',
    chapterNumber: 6,
    unitNumber: 2,
    unitName: 'क्षितिज भाग 1 (गद्य एवं काव्य)',
    description: 'प्रसिद्ध पक्षी विज्ञानी सालिम अली के जीवन, पर्यावरण चेतना और पक्षी संरक्षण पर भावपूर्ण संस्मरण।',
    defaultEstimatedHours: 4,
    examWeightage: 'high',
    difficulty: 'medium',
    prerequisites: [],
    inCbseSyllabus: true,
    topics: [
      { id: 'c9-hksh4-t1', name: 'सालिम अली का पक्षी प्रेम, साइलेंट वैली प्रसंग व पर्यावरण संदेश', inCbseSyllabus: true }
    ],
    officialNcertUrl: OFFICIAL_NCERT_PORTAL,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'c9-hin-ksh-5',
    subjectId: 'cbse-9-hindi-a',
    subjectName: 'Hindi Course A',
    subjectCode: '002',
    class: '9',
    academicSession: '2026-27',
    title: 'क्षितिज: प्रेमचंद के फटे जूते (हरिशंकर परसाई)',
    chapterNumber: 7,
    unitNumber: 2,
    unitName: 'क्षितिज भाग 1 (गद्य एवं काव्य)',
    description: 'दिखावे की प्रवृत्ति पर व्यंग्य, प्रेमचंद का सादगीपूर्ण यथार्थवादी जीवन और सामाजिक विसंगतियों पर कटाक्ष।',
    defaultEstimatedHours: 4,
    examWeightage: 'critical',
    difficulty: 'easy',
    prerequisites: [],
    inCbseSyllabus: true,
    topics: [
      { id: 'c9-hksh5-t1', name: 'प्रेमचंद का व्यक्तित्व, व्यंग्य कला और सामाजिक कुरीतियों पर प्रहार', inCbseSyllabus: true }
    ],
    officialNcertUrl: OFFICIAL_NCERT_PORTAL,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'c9-hin-ksh-6',
    subjectId: 'cbse-9-hindi-a',
    subjectName: 'Hindi Course A',
    subjectCode: '002',
    class: '9',
    academicSession: '2026-27',
    title: 'क्षितिज: मेरे बचपन के दिन (महादेवी वर्मा)',
    chapterNumber: 8,
    unitNumber: 2,
    unitName: 'क्षितिज भाग 1 (गद्य एवं काव्य)',
    description: 'महादेवी वर्मा के बचपन के संस्मरण, क्रास्थवेट गर्ल्स कॉलेज के दिन, सुभद्रा कुमारी चौहान की संगति और गांधीजी से भेंट।',
    defaultEstimatedHours: 3,
    examWeightage: 'medium',
    difficulty: 'easy',
    prerequisites: [],
    inCbseSyllabus: true,
    topics: [
      { id: 'c9-hksh6-t1', name: 'स्त्री शिक्षा का परिवेश, सांप्रदायिक सौहार्द व कविता लेखन के आरंभिक दिन', inCbseSyllabus: true }
    ],
    officialNcertUrl: OFFICIAL_NCERT_PORTAL,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'c9-hin-ksh-7',
    subjectId: 'cbse-9-hindi-a',
    subjectName: 'Hindi Course A',
    subjectCode: '002',
    class: '9',
    academicSession: '2026-27',
    title: 'क्षितिज काव्य: साखियां एवं सबद (कबीर) व वाख (ललद्यद)',
    chapterNumber: 9,
    unitNumber: 2,
    unitName: 'क्षितिज भाग 1 (गद्य एवं काव्य)',
    description: 'कबीरदास के नीतिपरक दोहे, गुरु महिमा, अहंकार त्याग तथा कश्मीरी संत कवयित्री ललद्यद की भक्तिपरक वाख रचनाएं।',
    defaultEstimatedHours: 4,
    examWeightage: 'critical',
    difficulty: 'medium',
    prerequisites: [],
    inCbseSyllabus: true,
    topics: [
      { id: 'c9-hksh7-t1', name: 'कबीर की साखियां व प्रथम पद (मोको कहाँ ढूँढे रे बन्दे)', inCbseSyllabus: true },
      { id: 'c9-hksh7-t2', name: 'ललद्यद के वाख: कच्चे धागे की नाव व आत्मज्ञान का महत्व', inCbseSyllabus: true }
    ],
    officialNcertUrl: OFFICIAL_NCERT_PORTAL,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'c9-hin-ksh-8',
    subjectId: 'cbse-9-hindi-a',
    subjectName: 'Hindi Course A',
    subjectCode: '002',
    class: '9',
    academicSession: '2026-27',
    title: 'क्षितिज काव्य: सवैये, कैदी और कोकिला, मेघ आए व बच्चे काम पर जा रहे हैं',
    chapterNumber: 10,
    unitNumber: 2,
    unitName: 'क्षितिज भाग 1 (गद्य एवं काव्य)',
    description: 'रसखान के कृष्ण प्रेम के सवैये, माखनलाल चतुर्वेदी की स्वाधीनता चेतना, मेघ आए में मानवीकरण तथा बालश्रम पर राजेश जोशी की मार्मिक कविता।',
    defaultEstimatedHours: 6,
    examWeightage: 'critical',
    difficulty: 'medium',
    prerequisites: [],
    inCbseSyllabus: true,
    topics: [
      { id: 'c9-hksh8-t1', name: 'रसखान के सवैये (मानुष हौं तो वही रसखानि)', inCbseSyllabus: true },
      { id: 'c9-hksh8-t2', name: 'कैदी और कोकिला: स्वतंत्रता सेनानियों की जेल यंत्रणा', inCbseSyllabus: true },
      { id: 'c9-hksh8-t3', name: 'मेघ आए (प्रकृति मानवीकरण) व बच्चे काम पर जा रहे हैं (बालश्रम की भयावहता)', inCbseSyllabus: true }
    ],
    officialNcertUrl: OFFICIAL_NCERT_PORTAL,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'c9-hin-krt-1',
    subjectId: 'cbse-9-hindi-a',
    subjectName: 'Hindi Course A',
    subjectCode: '002',
    class: '9',
    academicSession: '2026-27',
    title: 'कृतिका: इस जल प्रलय में (फणीश्वरनाथ "रेणु")',
    chapterNumber: 11,
    unitNumber: 3,
    unitName: 'कृतिका भाग 1',
    description: '1975 की पटना बाढ़ का आंखों देखा सजीव रिपोर्ताज, मानवीय त्रासदी और संकट काल में जनजीवन।',
    defaultEstimatedHours: 3,
    examWeightage: 'high',
    difficulty: 'easy',
    prerequisites: [],
    inCbseSyllabus: true,
    topics: [
      { id: 'c9-hkrt1-t1', name: 'बाढ़ की विभीषिका, रिपोर्ताज विधा और आपदा प्रबंधन का यथार्थ', inCbseSyllabus: true }
    ],
    officialNcertUrl: OFFICIAL_NCERT_PORTAL,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'c9-hin-krt-2',
    subjectId: 'cbse-9-hindi-a',
    subjectName: 'Hindi Course A',
    subjectCode: '002',
    class: '9',
    academicSession: '2026-27',
    title: 'कृतिका: मेरे संग की औरतें (मृदुला गर्ग)',
    chapterNumber: 12,
    unitNumber: 3,
    unitName: 'कृतिका भाग 1',
    description: 'पारिवारिक पृष्ठभूमि, नानी, दादी, मां और बहनों के लीक से हटकर जीने वाले प्रेरक संस्मरण।',
    defaultEstimatedHours: 3,
    examWeightage: 'medium',
    difficulty: 'easy',
    prerequisites: [],
    inCbseSyllabus: true,
    topics: [
      { id: 'c9-hkrt2-t1', name: 'स्वतंत्र विचार वाली महिलाओं के चरित्र और सामाजिक रूढ़ि भंजन', inCbseSyllabus: true }
    ],
    officialNcertUrl: OFFICIAL_NCERT_PORTAL,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'c9-hin-krt-3',
    subjectId: 'cbse-9-hindi-a',
    subjectName: 'Hindi Course A',
    subjectCode: '002',
    class: '9',
    academicSession: '2026-27',
    title: 'कृतिका: रीढ़ की हड्डी (जगदीशचंद्र माथुर)',
    chapterNumber: 13,
    unitNumber: 3,
    unitName: 'कृतिका भाग 1',
    description: 'स्त्री शिक्षा और समाज में दोहरे मानदंडों पर प्रहार करने वाला एकांकी, उमा का तेजस्वी प्रतिवाद।',
    defaultEstimatedHours: 4,
    examWeightage: 'critical',
    difficulty: 'easy',
    prerequisites: [],
    inCbseSyllabus: true,
    topics: [
      { id: 'c9-hkrt3-t1', name: 'एकांकी विश्लेषण, उमा का स्वाभिमान और दकियानूसी विवाह मानसिकता का पर्दाफाश', inCbseSyllabus: true }
    ],
    officialNcertUrl: OFFICIAL_NCERT_PORTAL,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },

  // Bengali (005) - CBSE Class 9 Official Curriculum
  {
    id: 'c9-ben-grammar',
    subjectId: 'cbse-9-bengali',
    subjectName: 'Bengali (বাংলা)',
    subjectCode: '005',
    class: '9',
    academicSession: '2026-27',
    title: 'বোধ পরীক্ষণ ও বাংলা ব্যাকরণ (Comprehension & Grammar)',
    chapterNumber: 1,
    unitNumber: 1,
    unitName: 'বোধ পরীক্ষণ ও ব্যাকরণ (Reading & Grammar)',
    description: 'অপঠিত গদ্যাংশ বোধ, সমাস (দ্বিগু, তৎপুরুষ, বহুব্রীহি), বাক্য রূপান্তর (নির্দেশক, প্রশ্নসূচক, বিস্ময়বোধক, অনুজ্ঞাসূচক, অস্থ্যর্থক, নঞর্থক), সন্ধি ও অশুদ্ধি সংশোধন।',
    defaultEstimatedHours: 6,
    examWeightage: 'critical',
    difficulty: 'medium',
    prerequisites: [],
    inCbseSyllabus: true,
    topics: [
      { id: 'c9-bg-t1', name: 'অপঠিত গদ্যাংশ বোধ ও তথ্যভিত্তিক প্রশ্নোত্তরী', inCbseSyllabus: true },
      { id: 'c9-bg-t2', name: 'সমাস: দ্বিগু, তৎপুরুষ ও বহুব্রীহি সমাস নির্ণয়', inCbseSyllabus: true },
      { id: 'c9-bg-t3', name: 'বাক্য রূপান্তর ও বাক্যের গঠনগত শ্রেণীবিভাগ', inCbseSyllabus: true },
      { id: 'c9-bg-t4', name: 'সন্ধি ও বানান/শব্দগত ও বাক্যগত অশুদ্ধি সংশোধন', inCbseSyllabus: true }
    ],
    officialNcertUrl: OFFICIAL_NCERT_PORTAL,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'c9-ben-writing',
    subjectId: 'cbse-9-bengali',
    subjectName: 'Bengali (বাংলা)',
    subjectCode: '005',
    class: '9',
    academicSession: '2026-27',
    title: 'নির্মিতি ও রচনা (Writing Skills & Composition)',
    chapterNumber: 2,
    unitNumber: 2,
    unitName: 'নির্মিতি ও রচনা (Writing Skills)',
    description: 'প্রতিবেদন রচনা (Report Writing - ১২০-১৫০ শব্দ), বিজ্ঞপ্তি লিখন (Notice Writing), ও বিষয়ভিত্তিক অনুচ্ছেদ রচনা।',
    defaultEstimatedHours: 5,
    examWeightage: 'high',
    difficulty: 'easy',
    prerequisites: [],
    inCbseSyllabus: true,
    topics: [
      { id: 'c9-bw-t1', name: 'প্রতিবেদন রচনা: বিদ্যালয় ও সামাজিক ঘটনাবলী বিষয়ক ফরম্যাট', inCbseSyllabus: true },
      { id: 'c9-bw-t2', name: 'বিজ্ঞপ্তি লিখন ও অনুচ্ছেদ রচনার মূল কৌশল', inCbseSyllabus: true }
    ],
    officialNcertUrl: OFFICIAL_NCERT_PORTAL,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'c9-ben-prose-1',
    subjectId: 'cbse-9-bengali',
    subjectName: 'Bengali (বাংলা)',
    subjectCode: '005',
    class: '9',
    academicSession: '2026-27',
    title: 'সাহিত্য সঞ্চয়ন গদ্য: "ছুটি" (রবীন্দ্রনাথ ঠাকুর)',
    chapterNumber: 3,
    unitNumber: 3,
    unitName: 'সাহিত্য সঞ্চয়ন - গদ্য ও পদ্য (Literature: Prose & Poetry)',
    description: 'ফটিক চক্রবর্তীর বাল্যজীবনের দুরন্তপনা, কলকাতা নগরীতে বন্দিদশা, মাতৃহৃদয়ের আকাঙ্ক্ষা ও করুণ আত্মত্যাগ।',
    defaultEstimatedHours: 4,
    examWeightage: 'critical',
    difficulty: 'medium',
    prerequisites: [],
    inCbseSyllabus: true,
    topics: [
      { id: 'c9-bp1-t1', name: 'ফটিকের চরিত্র, পল্লীপ্রকৃতির টান ও পরিণতি বিশ্লেষণ', inCbseSyllabus: true }
    ],
    officialNcertUrl: OFFICIAL_NCERT_PORTAL,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'c9-ben-prose-2',
    subjectId: 'cbse-9-bengali',
    subjectName: 'Bengali (বাংলা)',
    subjectCode: '005',
    class: '9',
    academicSession: '2026-27',
    title: 'সাহিত্য সঞ্চয়ন গদ্য: "ইলিয়াস" (লিও তলস্তয়)',
    chapterNumber: 4,
    unitNumber: 3,
    unitName: 'সাহিত্য সঞ্চয়ন - গদ্য ও পদ্য (Literature: Prose & Poetry)',
    description: 'বিত্তবৈভবের অনিত্যতা, সর্বস্ব হারিয়ে শান্ত ও প্রকৃত সুখের সন্ধান পাওয়ার দার্শনিক গল্প।',
    defaultEstimatedHours: 3,
    examWeightage: 'high',
    difficulty: 'easy',
    prerequisites: [],
    inCbseSyllabus: true,
    topics: [
      { id: 'c9-bp2-t1', name: 'ইলিয়াস ও শামশেমাগির জীবন দর্শন এবং প্রকৃত সুখের ধারণা', inCbseSyllabus: true }
    ],
    officialNcertUrl: OFFICIAL_NCERT_PORTAL,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'c9-ben-prose-3',
    subjectId: 'cbse-9-bengali',
    subjectName: 'Bengali (বাংলা)',
    subjectCode: '005',
    class: '9',
    academicSession: '2026-27',
    title: 'সাহিত্য সঞ্চয়ন গদ্য: "দাম" (নারায়ণ গঙ্গোপাধ্যায়)',
    chapterNumber: 5,
    unitNumber: 3,
    unitName: 'সাহিত্য সঞ্চয়ন - গদ্য ও পদ্য (Literature: Prose & Poetry)',
    description: 'অঙ্কের মাস্টারমশাই ও সুকুমারের ছাত্রজীবনের স্মৃতিচারণ, গুরু-শিষ্যের অন্তহীন ঋণ ও অপূর্ণ অনুশোচনা।',
    defaultEstimatedHours: 4,
    examWeightage: 'critical',
    difficulty: 'medium',
    prerequisites: [],
    inCbseSyllabus: true,
    topics: [
      { id: 'c9-bp3-t1', name: 'সুকুমারের আত্মোপলব্ধি, মাস্টারমশাইয়ের চরিত্র ও স্নেহের অমূল্য মর্যাদা', inCbseSyllabus: true }
    ],
    officialNcertUrl: OFFICIAL_NCERT_PORTAL,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'c9-ben-prose-4',
    subjectId: 'cbse-9-bengali',
    subjectName: 'Bengali (বাংলা)',
    subjectCode: '005',
    class: '9',
    academicSession: '2026-27',
    title: 'সাহিত্য সঞ্চয়ন গদ্য: "চিঠি" (স্বামী বিবেকানন্দ)',
    chapterNumber: 6,
    unitNumber: 3,
    unitName: 'সাহিত্য সঞ্চয়ন - গদ্য ও পদ্য (Literature: Prose & Poetry)',
    description: 'মিসেস সেভিয়ার ও মিস নোবল (ভগিনী নিবেদিতা)-কে লিখিত পত্র, ভারত সেবায় আত্মনিয়োগের আহ্বান ও পথনির্দেশ।',
    defaultEstimatedHours: 3,
    examWeightage: 'high',
    difficulty: 'easy',
    prerequisites: [],
    inCbseSyllabus: true,
    topics: [
      { id: 'c9-bp4-t1', name: 'নিবেদিতার প্রতি স্বামীজির সতর্কবাণী, ভারতীয় সমাজ ও সেবাব্রতের আদর্শ', inCbseSyllabus: true }
    ],
    officialNcertUrl: OFFICIAL_NCERT_PORTAL,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'c9-ben-poem-1',
    subjectId: 'cbse-9-bengali',
    subjectName: 'Bengali (বাংলা)',
    subjectCode: '005',
    class: '9',
    academicSession: '2026-27',
    title: 'সাহিত্য সঞ্চয়ন পদ্য: "খেয়া" (রবীন্দ্রনাথ ঠাকুর)',
    chapterNumber: 7,
    unitNumber: 3,
    unitName: 'সাহিত্য সঞ্চয়ন - গদ্য ও পদ্য (Literature: Prose & Poetry)',
    description: 'নশ্বর সাম্রাজ্যের উত্থান-পতনের বিপরীতে চিরন্তন গ্রামীণ জীবনধারা ও মানবিক সম্পর্কের অমর আবহমানতা।',
    defaultEstimatedHours: 3,
    examWeightage: 'critical',
    difficulty: 'medium',
    prerequisites: [],
    inCbseSyllabus: true,
    topics: [
      { id: 'c9-bpm1-t1', name: 'সাম্রাজ্য জয়-পরাজয়ের নশ্বরতা বনাম খেয়ানৌকার শাশ্বত জীবনযাত্রা', inCbseSyllabus: true }
    ],
    officialNcertUrl: OFFICIAL_NCERT_PORTAL,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'c9-ben-poem-2',
    subjectId: 'cbse-9-bengali',
    subjectName: 'Bengali (বাংলা)',
    subjectCode: '005',
    class: '9',
    academicSession: '2026-27',
    title: 'সাহিত্য সঞ্চয়ন পদ্য: "ব্যথার বাঁশী" (জসীমউদ্দীন)',
    chapterNumber: 8,
    unitNumber: 3,
    unitName: 'সাহিত্য সঞ্চয়ন - গদ্য ও পদ্য (Literature: Prose & Poetry)',
    description: 'পল্লীকবির সুরধ্বনিত কাব্য, গ্রামীণ মানুষের বেদনার সুর এবং প্রকৃতির সুরে মিশে থাকা জীবনগাথা।',
    defaultEstimatedHours: 3,
    examWeightage: 'high',
    difficulty: 'easy',
    prerequisites: [],
    inCbseSyllabus: true,
    topics: [
      { id: 'c9-bpm2-t1', name: 'পল্লীপ্রকৃতি ও সাধারণ মানুষের হৃদয়ের গভীর আর্তি ও সুর', inCbseSyllabus: true }
    ],
    officialNcertUrl: OFFICIAL_NCERT_PORTAL,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'c9-ben-poem-3',
    subjectId: 'cbse-9-bengali',
    subjectName: 'Bengali (বাংলা)',
    subjectCode: '005',
    class: '9',
    academicSession: '2026-27',
    title: 'সাহিত্য সঞ্চয়ন পদ্য: "এই জীবন" (সুনীল গঙ্গোপাধ্যায়)',
    chapterNumber: 9,
    unitNumber: 3,
    unitName: 'সাহিত্য সঞ্চয়ন - গদ্য ও পদ্য (Literature: Prose & Poetry)',
    description: 'জীবনের প্রতিটি অনুভূতি, দুঃখ-কষ্ট, আলো-আঁধারকে পরম মমতায় আলিঙ্গন করার আধুনিক কাব্যানুভূতি।',
    defaultEstimatedHours: 3,
    examWeightage: 'high',
    difficulty: 'easy',
    prerequisites: [],
    inCbseSyllabus: true,
    topics: [
      { id: 'c9-bpm3-t1', name: 'আধুনিক জীবনবোধ, মানবিক আকাঙ্ক্ষা ও জীবনের সামগ্রিক মূল্যায়ন', inCbseSyllabus: true }
    ],
    officialNcertUrl: OFFICIAL_NCERT_PORTAL,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'c9-ben-poem-4',
    subjectId: 'cbse-9-bengali',
    subjectName: 'Bengali (বাংলা)',
    subjectCode: '005',
    class: '9',
    academicSession: '2026-27',
    title: 'সাহিত্য সঞ্চয়ন পদ্য: "জন্মভূমি আজ" (বীরেন্দ্র চট্টোপাধ্যায়)',
    chapterNumber: 10,
    unitNumber: 3,
    unitName: 'সাহিত্য সঞ্চয়ন - গদ্য ও পদ্য (Literature: Prose & Poetry)',
    description: 'স্বদেশের দুরবস্থায় কবির সংক্ষুব্ধ হৃদয়, সামাজিক অসঙ্গতির প্রতিবাদ এবং মুক্তির উদাত্ত আহ্বান।',
    defaultEstimatedHours: 3,
    examWeightage: 'medium',
    difficulty: 'medium',
    prerequisites: [],
    inCbseSyllabus: true,
    topics: [
      { id: 'c9-bpm4-t1', name: 'দেশপ্রেম, স্বদেশীয় ক্ষোভ এবং নবজাগরণের চেতনা', inCbseSyllabus: true }
    ],
    officialNcertUrl: OFFICIAL_NCERT_PORTAL,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'c9-ben-supp-1',
    subjectId: 'cbse-9-bengali',
    subjectName: 'Bengali (বাংলা)',
    subjectCode: '005',
    class: '9',
    academicSession: '2026-27',
    title: 'আম আঁটির ভেঁপু (সহায়ক পাঠ - পর্ব ১: নিশ্চিন্দিপুরের শৈশব)',
    chapterNumber: 11,
    unitNumber: 4,
    unitName: 'সহায়ক পাঠ - আম আঁটির ভেঁপু (Supplementary Reader)',
    description: 'বিভূতিভূষণ বন্দ্যোপাধ্যায়ের ক্লাসিক উপন্যাস: নিশ্চিন্দিপুর গ্রামে হরিহর-সর্বজয়ার সংসার, অপু-দুর্গার বাঁধনহারা শৈশব ও বনভোজন।',
    defaultEstimatedHours: 5,
    examWeightage: 'critical',
    difficulty: 'medium',
    prerequisites: [],
    inCbseSyllabus: true,
    topics: [
      { id: 'c9-bs1-t1', name: 'অপু ও দুর্গার পারস্পরিক স্নেহ ও নির্ভেজাল প্রকৃতি পাঠ', inCbseSyllabus: true },
      { id: 'c9-bs1-t2', name: 'নিশ্চিন্দিপুরের পল্লীজীবন, দৈন্যদশা ও উৎসবের আনন্দ', inCbseSyllabus: true }
    ],
    officialNcertUrl: OFFICIAL_NCERT_PORTAL,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },
  {
    id: 'c9-ben-supp-2',
    subjectId: 'cbse-9-bengali',
    subjectName: 'Bengali (বাংলা)',
    subjectCode: '005',
    class: '9',
    academicSession: '2026-27',
    title: 'আম আঁটির ভেঁপু (সহায়ক পাঠ - পর্ব ২: রেলের লাইন ও অভিযাত্রা)',
    chapterNumber: 12,
    unitNumber: 4,
    unitName: 'সহায়ক পাঠ - আম আঁটির ভেঁপু (Supplementary Reader)',
    description: 'কাশবনে রেলের লাইন দেখার রোমাঞ্চ, অকালবৃষ্টিতে দুর্গার জ্বর ও প্রয়াণ, এবং নিশ্চিন্দিপুর ত্যাগ করে কাশীযাত্রা।',
    defaultEstimatedHours: 5,
    examWeightage: 'critical',
    difficulty: 'medium',
    prerequisites: ['c9-ben-supp-1'],
    inCbseSyllabus: true,
    topics: [
      { id: 'c9-bs2-t1', name: 'রেলগাড়ির বিস্ময়, মানবমনের অপূর্ণ স্বপ্নের প্রতীক', inCbseSyllabus: true },
      { id: 'c9-bs2-t2', name: 'দুর্গার বিয়োগান্তক প্রয়াণ ও নিশ্চিন্দিপুর থেকে বিদায়', inCbseSyllabus: true }
    ],
    officialNcertUrl: OFFICIAL_NCERT_PORTAL,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SYLLABUS_PORTAL,
  },

  // Vocational Education (Kaushal Vikas / कौशल विकास) (444) - Mandatory NEP 2020 / NCF-SE 2023
  {
    id: 'c9-kv-1',
    subjectId: 'cbse-9-kaushal-vikas',
    subjectName: 'Vocational Education (Kaushal Vikas)',
    subjectCode: '444',
    class: '9',
    academicSession: '2026-27',
    title: 'Introduction to Agricultural Practices (कृषि पद्धतियों का परिचय)',
    chapterNumber: 1,
    unitNumber: 1,
    unitName: 'Unit I: Work with Life Forms (जीव रूपों के साथ कार्य)',
    description: 'Foundations of farming, soil preparation, seed selection, crop seasons (Kharif, Rabi, Zaid), organic manure, composting, and water conservation.',
    defaultEstimatedHours: 5,
    examWeightage: 'critical',
    difficulty: 'easy',
    prerequisites: [],
    inCbseSyllabus: true,
    topics: [
      { id: 'c9-kv1-t1', name: 'Soil types, tillage, vermicomposting and bio-fertilizers', inCbseSyllabus: true },
      { id: 'c9-kv1-t2', name: 'Agronomic crop cycle, nursery raising, and weed control', inCbseSyllabus: true }
    ],
    officialNcertUrl: OFFICIAL_CBSE_SKILL_PORTAL,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SKILL_PORTAL,
  },
  {
    id: 'c9-kv-2',
    subjectId: 'cbse-9-kaushal-vikas',
    subjectName: 'Vocational Education (Kaushal Vikas)',
    subjectCode: '444',
    class: '9',
    academicSession: '2026-27',
    title: 'Rooftop Gardening & Urban Farming (रूफटॉप गार्डनिंग एवं शहरी सूक्ष्म खेती)',
    chapterNumber: 2,
    unitNumber: 1,
    unitName: 'Unit I: Work with Life Forms (जीव रूपों के साथ कार्य)',
    description: 'Design and management of rooftop and vertical gardens, container farming, potting mixes, microgreens, and domestic organic vegetables.',
    defaultEstimatedHours: 5,
    examWeightage: 'high',
    difficulty: 'easy',
    prerequisites: ['c9-kv-1'],
    inCbseSyllabus: true,
    topics: [
      { id: 'c9-kv2-t1', name: 'Potting media, cocopeat, drainage, and container selection', inCbseSyllabus: true },
      { id: 'c9-kv2-t2', name: 'Kitchen gardening, herbs, microgreens, and vertical wall planters', inCbseSyllabus: true }
    ],
    officialNcertUrl: OFFICIAL_CBSE_SKILL_PORTAL,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SKILL_PORTAL,
  },
  {
    id: 'c9-kv-3',
    subjectId: 'cbse-9-kaushal-vikas',
    subjectName: 'Vocational Education (Kaushal Vikas)',
    subjectCode: '444',
    class: '9',
    academicSession: '2026-27',
    title: 'Precision Farming & Sustainable Irrigation (सटीक खेती एवं टिकाऊ सिंचाई)',
    chapterNumber: 3,
    unitNumber: 1,
    unitName: 'Unit I: Work with Life Forms (जीव रूपों के साथ कार्य)',
    description: 'Modern sensor-guided agriculture, drip irrigation, fertigation, smart moisture probes, polyhouse climate management, and water budgeting.',
    defaultEstimatedHours: 6,
    examWeightage: 'high',
    difficulty: 'medium',
    prerequisites: ['c9-kv-1'],
    inCbseSyllabus: true,
    topics: [
      { id: 'c9-kv3-t1', name: 'Drip and micro-sprinkler setup, emitters, and water filters', inCbseSyllabus: true },
      { id: 'c9-kv3-t2', name: 'Soil moisture sensors, automated fertigation, and polyhouse climate control', inCbseSyllabus: true }
    ],
    officialNcertUrl: OFFICIAL_CBSE_SKILL_PORTAL,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SKILL_PORTAL,
  },
  {
    id: 'c9-kv-4',
    subjectId: 'cbse-9-kaushal-vikas',
    subjectName: 'Vocational Education (Kaushal Vikas)',
    subjectCode: '444',
    class: '9',
    academicSession: '2026-27',
    title: 'Allied Agricultural Vocations (मशरूम, एक्वापोनिक्स एवं संबद्ध कृषि व्यवसाय)',
    chapterNumber: 4,
    unitNumber: 1,
    unitName: 'Unit I: Work with Life Forms (जीव रूपों के साथ कार्य)',
    description: 'Commercial oyster and button mushroom cultivation, aquaponics symbiotic systems, freshwater pisciculture, and backyard poultry care.',
    defaultEstimatedHours: 6,
    examWeightage: 'high',
    difficulty: 'medium',
    prerequisites: ['c9-kv-1'],
    inCbseSyllabus: true,
    topics: [
      { id: 'c9-kv4-t1', name: 'Mushroom spawning, substrate preparation, temperature/humidity monitoring', inCbseSyllabus: true },
      { id: 'c9-kv4-t2', name: 'Aquaponics nitrogen cycle, fish rearing, and hydro-vegetable harvest', inCbseSyllabus: true }
    ],
    officialNcertUrl: OFFICIAL_CBSE_SKILL_PORTAL,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SKILL_PORTAL,
  },
  {
    id: 'c9-kv-5',
    subjectId: 'cbse-9-kaushal-vikas',
    subjectName: 'Vocational Education (Kaushal Vikas)',
    subjectCode: '444',
    class: '9',
    academicSession: '2026-27',
    title: 'Shaping Materials: Sheet Metal, Pottery & Woodcraft (सामग्रियों को आकार देना)',
    chapterNumber: 5,
    unitNumber: 2,
    unitName: 'Unit II: Work with Machines and Materials (मशीनों और सामग्रियों के साथ कार्य)',
    description: 'Material fabrication, sheet metal cutting and bending, traditional and wheel pottery, joinery, chiseling, safety tools, and recycled material craft.',
    defaultEstimatedHours: 6,
    examWeightage: 'critical',
    difficulty: 'medium',
    prerequisites: [],
    inCbseSyllabus: true,
    topics: [
      { id: 'c9-kv5-t1', name: 'Sheet metal shearing, punching, soldering, and protective gear', inCbseSyllabus: true },
      { id: 'c9-kv5-t2', name: 'Clay preparation, centering on wheel, glazing, and wood joints (lap, mortise)', inCbseSyllabus: true }
    ],
    officialNcertUrl: OFFICIAL_CBSE_SKILL_PORTAL,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SKILL_PORTAL,
  },
  {
    id: 'c9-kv-6',
    subjectId: 'cbse-9-kaushal-vikas',
    subjectName: 'Vocational Education (Kaushal Vikas)',
    subjectCode: '444',
    class: '9',
    academicSession: '2026-27',
    title: 'Construction & Civil Masonry (भवन निर्माण तकनीक एवं राजमिस्त्री कार्य)',
    chapterNumber: 6,
    unitNumber: 2,
    unitName: 'Unit II: Work with Machines and Materials (मशीनों और सामग्रियों के साथ कार्य)',
    description: 'Construction drawings reading, cement-mortar ratios, brick bonds (English & Flemish), spirit level alignment, and green building materials.',
    defaultEstimatedHours: 5,
    examWeightage: 'high',
    difficulty: 'medium',
    prerequisites: ['c9-kv-5'],
    inCbseSyllabus: true,
    topics: [
      { id: 'c9-kv6-t1', name: 'Cement, sand, aggregate ratios and mortar preparation', inCbseSyllabus: true },
      { id: 'c9-kv6-t2', name: 'Plumb-line, spirit level, bricklaying bonds, and eco-friendly AAC blocks', inCbseSyllabus: true }
    ],
    officialNcertUrl: OFFICIAL_CBSE_SKILL_PORTAL,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SKILL_PORTAL,
  },
  {
    id: 'c9-kv-7',
    subjectId: 'cbse-9-kaushal-vikas',
    subjectName: 'Vocational Education (Kaushal Vikas)',
    subjectCode: '444',
    class: '9',
    academicSession: '2026-27',
    title: 'Apparel Design, Tailoring & Textile Craft (परिधान डिजाइन एवं वस्त्र निर्माण)',
    chapterNumber: 7,
    unitNumber: 2,
    unitName: 'Unit II: Work with Machines and Materials (मशीनों और सामग्रियों के साथ कार्य)',
    description: 'Fabrics classification (natural vs synthetic), sewing machine operation, body measurements, pattern drafting, seam types, and embroidery embellishment.',
    defaultEstimatedHours: 5,
    examWeightage: 'high',
    difficulty: 'easy',
    prerequisites: [],
    inCbseSyllabus: true,
    topics: [
      { id: 'c9-kv7-t1', name: 'Sewing machine threading, tension adjustment, and maintenance', inCbseSyllabus: true },
      { id: 'c9-kv7-t2', name: 'Measurement taking, paper pattern layout, and straight/French seams', inCbseSyllabus: true }
    ],
    officialNcertUrl: OFFICIAL_CBSE_SKILL_PORTAL,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SKILL_PORTAL,
  },
  {
    id: 'c9-kv-8',
    subjectId: 'cbse-9-kaushal-vikas',
    subjectName: 'Vocational Education (Kaushal Vikas)',
    subjectCode: '444',
    class: '9',
    academicSession: '2026-27',
    title: 'Applied Industrial Vocations: Plumbing & Electrical Repair (प्लंबिंग व विद्युत अनुरक्षण)',
    chapterNumber: 8,
    unitNumber: 2,
    unitName: 'Unit II: Work with Machines and Materials (मशीनों और सामग्रियों के साथ कार्य)',
    description: 'Pipes and fittings (PVC, CPVC), leakage diagnosis, tap assembly, basic domestic electrical circuits, fuses, MCBs, grounding, and multimeter testing.',
    defaultEstimatedHours: 6,
    examWeightage: 'high',
    difficulty: 'medium',
    prerequisites: ['c9-kv-5'],
    inCbseSyllabus: true,
    topics: [
      { id: 'c9-kv8-t1', name: 'Plumbing joints, valves, washers, and water pressure testing', inCbseSyllabus: true },
      { id: 'c9-kv8-t2', name: 'Circuit wiring, earthing, tester/multimeter usage, and electrical safety norms', inCbseSyllabus: true }
    ],
    officialNcertUrl: OFFICIAL_CBSE_SKILL_PORTAL,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SKILL_PORTAL,
  },
  {
    id: 'c9-kv-9',
    subjectId: 'cbse-9-kaushal-vikas',
    subjectName: 'Vocational Education (Kaushal Vikas)',
    subjectCode: '444',
    class: '9',
    academicSession: '2026-27',
    title: 'Personal & Lifestyle Services: Wellness & Grooming (व्यक्तिगत एवं जीवनशैली सेवाएं)',
    chapterNumber: 9,
    unitNumber: 3,
    unitName: 'Unit III: Work in Human Services (मानव सेवाओं में कार्य)',
    description: 'Hygiene and skin care fundamentals, hair and scalp care, ergonomics, active listening, client consultation ethics, and fitness coaching basics.',
    defaultEstimatedHours: 5,
    examWeightage: 'critical',
    difficulty: 'easy',
    prerequisites: [],
    inCbseSyllabus: true,
    topics: [
      { id: 'c9-kv9-t1', name: 'Sanitisation, skin analysis, personal grooming, and client hygiene protocols', inCbseSyllabus: true },
      { id: 'c9-kv9-t2', name: 'Nutrition counseling, lifestyle wellness metrics, and service communication', inCbseSyllabus: true }
    ],
    officialNcertUrl: OFFICIAL_CBSE_SKILL_PORTAL,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SKILL_PORTAL,
  },
  {
    id: 'c9-kv-10',
    subjectId: 'cbse-9-kaushal-vikas',
    subjectName: 'Vocational Education (Kaushal Vikas)',
    subjectCode: '444',
    class: '9',
    academicSession: '2026-27',
    title: 'Community Healthcare & Patient Assistance (सामुदायिक स्वास्थ्य सेवा व प्राथमिक उपचार)',
    chapterNumber: 10,
    unitNumber: 3,
    unitName: 'Unit III: Work in Human Services (मानव सेवाओं में कार्य)',
    description: 'Vital signs measurement (pulse, BP, SpO2, body temperature), CPR essentials, bandaging, emergency first-aid, wheelchair transport, and biomedical waste management.',
    defaultEstimatedHours: 6,
    examWeightage: 'critical',
    difficulty: 'medium',
    prerequisites: ['c9-kv-9'],
    inCbseSyllabus: true,
    topics: [
      { id: 'c9-kv10-t1', name: 'Measuring vital signs and maintaining patient log charts', inCbseSyllabus: true },
      { id: 'c9-kv10-t2', name: 'First aid for burns, fractures, choking, and biomedical waste segregation', inCbseSyllabus: true }
    ],
    officialNcertUrl: OFFICIAL_CBSE_SKILL_PORTAL,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SKILL_PORTAL,
  },
  {
    id: 'c9-kv-11',
    subjectId: 'cbse-9-kaushal-vikas',
    subjectName: 'Vocational Education (Kaushal Vikas)',
    subjectCode: '444',
    class: '9',
    academicSession: '2026-27',
    title: 'Tourism & Hospitality Management (पर्यटन, आतिथ्य एवं यात्रा प्रबंधन)',
    chapterNumber: 11,
    unitNumber: 3,
    unitName: 'Unit III: Work in Human Services (मानव सेवाओं में कार्य)',
    description: 'Indian cultural heritage tourism, tour packaging, itinerary design, hotel front desk operations, guest welcome, and ticketing procedures.',
    defaultEstimatedHours: 5,
    examWeightage: 'high',
    difficulty: 'easy',
    prerequisites: [],
    inCbseSyllabus: true,
    topics: [
      { id: 'c9-kv11-t1', name: 'Tourist destination mapping, heritage interpretation, and itinerary crafting', inCbseSyllabus: true },
      { id: 'c9-kv11-t2', name: 'Front-office reservation, check-in hospitality etiquette, and billing basics', inCbseSyllabus: true }
    ],
    officialNcertUrl: OFFICIAL_CBSE_SKILL_PORTAL,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SKILL_PORTAL,
  },
  {
    id: 'c9-kv-12',
    subjectId: 'cbse-9-kaushal-vikas',
    subjectName: 'Vocational Education (Kaushal Vikas)',
    subjectCode: '444',
    class: '9',
    academicSession: '2026-27',
    title: 'Modern Service Vocations: Retail & Logistics (खुदरा प्रबंधन एवं लॉजिस्टिक्स)',
    chapterNumber: 12,
    unitNumber: 3,
    unitName: 'Unit III: Work in Human Services (मानव सेवाओं में कार्य)',
    description: 'Retail store layout, shelf merchandising, barcode scanning, POS billing, inventory stock checking, parcel dispatch, and customer service satisfaction.',
    defaultEstimatedHours: 5,
    examWeightage: 'high',
    difficulty: 'easy',
    prerequisites: ['c9-kv-9'],
    inCbseSyllabus: true,
    topics: [
      { id: 'c9-kv12-t1', name: 'Merchandise display, inventory FIFO tracking, and POS barcode billing', inCbseSyllabus: true },
      { id: 'c9-kv12-t2', name: 'Packaging, courier dispatch documentation, and grievance redressal', inCbseSyllabus: true }
    ],
    officialNcertUrl: OFFICIAL_CBSE_SKILL_PORTAL,
    officialCbseSyllabusUrl: OFFICIAL_CBSE_SKILL_PORTAL,
  },
];
