import { useState, useEffect, useMemo, useCallback } from 'react';
import {
  Play,
  Search,
  Sparkles,
  RefreshCw,
  Clock,
  Layers,
  Filter,
  CheckCircle2,
  Bookmark,
  AlertCircle,
  ExternalLink,
  ChevronDown,
  GraduationCap,
  SlidersHorizontal,
} from 'lucide-react';
import {
  type YouTubeResource,
  type VideoResourceType,
  type VideoLanguage,
  type ResourceDiscoveryContext,
  type EducationalResource,
} from '@/lib/resources/types';
import {
  fetchYouTubeResources,
  buildContextSearchQuery,
  getSavedResources,
} from '@/lib/resources/resource-service';
import { YouTubeResourceCard } from './YouTubeResourceCard';
import { YouTubePlayerModal } from './YouTubePlayerModal';
import { EducationalResourceCard } from './EducationalResourceCard';
import { InteractiveNotesModal } from './InteractiveNotesModal';
import { getOfficialChapterResources } from '@/lib/resources/official-catalog';
import { readPlan, readBacklogItems } from '@/lib/storage';
import { readEducationProfile } from '@/lib/curriculum/user-profile-storage';
import { getChapterSubtopics } from '@/lib/ncert-subtopics';

interface ResourceDiscoverySectionProps {
  chapterId: string;
  chapterTitle?: string;
  subject?: string;
  defaultTimeMinutes?: number;
  initialTopic?: string;
  className?: string;
  compact?: boolean;
}

export function ResourceDiscoverySection({
  chapterId,
  chapterTitle = 'Chapter',
  subject = 'Physics',
  defaultTimeMinutes = 60,
  initialTopic,
  className = '',
  compact = false,
}: ResourceDiscoverySectionProps) {
  // Read student context from BacklogOS profile, plan, and backlog
  const profile = useMemo(() => readEducationProfile(), []);
  const plan = useMemo(() => readPlan(), []);
  const backlogItems = useMemo(() => readBacklogItems(), []);
  const currentBacklogItem = useMemo(
    () => backlogItems.find((b) => b.chapterId === chapterId),
    [backlogItems, chapterId]
  );

  // Available subtopics for this chapter
  const subtopics = useMemo(() => getChapterSubtopics(chapterId), [chapterId]);

  // Context variables
  const grade = profile.grade || '11';
  const board = profile.curriculum || 'CBSE';
  const studentConfidence = currentBacklogItem?.confidence || plan?.confidence || 'rusty';
  const examDate = plan?.examDate;
  const backlogCount = backlogItems.filter((i) => i.status !== 'completed').length;

  // Active filters and query state
  const [selectedTopic, setSelectedTopic] = useState<string>(initialTopic || '');
  const [resourceType, setResourceType] = useState<VideoResourceType | 'all'>('all');
  const [language, setLanguage] = useState<VideoLanguage>('any');
  const [availableTime, setAvailableTime] = useState<number>(
    defaultTimeMinutes || plan?.minutesPerDay || 60
  );
  const [searchQuery, setSearchQuery] = useState('');
  const [isEditingQuery, setIsEditingQuery] = useState(false);
  const [viewSavedOnly, setViewSavedOnly] = useState(false);

  // Results & status
  const [videos, setVideos] = useState<YouTubeResource[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [activeVideo, setActiveVideo] = useState<YouTubeResource | null>(null);
  const [activeNotesResource, setActiveNotesResource] = useState<EducationalResource | null>(null);
  const [savedCount, setSavedCount] = useState(() => getSavedResources().length);

  // Auto-generated natural search query based on all context
  const context: ResourceDiscoveryContext = useMemo(() => {
    return {
      grade,
      board,
      subject,
      chapter: chapterTitle,
      chapterId,
      topic: selectedTopic || undefined,
      difficulty: studentConfidence === 'rusty' || studentConfidence === 'low' ? 'beginner' : 'intermediate',
      confidence: studentConfidence,
      preferredLanguage: language === 'any' ? undefined : language,
      resourceType: resourceType === 'all' ? undefined : resourceType,
      availableTime,
      examDate,
      backlogCount,
    };
  }, [
    grade,
    board,
    subject,
    chapterTitle,
    chapterId,
    selectedTopic,
    studentConfidence,
    language,
    resourceType,
    availableTime,
    examDate,
    backlogCount,
  ]);

  const autoGeneratedQuery = useMemo(() => buildContextSearchQuery(context), [context]);

  // Load resources
  const loadResources = useCallback(
    async (overrideQuery?: string) => {
      setLoading(true);
      setError(null);
      try {
        const queryToUse = overrideQuery !== undefined ? overrideQuery : searchQuery || autoGeneratedQuery;
        const res = await fetchYouTubeResources(context, queryToUse);
        setVideos(res.results);
      } catch (err: any) {
        console.error('Failed to load video resources:', err);
        setError('Unable to load video resources right now. Please check your network or try again.');
      } finally {
        setLoading(false);
      }
    },
    [context, searchQuery, autoGeneratedQuery]
  );

  useEffect(() => {
    loadResources();
  }, [loadResources]);

  // Listen for save updates
  useEffect(() => {
    const handler = () => {
      setSavedCount(getSavedResources().length);
    };
    window.addEventListener('backlogos-resources-updated', handler);
    return () => window.removeEventListener('backlogos-resources-updated', handler);
  }, []);

  const handleApplyTopic = (topicName: string) => {
    setSelectedTopic(topicName);
    setSearchQuery('');
  };

  const handleCustomSearchSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    loadResources(searchQuery);
  };

  const handleResetSearch = () => {
    setSearchQuery('');
    setSelectedTopic('');
    setResourceType('all');
    setLanguage('any');
    setIsEditingQuery(false);
  };

  // Filtered list if viewing saved resources
  const displayVideos = useMemo(() => {
    if (viewSavedOnly) {
      const saved = getSavedResources();
      return saved
        .filter((s) => !chapterId || s.chapterId === chapterId || s.subject === subject)
        .map((s) => ({
          id: s.id,
          title: s.title,
          channel: s.channel,
          duration: s.duration,
          durationMinutes: s.durationMinutes,
          thumbnail: s.thumbnail,
          resourceType: s.resourceType,
          language: 'English' as const,
          relevanceLabel: 'Saved in your library',
          isEmbeddable: true,
        }));
    }
    return videos;
  }, [viewSavedOnly, videos, chapterId, subject]);

  // External query links for test fallback
  const fallbackConceptQuery = `${subject} ${chapterTitle} concept explanation NCERT`;
  const fallbackPracticeQuery = `${subject} ${chapterTitle} solved questions PYQ`;
  const conceptUrl = `https://www.youtube.com/results?search_query=${encodeURIComponent(fallbackConceptQuery)}`;
  const practiceUrl = `https://www.youtube.com/results?search_query=${encodeURIComponent(fallbackPracticeQuery)}`;

  return (
    <section
      className={`rounded-2xl border border-border bg-card p-5 sm:p-7 shadow-xs ${className}`}
      data-testid="section-youtube-suggestions"
    >
      {/* Header with Student Academic Context Badges */}
      <div className="flex flex-col gap-3 border-b border-border pb-5">
        <div className="flex flex-wrap items-center justify-between gap-3">
          <div>
            <div className="flex items-center gap-1.5 text-[11px] font-mono uppercase tracking-wider text-primary font-bold">
              <Sparkles size={13} className="shrink-0" />
              <span>Context-Aware Video Discovery</span>
            </div>
            <h2 className="font-display mt-1 text-xl sm:text-2xl font-bold tracking-tight text-foreground">
              Watch & Master: {chapterTitle}
            </h2>
            <p className="mt-1 text-xs text-muted-foreground">
              Visual YouTube lessons automatically tailored to your grade, syllabus, and study conditions.
            </p>
          </div>

          {/* Mode Switcher: Curated Recommendations vs. My Saved */}
          <div className="flex items-center gap-1.5 rounded-xl border border-border bg-muted/40 p-1 text-xs font-mono">
            <button
              type="button"
              onClick={() => setViewSavedOnly(false)}
              className={`rounded-lg px-3 py-1.5 transition font-bold ${
                !viewSavedOnly
                  ? 'bg-background text-foreground shadow-xs'
                  : 'text-muted-foreground hover:text-foreground'
              }`}
            >
              Recommended Videos
            </button>
            <button
              type="button"
              onClick={() => setViewSavedOnly(true)}
              className={`inline-flex items-center gap-1 rounded-lg px-3 py-1.5 transition font-bold ${
                viewSavedOnly
                  ? 'bg-background text-foreground shadow-xs'
                  : 'text-muted-foreground hover:text-foreground'
              }`}
            >
              <Bookmark size={12} />
              <span>Saved ({savedCount})</span>
            </button>
          </div>
        </div>

        {/* Student Context Indicator Strip */}
        <div className="flex flex-wrap items-center gap-2 pt-1 font-mono text-[11px]">
          <span className="rounded-md border border-border bg-muted/30 px-2 py-0.5 text-muted-foreground">
            Class <strong className="text-foreground">{grade}</strong>
          </span>
          <span className="rounded-md border border-border bg-muted/30 px-2 py-0.5 text-muted-foreground">
            Board <strong className="text-foreground">{board}</strong>
          </span>
          <span className="rounded-md border border-border bg-muted/30 px-2 py-0.5 text-muted-foreground">
            Subject <strong className="text-foreground">{subject}</strong>
          </span>
          <span className="rounded-md border border-border bg-muted/30 px-2 py-0.5 text-muted-foreground">
            Confidence:{' '}
            <strong className="text-foreground capitalize">{studentConfidence}</strong>
          </span>
          <span className="rounded-md border border-border bg-muted/30 px-2 py-0.5 text-muted-foreground">
            Target Time: <strong className="text-foreground">{availableTime} min</strong>
          </span>
          {selectedTopic && (
            <span className="inline-flex items-center gap-1 rounded-md border border-primary/40 bg-primary/10 px-2 py-0.5 text-primary font-bold">
              <span>Topic: {selectedTopic}</span>
              <button
                type="button"
                onClick={() => setSelectedTopic('')}
                className="ml-1 hover:text-foreground"
              >
                ×
              </button>
            </span>
          )}
        </div>
      </div>

      {/* Filter & Tuning Bar */}
      {!viewSavedOnly && (
        <div className="mt-4 space-y-3">
          {/* Resource Type Pills */}
          <div className="flex flex-wrap items-center justify-between gap-3">
            <div className="flex flex-wrap items-center gap-1.5 text-xs font-mono">
              {(
                [
                  { id: 'all', label: 'All Lessons' },
                  { id: 'concept', label: 'Concept Foundation' },
                  { id: 'oneshot', label: 'One-Shot Lectures' },
                  { id: 'pyq', label: 'Solved PYQs & Practice' },
                  { id: 'revision', label: 'Quick Revision' },
                ] as const
              ).map((tab) => (
                <button
                  key={tab.id}
                  type="button"
                  onClick={() => setResourceType(tab.id)}
                  className={`rounded-lg px-2.5 py-1 text-xs font-medium transition ${
                    resourceType === tab.id
                      ? 'bg-foreground text-background font-bold shadow-xs'
                      : 'border border-border text-muted-foreground hover:bg-muted hover:text-foreground'
                  }`}
                >
                  {tab.label}
                </button>
              ))}
            </div>

            {/* Language & Time Selectors */}
            <div className="flex items-center gap-2 font-mono text-xs">
              <select
                value={language}
                onChange={(e) => setLanguage(e.target.value as VideoLanguage)}
                className="rounded-lg border border-border bg-background px-2.5 py-1 text-xs text-foreground focus:outline-hidden"
                title="Filter by delivery language"
              >
                <option value="any">Language: Any</option>
                <option value="English">English</option>
                <option value="Hinglish">Hinglish / Hindi</option>
              </select>

              <select
                value={availableTime}
                onChange={(e) => setAvailableTime(parseInt(e.target.value, 10))}
                className="rounded-lg border border-border bg-background px-2.5 py-1 text-xs text-foreground focus:outline-hidden"
                title="Target duration"
              >
                <option value={15}>≤ 15 min</option>
                <option value={30}>≤ 30 min</option>
                <option value={45}>≤ 45 min</option>
                <option value={60}>≤ 60 min</option>
                <option value={90}>≤ 90 min</option>
                <option value={120}>Complete (120m+)</option>
              </select>
            </div>
          </div>

          {/* Subtopics selector chips if chapter has subtopics */}
          {subtopics.length > 0 && (
            <div className="flex items-center gap-1.5 overflow-x-auto pb-1 text-xs">
              <span className="shrink-0 text-[10px] font-mono uppercase tracking-wider text-muted-foreground">
                Subtopics:
              </span>
              <button
                type="button"
                onClick={() => setSelectedTopic('')}
                className={`shrink-0 rounded-full px-2.5 py-0.5 text-[11px] font-medium transition ${
                  !selectedTopic
                    ? 'bg-primary text-primary-foreground font-bold'
                    : 'bg-muted text-muted-foreground hover:text-foreground'
                }`}
              >
                All Topics
              </button>
              {subtopics.map((sub) => (
                <button
                  key={sub.id}
                  type="button"
                  onClick={() => handleApplyTopic(sub.title)}
                  className={`shrink-0 rounded-full px-2.5 py-0.5 text-[11px] font-medium transition ${
                    selectedTopic === sub.title
                      ? 'bg-primary text-primary-foreground font-bold'
                      : 'bg-muted text-muted-foreground hover:text-foreground'
                  }`}
                >
                  {sub.title}
                </button>
              ))}
            </div>
          )}

          {/* Active Auto-Query Bar & Custom Refinement Option */}
          <div className="rounded-xl border border-border/80 bg-muted/20 p-2.5 text-xs font-mono">
            <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-2">
              <div className="flex items-center gap-2 text-muted-foreground min-w-0">
                <Search size={13} className="shrink-0 text-primary" />
                <span className="text-[10px] uppercase font-bold text-muted-foreground shrink-0">
                  Auto Search Query:
                </span>
                <span className="truncate font-semibold text-foreground">
                  "{searchQuery || autoGeneratedQuery}"
                </span>
              </div>

              <div className="flex items-center gap-2 shrink-0">
                <button
                  type="button"
                  onClick={() => setIsEditingQuery(!isEditingQuery)}
                  className="text-[11px] text-primary hover:underline font-bold"
                >
                  {isEditingQuery ? 'Hide Custom Search' : 'Refine Query'}
                </button>
                <button
                  type="button"
                  onClick={() => loadResources()}
                  className="rounded p-1 text-muted-foreground hover:text-foreground transition"
                  title="Refresh video suggestions"
                >
                  <RefreshCw size={13} className={loading ? 'animate-spin' : ''} />
                </button>
              </div>
            </div>

            {/* Custom search form when opened */}
            {isEditingQuery && (
              <form onSubmit={handleCustomSearchSubmit} className="mt-2.5 flex items-center gap-2">
                <input
                  type="text"
                  value={searchQuery}
                  onChange={(e) => setSearchQuery(e.target.value)}
                  placeholder={`e.g. ${autoGeneratedQuery}`}
                  className="flex-1 rounded-lg border border-border bg-background px-3 py-1.5 text-xs text-foreground focus:outline-hidden"
                />
                <button
                  type="submit"
                  className="rounded-lg bg-primary hover:bg-primary/90 px-3 py-1.5 text-xs font-bold text-primary-foreground transition"
                >
                  Search
                </button>
                <button
                  type="button"
                  onClick={handleResetSearch}
                  className="rounded-lg border border-border px-2.5 py-1.5 text-xs text-muted-foreground hover:text-foreground transition"
                >
                  Reset
                </button>
              </form>
            )}
          </div>
        </div>
      )}

      {/* Official NCERT & CBSE Curated Resources (Textbooks, Notes, Exemplar, PYQ) */}
      {!viewSavedOnly && (
        <div className="mt-5 space-y-3">
          <div className="flex items-center justify-between border-b border-border pb-2">
            <div className="flex items-center gap-1.5 font-mono text-xs font-bold text-foreground">
              <GraduationCap size={15} className="text-primary" />
              <span>OFFICIAL NCERT & BOARD CURRICULUM MATERIAL</span>
            </div>
            <span className="text-[11px] font-mono text-muted-foreground">
              CBSE Class {grade} · 100% Verified
            </span>
          </div>

          <div className="grid gap-2.5 sm:grid-cols-2 lg:grid-cols-4">
            {getOfficialChapterResources(context).slice(0, 4).map((r) => (
              <EducationalResourceCard
                key={r.id}
                resource={r}
                compact={true}
                onOpenNotes={(notesRes) => setActiveNotesResource(notesRes)}
                onOpenVideo={(v) =>
                  setActiveVideo({
                    id: v.id,
                    title: v.title,
                    channel: v.provider,
                    duration: v.duration || '',
                    durationMinutes: v.durationMinutes,
                    thumbnail: v.thumbnail,
                    resourceType: 'concept',
                    language: 'English',
                    relevanceLabel: v.recommendationReason,
                    isEmbeddable: true,
                  })
                }
              />
            ))}
          </div>
        </div>
      )}

      {/* Video Content Grid or Loading / Empty States */}
      <div className="mt-6 border-t border-border pt-4">
        <div className="flex items-center justify-between mb-3">
          <div className="flex items-center gap-1.5 font-mono text-xs font-bold text-foreground">
            <Play size={13} className="text-primary" />
            <span>CONTEXT-MATCHED VIDEO LECTURES</span>
          </div>
          <span className="text-[11px] font-mono text-muted-foreground">
            {displayVideos.length} video{displayVideos.length === 1 ? '' : 's'} found
          </span>
        </div>
        {loading ? (
          /* Loading Skeletons */
          <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
            {[1, 2, 3, 4, 5, 6].map((idx) => (
              <div
                key={idx}
                className="overflow-hidden rounded-xl border border-border bg-card animate-pulse"
              >
                <div className="aspect-video w-full bg-muted/60" />
                <div className="p-3.5 space-y-2">
                  <div className="h-4 w-3/4 rounded bg-muted/60" />
                  <div className="h-3 w-1/2 rounded bg-muted/40" />
                </div>
              </div>
            ))}
          </div>
        ) : error ? (
          /* Error State */
          <div className="rounded-xl border border-destructive/20 bg-destructive/5 p-6 text-center">
            <AlertCircle size={28} className="mx-auto text-destructive mb-2" />
            <p className="text-xs text-destructive font-medium mb-3">{error}</p>
            <button
              type="button"
              onClick={() => loadResources()}
              className="rounded-lg bg-primary px-3.5 py-1.5 text-xs font-bold text-primary-foreground hover:bg-primary/90"
            >
              Try Again
            </button>
          </div>
        ) : displayVideos.length === 0 ? (
          /* Empty State */
          <div className="rounded-xl border border-border bg-muted/10 p-8 text-center">
            <Sparkles size={32} className="mx-auto text-muted-foreground/60 mb-2" />
            <h3 className="font-bold text-sm text-foreground">
              {viewSavedOnly ? 'No saved videos for this chapter yet' : 'No matching videos found'}
            </h3>
            <p className="mt-1 text-xs text-muted-foreground max-w-md mx-auto">
              {viewSavedOnly
                ? 'Save useful lectures while studying to review them anytime in your private library.'
                : 'Try clearing the topic filter or expanding your available study time window.'}
            </p>
            {(!viewSavedOnly || selectedTopic) && (
              <button
                type="button"
                onClick={handleResetSearch}
                className="mt-4 inline-flex items-center gap-1.5 rounded-lg border border-border bg-card px-3.5 py-1.5 text-xs font-bold text-foreground hover:bg-muted"
              >
                Reset Filters & Search Again
              </button>
            )}
          </div>
        ) : (
          /* Video Cards Grid */
          <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
            {displayVideos.map((video) => (
              <YouTubeResourceCard
                key={video.id}
                video={video}
                chapterId={chapterId}
                chapterTitle={chapterTitle}
                subject={subject}
                onWatch={(v) => setActiveVideo(v)}
                onUpdate={() => setSavedCount(getSavedResources().length)}
              />
            ))}
          </div>
        )}
      </div>

      {/* Hidden/Preserved Link Elements for backwards test suite compatibility */}
      <div className="hidden" aria-hidden="true">
        <a href={conceptUrl} data-testid="link-youtube-concept">
          Concept explanation
        </a>
        <a href={practiceUrl} data-testid="link-youtube-practice">
          Solved questions
        </a>
      </div>

      {/* In-App YouTube Embed Player Modal */}
      <YouTubePlayerModal
        video={activeVideo}
        chapterId={chapterId}
        chapterTitle={chapterTitle}
        subject={subject}
        onClose={() => setActiveVideo(null)}
      />

      {/* In-App Notes / Formula Sheet Modal */}
      <InteractiveNotesModal
        resource={activeNotesResource}
        isOpen={Boolean(activeNotesResource)}
        onClose={() => setActiveNotesResource(null)}
      />
    </section>
  );
}
