import { AcademicMilestone } from './types';

export const ACADEMIC_MILESTONES: AcademicMilestone[] = [
  {
    id: 'first-session',
    title: 'First Study Session',
    description: 'Completed your very first focused study block.',
    iconName: 'PlayCircle',
    xpReward: 50,
    category: 'session',
    targetValue: 1,
  },
  {
    id: 'first-chapter',
    title: 'First Chapter Completed',
    description: 'Fully finished a syllabus chapter according to NCERT standard.',
    iconName: 'CheckCircle2',
    xpReward: 150,
    category: 'chapter',
    targetValue: 1,
  },
  {
    id: 'first-backlog-cleared',
    title: 'First Backlog Cleared',
    description: 'Reduced an overdue backlog topic to 0 hours remaining.',
    iconName: 'ShieldCheck',
    xpReward: 100,
    category: 'backlog',
    targetValue: 1,
  },
  {
    id: 'backlog-cleared-10h',
    title: 'Backlog Reduction: 10 Hours',
    description: 'Successfully cleared 10 total hours of academic backlog.',
    iconName: 'TrendingDown',
    xpReward: 200,
    category: 'backlog',
    targetValue: 10,
  },
  {
    id: 'backlog-cleared-25h',
    title: 'Major Backlog Recovery: 25h',
    description: 'Overcame 25 hours of accumulated syllabus backlog.',
    iconName: 'Zap',
    xpReward: 350,
    category: 'backlog',
    targetValue: 25,
  },
  {
    id: 'hours-studied-10',
    title: '10 Hours Studied',
    description: 'Accumulated 10 hours of verified focused learning.',
    iconName: 'Clock',
    xpReward: 100,
    category: 'hours',
    targetValue: 10,
  },
  {
    id: 'hours-studied-25',
    title: '25 Hours Studied',
    description: 'Reached a total of 25 hours of focused study time.',
    iconName: 'Clock8',
    xpReward: 200,
    category: 'hours',
    targetValue: 25,
  },
  {
    id: 'hours-studied-50',
    title: '50 Hours Studied',
    description: 'Achieved 50 logged hours of disciplined exam preparation.',
    iconName: 'Award',
    xpReward: 350,
    category: 'hours',
    targetValue: 50,
  },
  {
    id: 'hours-studied-100',
    title: '100 Hours Studied',
    description: 'A major milestone: 100 deep study hours completed.',
    iconName: 'Crown',
    xpReward: 600,
    category: 'hours',
    targetValue: 100,
  },
  {
    id: 'streak-3',
    title: '3-Day Study Consistency',
    description: 'Maintained active academic study across 3 consecutive days.',
    iconName: 'Flame',
    xpReward: 75,
    category: 'streak',
    targetValue: 3,
  },
  {
    id: 'streak-7',
    title: '7-Day Academic Streak',
    description: 'A full week of uninterrupted daily study commitment.',
    iconName: 'Flame',
    xpReward: 180,
    category: 'streak',
    targetValue: 7,
  },
  {
    id: 'streak-14',
    title: '14-Day Study Discipline',
    description: 'Two consecutive weeks of consistent daily progress.',
    iconName: 'FlameKindling',
    xpReward: 350,
    category: 'streak',
    targetValue: 14,
  },
  {
    id: 'first-revision',
    title: 'Spaced Retention Active',
    description: 'Completed your first spaced revision cycle for long-term memory.',
    iconName: 'RotateCcw',
    xpReward: 80,
    category: 'revision',
    targetValue: 1,
  },
  {
    id: 'first-test',
    title: 'Diagnostic Test Logged',
    description: 'Evaluated exam readiness by logging your first mock test or practice set.',
    iconName: 'FileCheck',
    xpReward: 100,
    category: 'test',
    targetValue: 1,
  },
  {
    id: 'first-subject-completed',
    title: 'First Subject Completed',
    description: 'Finished 100% of chapters in an entire curriculum subject.',
    iconName: 'GraduationCap',
    xpReward: 500,
    category: 'subject',
    targetValue: 1,
  },
];
